Repository Checkmarx/kics, pull requests merged in 2021-08, with the labels that each got.

#3913 feat(e2e): added tests to cover remote scans (git/https)
  e2e/cli_test.go
  e2e/fixtures/schemas/result-gl-sast.json
  e2e/fixtures/schemas/result-sarif.json
  e2e/fixtures/schemas/result.json
Labels: tests

#3981 fix: add missing descriptions url to nightly build
  .github/workflows/release-nightly.yml
Labels: CI, bug

#3984 feat: check connection before getting descriptions
  pkg/descriptions/client.go
  pkg/descriptions/client_test.go
  pkg/descriptions/descriptions.go
  pkg/descriptions/descriptions_test.go
  pkg/descriptions/mock/client_mock.go
Labels: enhancement, go

#3985 fix: debian image build
  Dockerfile.debian
Labels: CI, bug

#3982 fix(cli): correcting wrong path when printing result from remote repository
  pkg/model/summary.go
  pkg/model/summary_test.go
Labels: bug, go

#3987 fix(query): Removed problematic query to update to OPA v0.32.0
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/metadata.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/query.rego
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative1.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative2.yaml
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative3.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative4.yaml
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative5.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative6.yaml
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive1.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive2.yaml
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive3.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive4.yaml
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive5.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive6.yaml
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive_expected_result.json
Labels: query

#4019 feat: kics api spec scanner
  .github/workflows/release-apispec.yml
  .gitignore
  .goreleaser-apispec.yml
  Dockerfile.apispec
  Dockerfile.apispec.debian
  assets/queries/openAPI/general/example_not_compliant_with_schema_type/test/negative10.json
  assets/queries/openAPI/general/example_not_compliant_with_schema_type/test/negative11.yaml
  assets/queries/openAPI/general/example_not_compliant_with_schema_type/test/negative9.json
  assets/queries/openAPI/general/example_not_compliant_with_schema_type/test/negative9.yaml
  internal/console/scan.go
  internal/constants/constants.go
Labels: CI, go

#4022 fix: apispec scanner dockerfiles
  Dockerfile.apispec
  Dockerfile.apispec.debian
Labels: CI

#3997 docs: add ARM to documentation
  docs/platforms.md
  mkdocs.yml
Labels: documentation

#4026 ci: release apispec
  .github/workflows/release-apispec.yml
Labels: CI

#4025 feat(query): updated "IAM Password Without Minimum Length" query for Terraform
  assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/negative.tf
  assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/positive1.tf
  assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/positive2.tf
  assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/positive_expected_result.json
  assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/negative1.tf
  assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/positive1.tf
  assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/positive2.tf
  assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/positive_expected_result.json
  assets/queries/terraform/aws/iam_password_without_minimum_length/query.rego
  assets/queries/terraform/aws/iam_password_without_minimum_length/test/negative.tf
Labels: query, terraform, aws

#4013 refactor(query): 'object.get' function for k8s
  assets/queries/k8s/container_cpu_requests_not_equal_to_its_limits/query.rego
  assets/queries/k8s/container_memory_requests_not_equal_to_its_limits/query.rego
  assets/queries/k8s/container_requests_not_equal_to_its_limits/query.rego
  assets/queries/k8s/containers_run_with_low_uid/query.rego
  assets/queries/k8s/containers_running_as_root/query.rego
  assets/queries/k8s/containers_with_added_capabilities/query.rego
  assets/queries/k8s/containers_with_sys_admin_capabilities/query.rego
  assets/queries/k8s/cpu_limits_not_set/query.rego
  assets/queries/k8s/cpu_requests_not_set/query.rego
  assets/queries/k8s/cronjob_deadline_not_configured/query.rego
  assets/queries/k8s/default_service_account_in_use/query.rego
  assets/queries/k8s/deployment_has_no_pod_anti_affinity/query.rego
  assets/queries/k8s/host_aliases_undefined_or_empty/query.rego
  assets/queries/k8s/host_aliases_undefined_or_empty/test/positive_expected_result.json
  assets/queries/k8s/image_without_digest/query.rego
  assets/queries/k8s/ingress_controller_exposes_workload/query.rego
  assets/queries/k8s/invalid_image/query.rego
  assets/queries/k8s/invalid_image/test/positive_expected_result.json
  assets/queries/k8s/liveness_probe_is_not_defined/query.rego
  assets/queries/k8s/memory_limits_not_defined/query.rego
  assets/queries/k8s/memory_requests_not_defined/query.rego
  assets/queries/k8s/net_raw_capabilities_not_being_dropped/query.rego
  assets/queries/k8s/network_policy_is_not_targeting_any_pod/query.rego
  assets/queries/k8s/no_drop_capabilities_for_containers/query.rego
  assets/queries/k8s/not_limited_capabilities_for_pod_security_policy/query.rego
  assets/queries/k8s/object_is_using_a_deprecated_api_version/query.rego
  assets/queries/k8s/pod_misconfigured_network_policy/query.rego
  assets/queries/k8s/pod_or_container_without_security_context/query.rego
  assets/queries/k8s/privilege_escalation_allowed/query.rego
  assets/queries/k8s/psp_allows_privilege_escalation/query.rego
  assets/queries/k8s/psp_with_added_capabilities/query.rego
  assets/queries/k8s/readiness_probe_is_not_configured/query.rego
  assets/queries/k8s/root_container_not_mounted_as_read_only/query.rego
  assets/queries/k8s/seccomp_profile_is_not_configured/query.rego
  assets/queries/k8s/service_account_name_undefined_or_empty/query.rego
  assets/queries/k8s/service_account_name_undefined_or_empty/test/positive_expected_result.json
  assets/queries/k8s/service_account_token_automount_not_disabled/query.rego
  assets/queries/k8s/service_with_external_load_balance/query.rego
  assets/queries/k8s/statefulset_has_no_pod_anti_affinity/query.rego
  assets/queries/k8s/statefulset_requests_storage/query.rego
  assets/queries/k8s/tiller_deployment_is_accessible_from_within_the_cluster/query.rego
  assets/queries/k8s/using_default_namespace/query.rego
  assets/queries/k8s/volume_mount_with_os_directory_write_permissions/query.rego
  assets/queries/k8s/workload_host_port_not_specified/query.rego
Labels: query, kubernetes

#4003 feat(core): Added a ignore/disable/enable feature on commented files
  docs/running-kics.md
  pkg/engine/inspector.go
  pkg/engine/inspector_test.go
  pkg/kics/sink.go
  pkg/model/model.go
  pkg/model/model_test.go
  pkg/parser/docker/parser.go
  pkg/parser/docker/parser_test.go
  pkg/parser/json/parser.go
  pkg/parser/json/parser_test.go
  pkg/parser/parser.go
  pkg/parser/parser_test.go
  pkg/parser/terraform/terraform.go
  pkg/parser/terraform/terraform_test.go
  pkg/parser/yaml/parser.go
  pkg/parser/yaml/parser_test.go
  test/helpers.go
Labels: feature, go

#4029 feat(query): updated "IAM Policies With Full Privileges" query for Terraform
  assets/queries/terraform/aws/iam_policies_with_full_privileges/query.rego
Labels: query, terraform, aws

#4030 feat(query): added "S3 Bucket with Unsecured CORS Rule" query for Ansible, CloudFormation and Terraform
  assets/libraries/common/library.rego
  assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/metadata.json
  assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/query.rego
  assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/test/negative1.yaml
  assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/test/negative2.yaml
  assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/test/positive1.yaml
  assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/test/positive2.yaml
  assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/test/positive_expected_result.json
  assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/metadata.json
  assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/query.rego
  assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/test/negative1.yaml
  assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/test/negative2.json
  assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/test/positive1.yaml
  assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/test/positive2.json
  assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/test/positive_expected_result.json
  assets/queries/terraform/aws/s3_bucket_with_unsecured_cors_rule/metadata.json
  assets/queries/terraform/aws/s3_bucket_with_unsecured_cors_rule/query.rego
  assets/queries/terraform/aws/s3_bucket_with_unsecured_cors_rule/test/negative.tf
  assets/queries/terraform/aws/s3_bucket_with_unsecured_cors_rule/test/positive1.tf
  assets/queries/terraform/aws/s3_bucket_with_unsecured_cors_rule/test/positive2.tf
  assets/queries/terraform/aws/s3_bucket_with_unsecured_cors_rule/test/positive_expected_result.json
Labels: query, cloudformation, terraform, ansible, aws

#4032 feat(query): added "Network ACL With Unrestricted Access To SSH" and "Network ACL With Unrestricted Access To RDP" for Terraform
  assets/libraries/terraform/library.rego
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/metadata.json
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/query.rego
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/negative.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive_expected_result.json
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/metadata.json
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/query.rego
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/negative.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive_expected_result.json
  assets/queries/terraform/aws/security_group_with_unrestricted_access_to_ssh/metadata.json
  assets/queries/terraform/aws/security_group_with_unrestricted_access_to_ssh/query.rego
Labels: query, terraform, aws

#4046 fix(progress bar): Removed Counters from the progress bar (#3989)
  pkg/progress/counter/counter_progress.go
Labels: bug, go

#3900 fix(cli): fixing bug related to flag -q + adding new cli flag related to library path
  assets/libraries/ansible.rego
  assets/libraries/azureresourcemanager.rego
  assets/libraries/cloudformation.rego
  assets/libraries/common.rego
  assets/libraries/dockerfile.rego
  assets/libraries/k8s.rego
  assets/libraries/openapi.rego
  assets/libraries/terraform.rego
  docs/commands.md
  docs/creating-queries.md
  docs/dockerhub.md
  docs/queries.md
  e2e/cli_test.go
  e2e/fixtures/assets/scan_help
  internal/console/helpers/helpers.go
  internal/console/kics_test.go
  internal/console/scan.go
  pkg/engine/inspector.go
  pkg/engine/inspector_test.go
  pkg/engine/source/filesystem.go
  pkg/engine/source/filesystem_test.go
  pkg/scanner/scanner_test.go
  test/main_test.go
Labels: bug, feature, go

#4006 refactor(cli): Refactored scan to use JSON file to create flags
  docs/flags.md
  internal/console/assets/flags.json
  internal/console/assets/kics-console
  internal/console/flags.go
  internal/console/kics.go
  internal/console/scan.go
Labels: enhancement, go

#4044 feat(query): added "Certificate Has Expired" for Terraform and Ansible
  assets/libraries/common.rego
  assets/queries/ansible/aws/certificate_has_expired/metadata.json
  assets/queries/ansible/aws/certificate_has_expired/query.rego
  assets/queries/ansible/aws/certificate_has_expired/test/expiredCertificate.pem
  assets/queries/ansible/aws/certificate_has_expired/test/negative.yaml
  assets/queries/ansible/aws/certificate_has_expired/test/positive.yaml
  assets/queries/ansible/aws/certificate_has_expired/test/positive_expected_result.json
  assets/queries/ansible/aws/certificate_has_expired/test/validCertificate.pem
  assets/queries/terraform/aws/certificate_has_expired/metadata.json
  assets/queries/terraform/aws/certificate_has_expired/query.rego
  assets/queries/terraform/aws/certificate_has_expired/test/expiredCertificate.pem
  assets/queries/terraform/aws/certificate_has_expired/test/negative.tf
  assets/queries/terraform/aws/certificate_has_expired/test/negative.yaml
  assets/queries/terraform/aws/certificate_has_expired/test/positive.tf
  assets/queries/terraform/aws/certificate_has_expired/test/positive.yaml
  assets/queries/terraform/aws/certificate_has_expired/test/positive_expected_result.json
  assets/queries/terraform/aws/certificate_has_expired/test/validCertificate.pem
Labels: query, terraform, ansible, aws

#4052 fix: apispec scanner goreleaser config
  .goreleaser-apispec.yml
Labels: CI

#4048 feat: adding make test-unit task
  Makefile
Labels: CI

#4056 refactor(flags): change disable descriptions flag
  .github/workflows/go-ci-integration.yml
  docs/commands.md
  docs/configuration-file.md
  docs/dockerhub.md
  docs/flags.md
  e2e/fixtures/assets/scan_help
  internal/console/assets/flags.json
  internal/console/flags.go
  internal/console/scan.go
Labels: go

#4050 fix: incorrect descriptionUrl in 'HTTP Port Open' query
  assets/queries/cloudFormation/http_port_open/metadata.json
Labels: query, cloudformation

#4043 feat(query): added "VPC Peering Route Table with Unrestricted CIDR" for Terraform
  assets/queries/terraform/aws/vpc_peering_route_table_with_unrestricted_cidr/metadata.json
  assets/queries/terraform/aws/vpc_peering_route_table_with_unrestricted_cidr/query.rego
  assets/queries/terraform/aws/vpc_peering_route_table_with_unrestricted_cidr/test/negative.tf
  assets/queries/terraform/aws/vpc_peering_route_table_with_unrestricted_cidr/test/positive1.tf
  assets/queries/terraform/aws/vpc_peering_route_table_with_unrestricted_cidr/test/positive2.tf
  assets/queries/terraform/aws/vpc_peering_route_table_with_unrestricted_cidr/test/positive_expected_result.json
Labels: query, terraform, aws

#4039 feat(query): added "S3 Bucket Policy Accepts HTTP Requests" for Terraform
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/metadata.json
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/query.rego
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/negative1.tf
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/negative2.tf
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/positive1.tf
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/positive2.tf
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/positive_expected_result.json
Labels: query, terraform, aws

#4042 feat(query): added "CloudTrail Log Files S3 Bucket is Publicly Accessible" for Terraform
  assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_is_publicly_accessible/metadata.json
  assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_is_publicly_accessible/query.rego
  assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_is_publicly_accessible/test/negative.tf
  assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_is_publicly_accessible/test/positive.tf
  assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_is_publicly_accessible/test/positive_expected_result.json
Labels: query, terraform, aws

#4040 feat(query): added "VPC Default Security Group Accepts All Traffic" for Terraform
  assets/queries/terraform/aws/vpc_default_security_group_accepts_all_traffic/metadata.json
  assets/queries/terraform/aws/vpc_default_security_group_accepts_all_traffic/query.rego
  assets/queries/terraform/aws/vpc_default_security_group_accepts_all_traffic/test/negative.tf
  assets/queries/terraform/aws/vpc_default_security_group_accepts_all_traffic/test/positive1.tf
  assets/queries/terraform/aws/vpc_default_security_group_accepts_all_traffic/test/positive2.tf
  assets/queries/terraform/aws/vpc_default_security_group_accepts_all_traffic/test/positive_expected_result.json
Labels: query, terraform, aws

#4041 feat(query): added "CloudTrail Log Files S3 Bucket Logging Disabled" for Terraform
  assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/metadata.json
  assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/query.rego
  assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/test/negative.tf
  assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/test/positive.tf
  assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/test/positive_expected_result.json
Labels: query, terraform, aws

#4067 feat(query): refactored query to use walk
  assets/queries/openAPI/3.0/header_object_without_schema/query.rego
  assets/queries/openAPI/3.0/header_object_without_schema/test/positive_expected_result.json
Labels: enhancement, query, openapi

#4065 feat(query): added "S3 Bucket Object Level CloudTrail Logging Disabled" for Terraform
  assets/queries/terraform/aws/s3_bucket_object_level_cloudtrail_logging_disabled/metadata.json
  assets/queries/terraform/aws/s3_bucket_object_level_cloudtrail_logging_disabled/query.rego
  assets/queries/terraform/aws/s3_bucket_object_level_cloudtrail_logging_disabled/test/negative.tf
  assets/queries/terraform/aws/s3_bucket_object_level_cloudtrail_logging_disabled/test/positive1.tf
  assets/queries/terraform/aws/s3_bucket_object_level_cloudtrail_logging_disabled/test/positive2.tf
  assets/queries/terraform/aws/s3_bucket_object_level_cloudtrail_logging_disabled/test/positive_expected_result.json
Labels: query, terraform, aws

#4068 fix(Dockerfile): removing ENTRYPOINT from debian images fixes #4066
  Dockerfile.apispec.debian
  Dockerfile.debian
Labels: bug, CI

#4074 fix: panics when path to libraries is not found
  pkg/engine/inspector.go
  pkg/engine/inspector_test.go
  pkg/engine/source/filesystem.go
  test/main_test.go
Labels: bug

#4082 fix: wrong package usage in 'getKicsDirPath' function
  pkg/engine/source/filesystem.go
Labels: bug, go

#4076 feat(query): add "EKS Node Group Remote Access" for cloudFormation
  assets/queries/cloudFormation/eks_node_group_remote_access/metadata.json
  assets/queries/cloudFormation/eks_node_group_remote_access/query.rego
  assets/queries/cloudFormation/eks_node_group_remote_access/test/negative1.yaml
  assets/queries/cloudFormation/eks_node_group_remote_access/test/negative2.json
  assets/queries/cloudFormation/eks_node_group_remote_access/test/positive1.yaml
  assets/queries/cloudFormation/eks_node_group_remote_access/test/positive2.json
  assets/queries/cloudFormation/eks_node_group_remote_access/test/positive_expected_result.json
Labels: cloudformation, aws

#4053 feat(query): add 'App Service Authentication Is Not Set' for Terraform
  assets/queries/terraform/azure/app_service_authentication_is_not_set/metadata.json
  assets/queries/terraform/azure/app_service_authentication_is_not_set/query.rego
  assets/queries/terraform/azure/app_service_authentication_is_not_set/test/negative.tf
  assets/queries/terraform/azure/app_service_authentication_is_not_set/test/positive1.tf
  assets/queries/terraform/azure/app_service_authentication_is_not_set/test/positive2.tf
  assets/queries/terraform/azure/app_service_authentication_is_not_set/test/positive_expected_result.json
Labels: terraform, azure

#4097 feat(report): Added KICS version to reports
  e2e/fixtures/E2E_CLI_032_RESULT.json
  e2e/fixtures/E2E_CLI_033_RESULT.json
  e2e/fixtures/schemas/result.json
  e2e/utils/json.go
  pkg/model/summary.go
  pkg/report/html.go
  pkg/report/json.go
  pkg/report/json_test.go
  pkg/report/pdf.go
  pkg/report/template/html/report.tmpl
Labels: enhancement, go

#4070 feat(query): add "EC2 Instance Using API Keys" for Terraform
  assets/queries/terraform/aws/ec2_instance_using_api_keys/metadata.json
  assets/queries/terraform/aws/ec2_instance_using_api_keys/query.rego
  assets/queries/terraform/aws/ec2_instance_using_api_keys/test/negative.tf
  assets/queries/terraform/aws/ec2_instance_using_api_keys/test/positive1.tf
  assets/queries/terraform/aws/ec2_instance_using_api_keys/test/positive2.tf
  assets/queries/terraform/aws/ec2_instance_using_api_keys/test/positive3.tf
  assets/queries/terraform/aws/ec2_instance_using_api_keys/test/positive4.tf
  assets/queries/terraform/aws/ec2_instance_using_api_keys/test/positive5.tf
  assets/queries/terraform/aws/ec2_instance_using_api_keys/test/positive6.tf
  assets/queries/terraform/aws/ec2_instance_using_api_keys/test/positive7.tf
  assets/queries/terraform/aws/ec2_instance_using_api_keys/test/positive8.tf
  assets/queries/terraform/aws/ec2_instance_using_api_keys/test/positive9.tf
  assets/queries/terraform/aws/ec2_instance_using_api_keys/test/positive_expected_result.json
  assets/queries/terraform/aws/ec2_instance_using_api_keys/test/terraform.tfvars
  pkg/parser/terraform/functions/default.go
Labels: query, terraform, aws

#4087 fix: KICS integrations docs and examples
  docs/integrations_gitlabci.md
  docs/integrations_jenkins.md
  examples/gitlab/KICS.gitlabci.yaml
  examples/gitlab/KICS.v2.gitlabci.yaml
  examples/jenkins/agent-docker-html-report-declarative.jenkinsfile
  examples/jenkins/agent-linux-simple-declarative.jenkinsfile
Labels: documentation, CI

#4103 fix: Network ACL queries covering more cases
  assets/libraries/terraform.rego
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/query.rego
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/negative1.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/negative2.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/negative3.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive1.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive2.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive3.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive_expected_result.json
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/query.rego
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/negative1.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/negative2.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/negative3.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive1.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive2.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive3.tf
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive_expected_result.json
Labels: terraform, aws

#4088 feat(query): add Neptune Cluster Instance is Publicly Accessible for Terraform
  assets/queries/terraform/aws/neptune_cluster_instance_is_publicly_accessible/metadata.json
  assets/queries/terraform/aws/neptune_cluster_instance_is_publicly_accessible/query.rego
  assets/queries/terraform/aws/neptune_cluster_instance_is_publicly_accessible/test/negative.tf
  assets/queries/terraform/aws/neptune_cluster_instance_is_publicly_accessible/test/positive.tf
  assets/queries/terraform/aws/neptune_cluster_instance_is_publicly_accessible/test/positive_expected_result.json
Labels: terraform, aws

#4089 feat(query): add Sagemaker Endpoint Configuration Disabled for Terraform
  assets/queries/terraform/aws/sagemaker_endpoint_configuration_encryption_disabled/metadata.json
  assets/queries/terraform/aws/sagemaker_endpoint_configuration_encryption_disabled/query.rego
  assets/queries/terraform/aws/sagemaker_endpoint_configuration_encryption_disabled/test/negative.tf
  assets/queries/terraform/aws/sagemaker_endpoint_configuration_encryption_disabled/test/positive.tf
  assets/queries/terraform/aws/sagemaker_endpoint_configuration_encryption_disabled/test/positive_expected_result.json
Labels: terraform, aws

#4083 feat(query): add API Gateway Cache Encrypted Disabled
  assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/metadata.json
  assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/query.rego
  assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/negative1.yaml
  assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/negative2.json
  assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/positive1.yaml
  assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/positive2.json
  assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/positive3.yaml
  assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/positive4.json
  assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/positive_expected_result.json
Labels: cloudformation, aws

#4061 feat(query): add MySQL Server public access enabled for Terraform
  assets/queries/terraform/azure/mysql_server_public_access_enabled/metadata.json
  assets/queries/terraform/azure/mysql_server_public_access_enabled/query.rego
  assets/queries/terraform/azure/mysql_server_public_access_enabled/test/negative.tf
  assets/queries/terraform/azure/mysql_server_public_access_enabled/test/positive1.tf
  assets/queries/terraform/azure/mysql_server_public_access_enabled/test/positive2.tf
  assets/queries/terraform/azure/mysql_server_public_access_enabled/test/positive_expected_result.json
Labels: terraform, azure

#4092 feat(query): add MariaDB Server Public Network Access Enabled for Terraform
  assets/queries/terraform/azure/mariadb_public_network_access_enabled/metadata.json
  assets/queries/terraform/azure/mariadb_public_network_access_enabled/query.rego
  assets/queries/terraform/azure/mariadb_public_network_access_enabled/test/negative.tf
  assets/queries/terraform/azure/mariadb_public_network_access_enabled/test/positive.tf
  assets/queries/terraform/azure/mariadb_public_network_access_enabled/test/positive2.tf
  assets/queries/terraform/azure/mariadb_public_network_access_enabled/test/positive_expected_result.json
Labels: terraform, azure

#4086 feat(query): add EKS Node Group Remote Access Disabled for Terraform
  assets/queries/terraform/aws/eks_node_group_remote_access_disabled/metadata.json
  assets/queries/terraform/aws/eks_node_group_remote_access_disabled/query.rego
  assets/queries/terraform/aws/eks_node_group_remote_access_disabled/test/negative.tf
  assets/queries/terraform/aws/eks_node_group_remote_access_disabled/test/positive.tf
  assets/queries/terraform/aws/eks_node_group_remote_access_disabled/test/positive_expected_result.json
Labels: terraform, aws

#4060 feat(query): add SQL Server alert email disabled for Terraform
  assets/queries/terraform/azure/sql_server_alert_email_disabled/metadata.json
  assets/queries/terraform/azure/sql_server_alert_email_disabled/query.rego
  assets/queries/terraform/azure/sql_server_alert_email_disabled/test/negative.tf
  assets/queries/terraform/azure/sql_server_alert_email_disabled/test/positive1.tf
  assets/queries/terraform/azure/sql_server_alert_email_disabled/test/positive2.tf
  assets/queries/terraform/azure/sql_server_alert_email_disabled/test/positive_expected_result.json
Labels: terraform, azure

#4054 feat(query): add 'App Service Client Certificates Disabled' for Terraform
  assets/queries/terraform/azure/azure_app_service_client_certificate_disabled/metadata.json
  assets/queries/terraform/azure/azure_app_service_client_certificate_disabled/query.rego
  assets/queries/terraform/azure/azure_app_service_client_certificate_disabled/test/negative.tf
  assets/queries/terraform/azure/azure_app_service_client_certificate_disabled/test/positive1.tf
  assets/queries/terraform/azure/azure_app_service_client_certificate_disabled/test/positive2.tf
  assets/queries/terraform/azure/azure_app_service_client_certificate_disabled/test/positive_expected_result.json
Labels: terraform, azure

#4106 feat(query): Updated "S3 Bucket Policy Accepts HTTP Requests" for Terraform
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/query.rego
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/negative1.tf
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/negative2.tf
Labels: query, terraform, aws

#4102 fix(pkg): Treated unhandled errors in pkg(printer.go, detector/helper.go)
  internal/console/helpers/helpers.go
  internal/console/printer/printer.go
  pkg/detector/helper.go
  pkg/kics/service.go
Labels: bug, security

#4107 fix(query): Updated "CloudTrail Multi Region Disabled" for Terraform
  assets/queries/terraform/aws/cloudtrail_multi_region_disabled/metadata.json
  assets/queries/terraform/aws/cloudtrail_multi_region_disabled/query.rego
  assets/queries/terraform/aws/cloudtrail_multi_region_disabled/test/positive1.tf
  assets/queries/terraform/aws/cloudtrail_multi_region_disabled/test/positive2.tf
  assets/queries/terraform/aws/cloudtrail_multi_region_disabled/test/positive3.tf
  assets/queries/terraform/aws/cloudtrail_multi_region_disabled/test/positive_expected_result.json
Labels: query, terraform, aws

#4108 refactor(query): "CloudTrail Not Integrated With CloudWatch" for Terraform
  assets/queries/terraform/aws/cloudtrail_not_integrated_with_cloudwatch/test/negative.tf
  assets/queries/terraform/aws/cloudtrail_not_integrated_with_cloudwatch/test/positive.tf
  assets/queries/terraform/aws/cloudtrail_not_integrated_with_cloudwatch/test/positive_expected_result.json
Labels: query, terraform, aws

#4126 fix: full descriptions integration
  pkg/descriptions/descriptions.go
Labels: go

#4127 fix: remove auth information in URL closes #4125
  internal/console/scan.go
  pkg/model/summary.go
  pkg/model/summary_test.go
Labels: bug

#4128 feat: saving unit test logs as job artifact
  .github/workflows/go-ci.yml
Labels: CI, tests

#4115 feat(core): implemented embedded libraries
  assets/assets.go
  docs/commands.md
  docs/configuration-file.md
  docs/creating-queries.md
  docs/dockerhub.md
  e2e/fixtures/assets/scan_help
  internal/console/assets/scan-flags.json
  internal/console/flags/scan_flags.go
  internal/console/scan.go
  pkg/engine/inspector_test.go
  pkg/engine/source/filesystem.go
  pkg/engine/source/filesystem_test.go
  pkg/engine/source/source.go
  pkg/engine/source/source_test.go
  test/main_test.go
Labels: go

#4131 feat: multi-platform nightly builds docker image
  .github/workflows/release-nightly.yml
Labels: CI

#4134 fix: multi platform docker images
  .github/workflows/release-nightly.yml
Labels: CI

#4132 fix: cxSAST untreated error - low result
  pkg/parser/terraform/converter/default.go
Labels: go

#4133 fix: unit tests
  pkg/model/summary_test.go
Labels: go

#4135 fix: pdf report last grey line closes #4129
  pkg/report/pdf.go
Labels: go

#4140 fix(core): corrected nil pointer access on detector line array
  pkg/detector/search_line_detector.go
Labels: bug, go
