Repository Checkmarx/kics, pull requests merged in 2021-04, with the labels that each got.

#2678 Docs changes should not trigger CI #2677
  .github/workflows/go-ci-integration.yml
  .github/workflows/go-ci.yml
Labels: CI, bug

#2687 Nightly build conditional refactor #2686
  .github/workflows/nightly-release.yml
Labels: CI, bug

#2679 Removing patch from alpine semver in dockerfile
  Dockerfile.integration
Labels: CI

#2689 Fixing nightly build workflow conditional
  .github/new_changes.sh
  .github/workflows/nightly-release.yml
Labels: CI, bug

#2696 Fixing nightly build workflow
  .github/workflows/nightly-release.yml
Labels: CI, bug

#2692 Added New Flag 'ci'
  docs/getting-started.md
  internal/console/kics.go
Labels: bug, enhancement, feature, go

#2695 fix gosec issues #2694
  internal/console/kics.go
  pkg/engine/source/filesystem.go
Labels: enhancement, go

#2531 Refactored Vulnerability Builder
  go.sum
  internal/console/helpers/helpers.go
  internal/constants/constants.go
  pkg/detector/default_detect.go
  pkg/detector/default_detect_test.go
  pkg/detector/detector.go
  pkg/detector/detector_test.go
  pkg/detector/docker/docker_detect.go
  pkg/detector/docker/docker_detect_test.go
  pkg/detector/helm/helm_detect.go
  pkg/detector/helm/helm_detect_test.go
  pkg/detector/helper.go
  pkg/detector/helper_test.go
  pkg/engine/inspector.go
  pkg/engine/inspector_test.go
  pkg/engine/vulnerability_builder.go
  pkg/engine/vulnerability_builder_test.go
  pkg/kics/resolver_sink.go
  pkg/kics/service.go
  pkg/kics/service_test.go
  pkg/kics/sink.go
  pkg/model/model.go
  pkg/model/summary.go
  pkg/report/template/html/report.tmpl
  pkg/resolver/helm/resolver.go
  test/queries_content_test.go
Labels: enhancement, go

#2674 Add status code to results
  .github/workflows/go-ci-integration.yml
  cmd/console/main.go
  docs/getting-started.md
  docs/results.md
  internal/console/helpers/helpers.go
  internal/console/scan.go
  internal/constants/constants.go
  mkdocs.yml
Labels: documentation, feature, go

#2697 Typo in architecture.md
  docs/architecture.md
Labels: documentation

#2699 Add logging to invalid YAML failure on parse
  pkg/parser/yaml/parser.go
Labels: bug, enhancement

#2685 Add "Service Account Token Automount Not Disabled" query for Terraform Closes#2684
  assets/queries/k8s/service_account_token_automount_not_disabled/query.rego
  assets/queries/terraform/kubernetes/service_account_token_automount_not_disabled/metadata.json
  assets/queries/terraform/kubernetes/service_account_token_automount_not_disabled/query.rego
  assets/queries/terraform/kubernetes/service_account_token_automount_not_disabled/test/negative.tf
  assets/queries/terraform/kubernetes/service_account_token_automount_not_disabled/test/positive.tf
  assets/queries/terraform/kubernetes/service_account_token_automount_not_disabled/test/positive_expected_result.json
  assets/queries/terraform/kubernetes/service_type_is_nodeport/query.rego
Labels: query, terraform

#2448 Add Workload Host Port Not Specified query terraform
  assets/queries/k8s/image_host_port_not_specified/metadata.json
  assets/queries/k8s/image_host_port_not_specified/test/positive_expected_result.json
  assets/queries/k8s/workload_host_port_not_specified/metadata.json
  assets/queries/k8s/workload_host_port_not_specified/query.rego
  assets/queries/k8s/workload_host_port_not_specified/test/negative.yaml
  assets/queries/k8s/workload_host_port_not_specified/test/positive.yaml
  assets/queries/k8s/workload_host_port_not_specified/test/positive_expected_result.json
  assets/queries/terraform/kubernetes/workload_host_port_not_specified/metadata.json
  assets/queries/terraform/kubernetes/workload_host_port_not_specified/query.rego
  assets/queries/terraform/kubernetes/workload_host_port_not_specified/test/negative1.tf
  assets/queries/terraform/kubernetes/workload_host_port_not_specified/test/negative2.tf
  assets/queries/terraform/kubernetes/workload_host_port_not_specified/test/positive1.tf
  assets/queries/terraform/kubernetes/workload_host_port_not_specified/test/positive2.tf
  assets/queries/terraform/kubernetes/workload_host_port_not_specified/test/positive_expected_result.json
  docs/benchmark.md
Labels: query, terraform

#2666 Add Query StatefulSet Without Service Name for Terraform
  assets/queries/k8s/statefulset_without_service_name/metadata.json
  assets/queries/k8s/statefulset_without_service_name/query.rego
  assets/queries/k8s/statefulset_without_service_name/test/negative.yaml
  assets/queries/k8s/statefulset_without_service_name/test/positive.yaml
  assets/queries/k8s/statefulset_without_service_name/test/positive_expected_result.json
  assets/queries/k8s/statefulsets_without_service_name/metadata.json
  assets/queries/k8s/statefulsets_without_service_name/query.rego
  assets/queries/k8s/statefulsets_without_service_name/test/positive_expected_result.json
  assets/queries/terraform/kubernetes/statefulset_without_service_name/metadata.json
  assets/queries/terraform/kubernetes/statefulset_without_service_name/query.rego
  assets/queries/terraform/kubernetes/statefulset_without_service_name/test/negative.tf
  assets/queries/terraform/kubernetes/statefulset_without_service_name/test/positive.tf
  assets/queries/terraform/kubernetes/statefulset_without_service_name/test/positive_expected_result.json
Labels: query, terraform

#2703 Fixing nightly build docker version
  .github/workflows/nightly-release.yml
Labels: CI, bug

#2673 New tags should create prereleases #2437
  .github/workflows/release-dkr-image.yml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
  .github/workflows/update-install-script.yaml
Labels: CI

#2675 Add support to terraform vars
  docs/js/custom.js
  go.mod
  go.sum
  pkg/engine/provider/filesystem.go
  pkg/engine/provider/filesystem_test.go
  pkg/engine/provider/provider.go
  pkg/kics/sink.go
  pkg/parser/docker/parser.go
  pkg/parser/docker/parser_test.go
  pkg/parser/json/parser.go
  pkg/parser/json/parser_test.go
  pkg/parser/parser.go
  pkg/parser/terraform/converter/default.go
  pkg/parser/terraform/converter/default_test.go
  pkg/parser/terraform/terraform.go
  pkg/parser/terraform/terraform_test.go
  pkg/parser/terraform/variables.go
  pkg/parser/terraform/variables_test.go
  pkg/parser/yaml/parser.go
  pkg/parser/yaml/parser_test.go
  test/fixtures/test_terraform_variables/invalid.auto.tfvars
  test/fixtures/test_terraform_variables/terraform.tfvars
  test/fixtures/test_terraform_variables/test.tf
  test/fixtures/test_terraform_variables/test_without_variables_block.tf
  test/fixtures/test_terraform_variables/variable_set.auto.tfvars
  test/fixtures/test_terraform_variables/variables.tf
Labels: feature, terraform

#2724 Updated docs for terraform vars
  docs/getting-started.md
  docs/results.md
  docs/usage/commands.md
  docs/usage/technologies.md
  mkdocs.yml
Labels: documentation

#2732 Fixed bug that panics KICS when queries path not exists
  go.sum
  internal/console/scan.go
  pkg/parser/terraform/converter/default_test.go
Labels: bug

#2736 Adding manual trigger to docker release
  .github/workflows/release-dkr-image.yml
Labels: CI

#2737 Fixing fetching tags for shallow clones in release related workflows
  .github/workflows/release-dkr-image.yml
  .github/workflows/update-docs-index.yaml
  .github/workflows/update-install-script.yaml
Labels: CI, bug

#2702 Add "Secrets As Environment Variables" query for Terraform Closes #2701
  assets/queries/terraform/kubernetes/secrets_as_environment_variables/metadata.json
  assets/queries/terraform/kubernetes/secrets_as_environment_variables/query.rego
  assets/queries/terraform/kubernetes/secrets_as_environment_variables/test/negative.tf
  assets/queries/terraform/kubernetes/secrets_as_environment_variables/test/positive.tf
  assets/queries/terraform/kubernetes/secrets_as_environment_variables/test/positive_expected_result.json
Labels: query, terraform

#2742 Fixed pattern error on passwords query #2393
  assets/libraries/common/library.rego
  assets/queries/common/passwords_and_secrets_in_infrastructure_code/query.rego
Labels: bug, query

#2744 Disabling --ci and --silent flags #2743
  docs/usage/commands.md
  internal/console/kics.go
Labels: bug, documentation, go

#2713 Add "Readiness Probe Is Not Configured" query for Terraform Closes #2712
  assets/queries/terraform/kubernetes/readiness_probe_is_not_configured/metadata.json
  assets/queries/terraform/kubernetes/readiness_probe_is_not_configured/query.rego
  assets/queries/terraform/kubernetes/readiness_probe_is_not_configured/test/negative.tf
  assets/queries/terraform/kubernetes/readiness_probe_is_not_configured/test/positive.tf
  assets/queries/terraform/kubernetes/readiness_probe_is_not_configured/test/positive_expected_result.json
Labels: query, terraform

#2746 Added HTML report severity filter
  go.sum
  pkg/report/html.go
  pkg/report/template/html/report.css
  pkg/report/template/html/report.js
  pkg/report/template/html/report.tmpl
Labels: community, feature

#2748 Adding nightly build msteams notifications #2747
  .github/workflows/release-nightly.yml
  go.mod
  go.sum
Labels: CI

#2706 Add "No Drop Capabilities for Containers" query for Terraform Closes #2705
  assets/queries/k8s/containers_security_context_capabilities_drop_any/query.rego
  assets/queries/k8s/containers_security_context_capabilities_drop_any/test/positive_expected_result.json
  assets/queries/k8s/no_drop_capabilities_for_containers/metadata.json
  assets/queries/k8s/no_drop_capabilities_for_containers/query.rego
  assets/queries/k8s/no_drop_capabilities_for_containers/test/negative.yaml
  assets/queries/k8s/no_drop_capabilities_for_containers/test/positive.yaml
  assets/queries/k8s/no_drop_capabilities_for_containers/test/positive_expected_result.json
  assets/queries/terraform/kubernetes/no_drop_capabilities_for_containers/metadata.json
  assets/queries/terraform/kubernetes/no_drop_capabilities_for_containers/query.rego
  assets/queries/terraform/kubernetes/no_drop_capabilities_for_containers/test/negative1.tf
  assets/queries/terraform/kubernetes/no_drop_capabilities_for_containers/test/positive1.tf
  assets/queries/terraform/kubernetes/no_drop_capabilities_for_containers/test/positive2.tf
  assets/queries/terraform/kubernetes/no_drop_capabilities_for_containers/test/positive3.tf
  assets/queries/terraform/kubernetes/no_drop_capabilities_for_containers/test/positive_expected_result.json
Labels: query, terraform

#2715 Add "Deployment Has No PodAntiAffinity" query for Terraform Closes #2714
  assets/queries/k8s/deployment_has_no_pod_anti_affinity/query.rego
  assets/queries/terraform/kubernetes/deployment_has_no_pod_anti_affinity/metadata.json
  assets/queries/terraform/kubernetes/deployment_has_no_pod_anti_affinity/query.rego
  assets/queries/terraform/kubernetes/deployment_has_no_pod_anti_affinity/test/negative1.tf
  assets/queries/terraform/kubernetes/deployment_has_no_pod_anti_affinity/test/positive1.tf
  assets/queries/terraform/kubernetes/deployment_has_no_pod_anti_affinity/test/positive2.tf
  assets/queries/terraform/kubernetes/deployment_has_no_pod_anti_affinity/test/positive3.tf
  assets/queries/terraform/kubernetes/deployment_has_no_pod_anti_affinity/test/positive4.tf
  assets/queries/terraform/kubernetes/deployment_has_no_pod_anti_affinity/test/positive_expected_result.json
Labels: query, terraform

#2719 Add "API Gateway Without Security Policy" query for Terraform Closes #2718
  assets/queries/terraform/aws/api_gateway_without_security_policy/metadata.json
  assets/queries/terraform/aws/api_gateway_without_security_policy/query.rego
  assets/queries/terraform/aws/api_gateway_without_security_policy/test/negative1.tf
  assets/queries/terraform/aws/api_gateway_without_security_policy/test/positive1.tf
  assets/queries/terraform/aws/api_gateway_without_security_policy/test/positive2.tf
  assets/queries/terraform/aws/api_gateway_without_security_policy/test/positive_expected_result.json
Labels: query, terraform

#2750 Adding nightly build msteams notifications #2747
  .github/pull_request_template.md
  .github/workflows/release-nightly.yml
Labels: CI

#2753 Added versioning and created mike workflow
  .github/workflows/init-versioning.yml
  .github/workflows/mkdocs.yml
  .github/workflows/update-docs-index.yaml
  docs/js/version-mike.js
  mkdocs.yml
Labels: CI, documentation

#2708 Add "Cluster Allows Unsafe Sysctls" query for Terraform Closes #2707
  assets/queries/k8s/cluster_allows_unsafe_sysctls/metadata.json
  assets/queries/k8s/cluster_allows_unsafe_sysctls/query.rego
  assets/queries/terraform/kubernetes/cluster_allows_unsafe_sysctls/metadata.json
  assets/queries/terraform/kubernetes/cluster_allows_unsafe_sysctls/query.rego
  assets/queries/terraform/kubernetes/cluster_allows_unsafe_sysctls/test/negative1.tf
  assets/queries/terraform/kubernetes/cluster_allows_unsafe_sysctls/test/negative2.tf
  assets/queries/terraform/kubernetes/cluster_allows_unsafe_sysctls/test/positive1.tf
  assets/queries/terraform/kubernetes/cluster_allows_unsafe_sysctls/test/positive2.tf
  assets/queries/terraform/kubernetes/cluster_allows_unsafe_sysctls/test/positive_expected_result.json
Labels: query, terraform

#2751 CI improvements #2747
  .github/workflows/go-ci-integration.yml
  .github/workflows/go-ci.yml
  .github/workflows/mkdocs.yml
  .github/workflows/release-dkr-image.yml
  .github/workflows/release.yml
Labels: CI

#2755 Fixing invalid yaml in docs generator for versioning the documentation
  .github/workflows/init-versioning.yml
Labels: CI, bug

#2756 Fixing mike docs generation
  .github/workflows/init-versioning.yml
  .github/workflows/mkdocs.yml
  README.md
Labels: CI

#2721 Add "Auto Scaling Group With No Associated ELB" query for Terraform and Ansible Closes #2720
  assets/queries/ansible/aws/auto_scaling_group_with_no_associated_elb/metadata.json
  assets/queries/ansible/aws/auto_scaling_group_with_no_associated_elb/query.rego
  assets/queries/ansible/aws/auto_scaling_group_with_no_associated_elb/test/negative1.yaml
  assets/queries/ansible/aws/auto_scaling_group_with_no_associated_elb/test/negative2.yaml
  assets/queries/ansible/aws/auto_scaling_group_with_no_associated_elb/test/positive1.yaml
  assets/queries/ansible/aws/auto_scaling_group_with_no_associated_elb/test/positive2.yaml
  assets/queries/ansible/aws/auto_scaling_group_with_no_associated_elb/test/positive_expected_result.json
  assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/metadata.json
  assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/query.rego
  assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/negative1.tf
  assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/positive1.tf
  assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/positive2.tf
  assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/positive_expected_result.json
Labels: ansible, query, terraform

#2759 Updated html report docs image
  docs/img/html_report.png
Labels: documentation

#2758 Coverage different types of spec for Terraform k8s Closes#2757
  assets/libraries/terraform/library.rego
  assets/queries/terraform/kubernetes/container_host_ipc_is_true/query.rego
  assets/queries/terraform/kubernetes/container_host_pid_is_true/query.rego
  assets/queries/terraform/kubernetes/container_is_privileged/query.rego
  assets/queries/terraform/kubernetes/container_resources_limits_undefined/query.rego
  assets/queries/terraform/kubernetes/container_with_added_capabilities/query.rego
  assets/queries/terraform/kubernetes/containers_with_sys_admin_capabilities/query.rego
  assets/queries/terraform/kubernetes/cpu_limits_not_set/query.rego
  assets/queries/terraform/kubernetes/cpu_requests_not_set/query.rego
  assets/queries/terraform/kubernetes/image_without_digest/query.rego
  assets/queries/terraform/kubernetes/invalid_image/query.rego
  assets/queries/terraform/kubernetes/memory_limits_not_defined/query.rego
  assets/queries/terraform/kubernetes/memory_requests_not_defined/query.rego
  assets/queries/terraform/kubernetes/net_raw_capabilities_not_being_dropped/query.rego
  assets/queries/terraform/kubernetes/no_drop_capabilities_for_containers/query.rego
  assets/queries/terraform/kubernetes/pod_or_container_without_security_context/query.rego
  assets/queries/terraform/kubernetes/privilege_escalation_allowed/query.rego
  assets/queries/terraform/kubernetes/readiness_probe_is_not_configured/query.rego
  assets/queries/terraform/kubernetes/root_container_not_mounted_as_read_only/query.rego
  assets/queries/terraform/kubernetes/secrets_as_environment_variables/query.rego
  assets/queries/terraform/kubernetes/shared_host_network_namespace/query.rego
  assets/queries/terraform/kubernetes/shared_service_account/query.rego
Labels: query, terraform

#2754 Fix malformed files not reporting error
  pkg/parser/terraform/converter/default.go
  pkg/parser/terraform/converter/default_test.go
  pkg/parser/terraform/terraform.go
  pkg/parser/terraform/terraform_test.go
Labels: bug

#2762 Fix KICS not rendering Chart bug #2761
  pkg/engine/provider/filesystem.go
  pkg/engine/provider/filesystem_test.go
Labels: bug

#2774 Fixing arch docs img preview in .md files #2730
  docs/architecture.md
Labels: documentation

#2782 Added log when terraform.tfvars not found
  pkg/parser/terraform/variables.go
Labels: bug

#2777 Solve GoReport card issues Closes #2298
  internal/constants/constants.go
  pkg/detector/default_detect.go
  pkg/detector/docker/docker_detect.go
  pkg/engine/source/source.go
  pkg/model/model.go
  pkg/resolver/helm/helm.go
  tools/tools.go
Labels: feature, good first issue

#2763 Add "API Gateway Deployment Without Access Log Setting" query for Terraform Closes #2760
  assets/queries/cloudFormation/api_gateway_deployment_without_access_log_setting/query.rego
  assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/metadata.json
  assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/query.rego
  assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/test/negative1.tf
  assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/test/positive1.tf
  assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/test/positive2.tf
  assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/test/positive3.tf
  assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/test/positive_expected_result.json
Labels: query, terraform

#2765 Add "CMK Rotation Disabled" query for Terraform and Ansible Closes #2764
  assets/queries/ansible/aws/cmk_rotation_disabled/metadata.json
  assets/queries/ansible/aws/cmk_rotation_disabled/query.rego
  assets/queries/ansible/aws/cmk_rotation_disabled/test/negative1.yaml
  assets/queries/ansible/aws/cmk_rotation_disabled/test/positive1.yaml
  assets/queries/ansible/aws/cmk_rotation_disabled/test/positive2.yaml
  assets/queries/ansible/aws/cmk_rotation_disabled/test/positive_expected_result.json
  assets/queries/cloudFormation/cmk_rotation_disabled/metadata.json
  assets/queries/cloudFormation/cmk_rotation_disabled/query.rego
  assets/queries/cloudFormation/cmk_rotation_disabled/test/negative1.yaml
  assets/queries/cloudFormation/cmk_rotation_disabled/test/negative2.json
  assets/queries/cloudFormation/cmk_rotation_disabled/test/positive1.yaml
  assets/queries/cloudFormation/cmk_rotation_disabled/test/positive2.json
  assets/queries/cloudFormation/cmk_rotation_disabled/test/positive_expected_result.json
  assets/queries/terraform/aws/cmk_rotation_disabled/metadata.json
  assets/queries/terraform/aws/cmk_rotation_disabled/query.rego
  assets/queries/terraform/aws/cmk_rotation_disabled/test/negative1.tf
  assets/queries/terraform/aws/cmk_rotation_disabled/test/positive1.tf
  assets/queries/terraform/aws/cmk_rotation_disabled/test/positive2.tf
  assets/queries/terraform/aws/cmk_rotation_disabled/test/positive_expected_result.json
Labels: ansible, query, terraform

#2768 Add "CMK Is Unusable" query for Terraform and Ansible Closes #2766
  assets/queries/ansible/aws/cmk_is_unusable/metadata.json
  assets/queries/ansible/aws/cmk_is_unusable/query.rego
  assets/queries/ansible/aws/cmk_is_unusable/test/negative1.yaml
  assets/queries/ansible/aws/cmk_is_unusable/test/positive1.yaml
  assets/queries/ansible/aws/cmk_is_unusable/test/positive2.yaml
  assets/queries/ansible/aws/cmk_is_unusable/test/positive_expected_result.json
  assets/queries/terraform/aws/cmk_is_unusable/metadata.json
  assets/queries/terraform/aws/cmk_is_unusable/query.rego
  assets/queries/terraform/aws/cmk_is_unusable/test/negative.tf
  assets/queries/terraform/aws/cmk_is_unusable/test/positive.tf
  assets/queries/terraform/aws/cmk_is_unusable/test/positive_expected_result.json
Labels: ansible, query, terraform

#2779 Update "Volume Mount With OS Directory Write Permissions" query for Terraform Closes #2778
  assets/queries/terraform/kubernetes/volume_mount_with_os_directory_write_permissions/query.rego
Labels: query, terraform

#2667 Generate homebrew tap with goreleaser
  .github/workflows/release.yml
  .goreleaser.yml
  Makefile
  internal/console/helpers/helpers.go
  internal/console/scan.go
Labels: CI, go

#2784 Add "ALB Is Not Integrated With WAF" query for Terraform Closes #2783
  assets/queries/cloudFormation/alb_is_not_integrated_with_waf/query.rego
  assets/queries/cloudFormation/alb_is_not_integrated_with_waf/test/negative1.yaml
  assets/queries/cloudFormation/alb_is_not_integrated_with_waf/test/negative2.json
  assets/queries/cloudFormation/alb_is_not_integrated_with_waf/test/positive1.yaml
  assets/queries/cloudFormation/alb_is_not_integrated_with_waf/test/positive3.json
  assets/queries/cloudFormation/alb_is_not_integrated_with_waf/test/positive4.json
  assets/queries/terraform/aws/alb_is_not_integrated_with_waf/metadata.json
  assets/queries/terraform/aws/alb_is_not_integrated_with_waf/query.rego
  assets/queries/terraform/aws/alb_is_not_integrated_with_waf/test/negative.tf
  assets/queries/terraform/aws/alb_is_not_integrated_with_waf/test/positive.tf
  assets/queries/terraform/aws/alb_is_not_integrated_with_waf/test/positive_expected_result.json
Labels: query, terraform

#2789 fixing typo in technologies docs header fixes #2788
  docs/usage/technologies.md
  mkdocs.yml
Labels: bug, documentation

#2787 Changed order to print from info to high on console
  internal/console/helpers/helpers.go
  internal/console/helpers/helpers_test.go
  test/helpers.go
Labels: bug

#2791 Force pushing changes into mkdocs gh-pages branch
  .github/workflows/mkdocs.yml
  .github/workflows/update-docs-index.yaml
Labels: CI, documentation

#2790 Added version select to dropdown menu
  docs/css/custom.css
  docs/js/version-mike.js
Labels: documentation

#2801 pin go release version
  .github/workflows/release-nightly.yml
Labels: CI, bug

#2802 Fix nightly releases being created as draft
  .github/workflows/release-nightly.yml
Labels: CI, bug

#2797 Release docker image is not being triggered on new release #2795
  .github/workflows/release-dkr-image.yml
Labels: CI

#2800 Fixing documentation publishing without forcing changes #2799
  .github/workflows/mkdocs.yml
  .github/workflows/update-docs-index.yaml
Labels: CI, bug, documentation

#2804 Fixing technologies docs
  docs/usage/technologies.md
Labels: documentation

#2805 Fixing docs publishing workflow
  .github/workflows/mkdocs.yml
Labels: CI

#2806 Testing docs changes workflow
  docs/benchmark.md
Labels: CI, documentation

#2807 Fixing publication workflow for releases
  .github/workflows/update-docs-index.yaml
Labels: CI, bug

#2767 Fix bugs with tracker counters
  pkg/engine/provider/filesystem.go
  pkg/engine/provider/filesystem_test.go
  pkg/engine/provider/provider.go
  pkg/kics/resolver_sink.go
  pkg/kics/service.go
  pkg/kics/sink.go
Labels: bug, enhancement, go

#2775 Add --log-format and json logs #2776
  internal/console/kics.go
  internal/console/printer/printer.go
  internal/console/printer/printer_test.go
  internal/console/scan.go
Labels: feature, go

#2808 Added Open API query example #2796 #2810
  assets/libraries/openapi/library.rego
  assets/queries/openAPI/security_empty_array/metadata.json
  assets/queries/openAPI/security_empty_array/query.rego
  assets/queries/openAPI/security_empty_array/test/negative1.json
  assets/queries/openAPI/security_empty_array/test/negative2.yaml
  assets/queries/openAPI/security_empty_array/test/positive1.json
  assets/queries/openAPI/security_empty_array/test/positive2.json
  assets/queries/openAPI/security_empty_array/test/positive3.yaml
  assets/queries/openAPI/security_empty_array/test/positive4.yaml
  assets/queries/openAPI/security_empty_array/test/positive_expected_result.json
  go.sum
  pkg/engine/source/filesystem.go
  pkg/engine/source/filesystem_test.go
  pkg/parser/json/parser.go
  pkg/parser/json/parser_test.go
  pkg/parser/yaml/parser.go
  pkg/parser/yaml/parser_test.go
  test/main_test.go
Labels: go, openapi, query

#2815 Adding OpenAPI Queries Catalog Entry #2814
  mkdocs.yml
Labels: documentation, openapi

#2822 Add new category Structure and Semantics #2821
  pkg/model/sarif_categories.go
  test/queries_content_test.go
Labels: enhancement, go, openapi

#2829 Fixing docs workflow for develop version
  .github/workflows/mkdocs.yml
Labels: CI, documentation

#2840 Increased package 'helpers' coverage to 82.7% #2839
  internal/console/helpers/helpers.go
  internal/console/helpers/helpers_test.go
Labels: enhancement, go

#2824 Add Unit Tests to CMDs to increase testing coverage #2823
  codecov.yml
  internal/console/generate_id.go
  internal/console/generate_id_test.go
  internal/console/kics.go
  internal/console/kics_test.go
  internal/console/list_platforms.go
  internal/console/scan.go
  internal/console/version.go
  internal/console/version_test.go
  test/fixtures/config/kics.config_json
  test/fixtures/config/kics.config_yaml
  test/fixtures/config/kics_unknown.config_json
  test/fixtures/config/positive1.tf
Labels: enhancement, go

#2835 Test metrics using zsh script
  .github/scripts/get-test-metrics.sh
  .github/scripts/new-changes-nightly.sh
  .github/workflows/go-ci.yml
  .github/workflows/release-nightly.yml
Labels: CI

#2838 Add query "Global Server Object Uses HTTP" #2837
  assets/libraries/openapi/library.rego
  assets/queries/openAPI/global_server_uses_http/metadata.json
  assets/queries/openAPI/global_server_uses_http/query.rego
  assets/queries/openAPI/global_server_uses_http/test/negative1.json
  assets/queries/openAPI/global_server_uses_http/test/negative2.yaml
  assets/queries/openAPI/global_server_uses_http/test/positive1.json
  assets/queries/openAPI/global_server_uses_http/test/positive2.yaml
  assets/queries/openAPI/global_server_uses_http/test/positive3.yaml
  assets/queries/openAPI/global_server_uses_http/test/positive_expected_result.json
  assets/queries/openAPI/security_empty_array/query.rego
Labels: openapi, query

#2820 Added Path Server Object Uses HTTP query for OpenAPI #2819
  assets/queries/openAPI/path_server_uses_http/metadata.json
  assets/queries/openAPI/path_server_uses_http/query.rego
  assets/queries/openAPI/path_server_uses_http/test/negative1.json
  assets/queries/openAPI/path_server_uses_http/test/negative2.yaml
  assets/queries/openAPI/path_server_uses_http/test/positive1.json
  assets/queries/openAPI/path_server_uses_http/test/positive2.yaml
  assets/queries/openAPI/path_server_uses_http/test/positive_expected_result.json
  go.sum
Labels: openapi, query

#2864 Fixing unit tests
  assets/queries/openAPI/global_server_uses_http/query.rego
  assets/queries/openAPI/path_server_uses_http/query.rego
  assets/queries/openAPI/security_empty_object_definition/metadata.json
  test/queries_content_test.go
Labels: CI, go

#2867 Test metrics script should also run on pushes to master
  .github/workflows/go-ci-metrics.yaml
  .github/workflows/go-ci.yml
Labels: CI

#2870 Manual docker tag releaser
  .github/workflows/release-dkr-image-for-tag.yml
Labels: CI

#2885 Greping for version-selector in generated docs
  .github/workflows/mkdocs.yml
Labels: CI

#2886 Troubleshooting mkdocs
  .github/workflows/mkdocs.yml
Labels: CI

#2889 Refactor CI/CD workflows
  .github/scripts/docs-generator/docs-generator.py
  .github/scripts/docs-generator/requirements.txt
  .github/scripts/docs-generator/templates/general_template.md
  .github/scripts/docs-generator/templates/platform_template.md
  .github/scripts/get-test-metrics.sh
  .github/scripts/is-changed-since-last-nightly.sh
  .github/scripts/samples-linters/.cfnlintrc.yml
  .github/scripts/samples-linters/hadolint.yml
  .github/scripts/samples-linters/ignore-list/cloudformation
  .github/scripts/samples-linters/ignore-list/docker
  .github/scripts/samples-linters/ignore-list/k8s
  .github/scripts/samples-linters/ignore-list/openapi
  .github/scripts/samples-linters/ignore-list/terraform
  .github/scripts/samples-linters/validate-syntax.py
  .github/scripts/samples-linters/yamllint.yml
  .github/scripts/samples-linters/yamllint_ansible.yml
  .github/workflows/go-ci.yml
  .github/workflows/mkdocs.yml
  .github/workflows/release-dkr-image-for-tag-latest.yml
  .github/workflows/release-dkr-image-for-tag.yml
  .github/workflows/release-dkr-image.yml
  .github/workflows/release-nightly.yml
  .github/workflows/update-docs-index.yaml
  .github/workflows/update-docs-queries.yaml
  .github/workflows/validate-ansible-samples.yml
  .github/workflows/validate-cfn-samples.yml
  .github/workflows/validate-dkr-samples.yml
  .github/workflows/validate-k8s-samples.yml
  .github/workflows/validate-openapi-samples.yaml
  .github/workflows/validate-tf-samples.yml
  assets/queries/ansible/aws/alb_listening_on_http/test/negative.yaml
  assets/queries/cloudFormation/alexa_skill_plaintext_client_secret_exposed/test/negative1.yaml
  assets/queries/common/passwords_and_secrets_in_infrastructure_code/test/negative1.yaml
  assets/queries/dockerfile/add_instead_of_copy/test/negative.dockerfile
  assets/queries/k8s/cluster_admin_role_binding_with_super_user_permissions/test/negative.yaml
  assets/queries/openAPI/global_server_uses_http/test/negative2.yaml
  assets/queries/terraform/aws/alb_is_not_integrated_with_waf/test/negative.tf
Labels: CI

#2890 Triggering docs deployment
  README.md
Labels: documentation

#2891 Triggering docs deployment
  docs/index.md
Labels: documentation

#2817 Add Query Path Parameter Not Required for OpenAPI #2816
  assets/queries/openAPI/path_parameter_not_required/metadata.json
  assets/queries/openAPI/path_parameter_not_required/query.rego
  assets/queries/openAPI/path_parameter_not_required/test/negative1.json
  assets/queries/openAPI/path_parameter_not_required/test/negative2.yaml
  assets/queries/openAPI/path_parameter_not_required/test/negative3.json
  assets/queries/openAPI/path_parameter_not_required/test/negative4.yaml
  assets/queries/openAPI/path_parameter_not_required/test/positive1.json
  assets/queries/openAPI/path_parameter_not_required/test/positive2.yaml
  assets/queries/openAPI/path_parameter_not_required/test/positive3.json
  assets/queries/openAPI/path_parameter_not_required/test/positive4.yaml
  assets/queries/openAPI/path_parameter_not_required/test/positive5.json
  assets/queries/openAPI/path_parameter_not_required/test/positive6.yaml
  assets/queries/openAPI/path_parameter_not_required/test/positive_expected_result.json
  assets/queries/openAPI/security_empty_array/query.rego
Labels: openapi, query

#2834 Created query to check empty security array on operations
  assets/queries/openAPI/security_empty_array/metadata.json
  assets/queries/openAPI/security_empty_array/test/positive_expected_result.json
  assets/queries/openAPI/security_operations_empty_array/metadata.json
  assets/queries/openAPI/security_operations_empty_array/query.rego
  assets/queries/openAPI/security_operations_empty_array/test/negative1.json
  assets/queries/openAPI/security_operations_empty_array/test/negative2.yaml
  assets/queries/openAPI/security_operations_empty_array/test/positive1.json
  assets/queries/openAPI/security_operations_empty_array/test/positive2.json
  assets/queries/openAPI/security_operations_empty_array/test/positive3.json
  assets/queries/openAPI/security_operations_empty_array/test/positive4.json
  assets/queries/openAPI/security_operations_empty_array/test/positive5.yaml
  assets/queries/openAPI/security_operations_empty_array/test/positive6.yaml
  assets/queries/openAPI/security_operations_empty_array/test/positive7.yaml
  assets/queries/openAPI/security_operations_empty_array/test/positive8.yaml
  assets/queries/openAPI/security_operations_empty_array/test/positive_expected_result.json
Labels: openapi, query

#2843 Add Query "Invalid OAuth2 Token URL" #2842
  assets/libraries/openapi/library.rego
  assets/queries/openAPI/invalid_oauth2_token_url/metadata.json
  assets/queries/openAPI/invalid_oauth2_token_url/query.rego
  assets/queries/openAPI/invalid_oauth2_token_url/test/negative1.yaml
  assets/queries/openAPI/invalid_oauth2_token_url/test/negative2.json
  assets/queries/openAPI/invalid_oauth2_token_url/test/negative3.yaml
  assets/queries/openAPI/invalid_oauth2_token_url/test/positive1.yaml
  assets/queries/openAPI/invalid_oauth2_token_url/test/positive2.yaml
  assets/queries/openAPI/invalid_oauth2_token_url/test/positive3.yaml
  assets/queries/openAPI/invalid_oauth2_token_url/test/positive4.json
  assets/queries/openAPI/invalid_oauth2_token_url/test/positive5.json
  assets/queries/openAPI/invalid_oauth2_token_url/test/positive6.json
  assets/queries/openAPI/invalid_oauth2_token_url/test/positive_expected_result.json
Labels: openapi, query

#2862 Added "Servers Array Undefined" query for OpenAPI Closes #2861
  assets/queries/openAPI/servers_undefined/metadata.json
  assets/queries/openAPI/servers_undefined/query.rego
  assets/queries/openAPI/servers_undefined/test/negative1.json
  assets/queries/openAPI/servers_undefined/test/negative2.yaml
  assets/queries/openAPI/servers_undefined/test/positive1.json
  assets/queries/openAPI/servers_undefined/test/positive2.json
  assets/queries/openAPI/servers_undefined/test/positive3.yaml
  assets/queries/openAPI/servers_undefined/test/positive4.yaml
  assets/queries/openAPI/servers_undefined/test/positive_expected_result.json
Labels: openapi, query

#2812 Add Query Paths Object is Empty #2811
  assets/queries/openAPI/paths_object_empty/metadata.json
  assets/queries/openAPI/paths_object_empty/query.rego
  assets/queries/openAPI/paths_object_empty/test/negative1.json
  assets/queries/openAPI/paths_object_empty/test/negative2.yaml
  assets/queries/openAPI/paths_object_empty/test/positive1.json
  assets/queries/openAPI/paths_object_empty/test/positive2.yaml
  assets/queries/openAPI/paths_object_empty/test/positive_expected_result.json
Labels: openapi, query

#2844 Added "Operations security field has an empty object" query
  assets/queries/openAPI/security_empty_array/query.rego
  assets/queries/openAPI/security_operations_empty_object_definition/metadata.json
  assets/queries/openAPI/security_operations_empty_object_definition/query.rego
  assets/queries/openAPI/security_operations_empty_object_definition/test/negative1.json
  assets/queries/openAPI/security_operations_empty_object_definition/test/negative2.yaml
  assets/queries/openAPI/security_operations_empty_object_definition/test/positive1.json
  assets/queries/openAPI/security_operations_empty_object_definition/test/positive2.json
  assets/queries/openAPI/security_operations_empty_object_definition/test/positive3.json
  assets/queries/openAPI/security_operations_empty_object_definition/test/positive4.json
  assets/queries/openAPI/security_operations_empty_object_definition/test/positive5.yaml
  assets/queries/openAPI/security_operations_empty_object_definition/test/positive6.yaml
  assets/queries/openAPI/security_operations_empty_object_definition/test/positive7.yaml
  assets/queries/openAPI/security_operations_empty_object_definition/test/positive8.yaml
  assets/queries/openAPI/security_operations_empty_object_definition/test/positive_expected_result.json
Labels: openapi, query

#2868 Added query for undefined security scheme
  assets/queries/openAPI/security_scheme_undefined/metadata.json
  assets/queries/openAPI/security_scheme_undefined/query.rego
  assets/queries/openAPI/security_scheme_undefined/test/negative1.json
  assets/queries/openAPI/security_scheme_undefined/test/negative2.yaml
  assets/queries/openAPI/security_scheme_undefined/test/positive1.json
  assets/queries/openAPI/security_scheme_undefined/test/positive2.json
  assets/queries/openAPI/security_scheme_undefined/test/positive3.json
  assets/queries/openAPI/security_scheme_undefined/test/positive4.yaml
  assets/queries/openAPI/security_scheme_undefined/test/positive5.yaml
  assets/queries/openAPI/security_scheme_undefined/test/positive6.yaml
  assets/queries/openAPI/security_scheme_undefined/test/positive_expected_result.json
Labels: openapi, query

#2883 Add "Invalid Tag External Documentation URL" query for OpenAPI Closes#2882
  .github/scripts/is-changed-since-last-nightly.sh
  assets/libraries/openapi/library.rego
  assets/queries/openAPI/invalid_tag_external_documentation_url/metadata.json
  assets/queries/openAPI/invalid_tag_external_documentation_url/query.rego
  assets/queries/openAPI/invalid_tag_external_documentation_url/test/negative1.json
  assets/queries/openAPI/invalid_tag_external_documentation_url/test/negative2.yaml
  assets/queries/openAPI/invalid_tag_external_documentation_url/test/positive1.json
  assets/queries/openAPI/invalid_tag_external_documentation_url/test/positive2.yaml
  assets/queries/openAPI/invalid_tag_external_documentation_url/test/positive_expected_result.json
  payload.json
Labels: openapi, query

#2880 Added "Invalid Contact Email" query for OpenAPI #Closes2879
  assets/queries/openAPI/invalid_contact_email/metadata.json
  assets/queries/openAPI/invalid_contact_email/query.rego
  assets/queries/openAPI/invalid_contact_email/test/negative1.json
  assets/queries/openAPI/invalid_contact_email/test/negative2.yaml
  assets/queries/openAPI/invalid_contact_email/test/positive1.json
  assets/queries/openAPI/invalid_contact_email/test/positive2.yaml
  assets/queries/openAPI/invalid_contact_email/test/positive_expected_result.json
Labels: openapi, query

#2899 Added "Undefined Scope 'securityScheme' On Global 'security' Field" query for OpenAPI #2896
  assets/queries/openAPI/undefined_security_scope_global_security/metadata.json
  assets/queries/openAPI/undefined_security_scope_global_security/query.rego
  assets/queries/openAPI/undefined_security_scope_global_security/test/negative1.json
  assets/queries/openAPI/undefined_security_scope_global_security/test/negative2.json
  assets/queries/openAPI/undefined_security_scope_global_security/test/negative3.yaml
  assets/queries/openAPI/undefined_security_scope_global_security/test/negative4.yaml
  assets/queries/openAPI/undefined_security_scope_global_security/test/positive1.json
  assets/queries/openAPI/undefined_security_scope_global_security/test/positive2.json
  assets/queries/openAPI/undefined_security_scope_global_security/test/positive3.yaml
  assets/queries/openAPI/undefined_security_scope_global_security/test/positive4.yaml
  assets/queries/openAPI/undefined_security_scope_global_security/test/positive_expected_result.json
Labels: openapi, query

#2904 Removing payload.json
  payload.json
Labels: bug

#2852 Added Parameter Object With Schema And Content query for OpenAPI #2851
  assets/queries/openAPI/parameter_object_schema_content/metadata.json
  assets/queries/openAPI/parameter_object_schema_content/query.rego
  assets/queries/openAPI/parameter_object_schema_content/test/negative1.json
  assets/queries/openAPI/parameter_object_schema_content/test/negative2.yaml
  assets/queries/openAPI/parameter_object_schema_content/test/negative3.json
  assets/queries/openAPI/parameter_object_schema_content/test/negative4.yaml
  assets/queries/openAPI/parameter_object_schema_content/test/positive1.json
  assets/queries/openAPI/parameter_object_schema_content/test/positive2.yaml
  assets/queries/openAPI/parameter_object_schema_content/test/positive3.json
  assets/queries/openAPI/parameter_object_schema_content/test/positive4.yaml
  assets/queries/openAPI/parameter_object_schema_content/test/positive_expected_result.json
Labels: openapi, query

#2855 Added Parameter Object With Incorrect Ref query for OpenAPI #2854
  assets/queries/openAPI/parameter_object_incorrect_ref/metadata.json
  assets/queries/openAPI/parameter_object_incorrect_ref/query.rego
  assets/queries/openAPI/parameter_object_incorrect_ref/test/negative1.json
  assets/queries/openAPI/parameter_object_incorrect_ref/test/negative2.yaml
  assets/queries/openAPI/parameter_object_incorrect_ref/test/positive1.json
  assets/queries/openAPI/parameter_object_incorrect_ref/test/positive2.yaml
  assets/queries/openAPI/parameter_object_incorrect_ref/test/positive_expected_result.json
Labels: openapi, query

#2898 Added Responses With Wrong HTTP Status Code query for OpenAPI #2897
  assets/queries/openAPI/responses_wrong_http_status_code/metadata.json
  assets/queries/openAPI/responses_wrong_http_status_code/query.rego
  assets/queries/openAPI/responses_wrong_http_status_code/test/negative1.json
  assets/queries/openAPI/responses_wrong_http_status_code/test/negative2.yaml
  assets/queries/openAPI/responses_wrong_http_status_code/test/positive1.json
  assets/queries/openAPI/responses_wrong_http_status_code/test/positive2.yaml
  assets/queries/openAPI/responses_wrong_http_status_code/test/positive_expected_result.json
Labels: openapi, query

#2894 Created query for undefined scopes on operations #2884
  assets/queries/openAPI/undefined_security_scope_security_operations/metadata.json
  assets/queries/openAPI/undefined_security_scope_security_operations/query.rego
  assets/queries/openAPI/undefined_security_scope_security_operations/test/negative1.json
  assets/queries/openAPI/undefined_security_scope_security_operations/test/negative2.json
  assets/queries/openAPI/undefined_security_scope_security_operations/test/negative3.yaml
  assets/queries/openAPI/undefined_security_scope_security_operations/test/negative4.yaml
  assets/queries/openAPI/undefined_security_scope_security_operations/test/positive1.json
  assets/queries/openAPI/undefined_security_scope_security_operations/test/positive2.json
  assets/queries/openAPI/undefined_security_scope_security_operations/test/positive3.yaml
  assets/queries/openAPI/undefined_security_scope_security_operations/test/positive4.yaml
  assets/queries/openAPI/undefined_security_scope_security_operations/test/positive_expected_result.json
Labels: openapi, query

#2903 Fixing wrong platform and adding unit tests #2902
  assets/queries/terraform/kubernetes/non_kube_system_pod_with_host_mount/metadata.json
  test/queries_content_test.go
Labels: bug, terraform, tests

#2907 Adding tests docs, fixing makefile tasks
  .github/scripts/get-coverage.py
  .github/workflows/go-ci-metrics.yaml
  .github/workflows/go-ci.yml
  Makefile
  docs/creating-queries.md
  docs/getting-started.md
  docs/queries.md
  e2e/README.md
  e2e/cli_test.go
  test/README.md
Labels: CI, documentation, tests

#2888 Add "Invalid Operation External Documentation URL" query for OpenAPI #2887
  assets/queries/openAPI/invalid_operation_external_documentation_url/metadata.json
  assets/queries/openAPI/invalid_operation_external_documentation_url/query.rego
  assets/queries/openAPI/invalid_operation_external_documentation_url/test/negative1.json
  assets/queries/openAPI/invalid_operation_external_documentation_url/test/negative2.yaml
  assets/queries/openAPI/invalid_operation_external_documentation_url/test/positive1.json
  assets/queries/openAPI/invalid_operation_external_documentation_url/test/positive2.yaml
  assets/queries/openAPI/invalid_operation_external_documentation_url/test/positive_expected_result.json
Labels: openapi, query

#2912 Added Response Object With Incorrect Ref query for OpenAPI #2911
  assets/queries/openAPI/response_object_incorrect_ref/metadata.json
  assets/queries/openAPI/response_object_incorrect_ref/query.rego
  assets/queries/openAPI/response_object_incorrect_ref/test/negative1.json
  assets/queries/openAPI/response_object_incorrect_ref/test/negative2.yaml
  assets/queries/openAPI/response_object_incorrect_ref/test/positive1.json
  assets/queries/openAPI/response_object_incorrect_ref/test/positive2.yaml
  assets/queries/openAPI/response_object_incorrect_ref/test/positive_expected_result.json
Labels: openapi, query

#2916 Add pipeline examples #2876
  .dockerignore
  docs/integrations.md
  docs/integrations_gitlabci.md
  examples/azure-pipelines.yaml
  examples/bitbucket-pipelines.yaml
  examples/cx-kics-github-actions-sarif.yaml
  examples/gitlab/KICS.gitlabci.yaml
  examples/gitlab/KICS.v1.gitlabci.yaml
Labels: documentation

#2901 Add "Schema Discriminator Not Required" query for OpenAPI Closes#2900
  assets/queries/openAPI/schema_discriminator_not_required/metadata.json
  assets/queries/openAPI/schema_discriminator_not_required/query.rego
  assets/queries/openAPI/schema_discriminator_not_required/test/negative1.json
  assets/queries/openAPI/schema_discriminator_not_required/test/negative2.json
  assets/queries/openAPI/schema_discriminator_not_required/test/negative3.yaml
  assets/queries/openAPI/schema_discriminator_not_required/test/negative4.yaml
  assets/queries/openAPI/schema_discriminator_not_required/test/positive1.json
  assets/queries/openAPI/schema_discriminator_not_required/test/positive2.json
  assets/queries/openAPI/schema_discriminator_not_required/test/positive3.yaml
  assets/queries/openAPI/schema_discriminator_not_required/test/positive4.yaml
  assets/queries/openAPI/schema_discriminator_not_required/test/positive_expected_result.json
Labels: openapi, query

#2921 Added Request Body With Incorrect Ref query for OpenAPI #2920
  assets/queries/openAPI/request_body_incorrect_ref/metadata.json
  assets/queries/openAPI/request_body_incorrect_ref/query.rego
  assets/queries/openAPI/request_body_incorrect_ref/test/negative1.json
  assets/queries/openAPI/request_body_incorrect_ref/test/negative1.yaml
  assets/queries/openAPI/request_body_incorrect_ref/test/positive1.json
  assets/queries/openAPI/request_body_incorrect_ref/test/positive2.yaml
  assets/queries/openAPI/request_body_incorrect_ref/test/positive_expected_result.json
Labels: openapi, query

#2895 Added "Invalid Schema External Documentation URL" query for OpenAPI Closes#2893
  assets/queries/openAPI/invalid_schema_external_documentation_url/metadata.json
  assets/queries/openAPI/invalid_schema_external_documentation_url/query.rego
  assets/queries/openAPI/invalid_schema_external_documentation_url/test/negative1.json
  assets/queries/openAPI/invalid_schema_external_documentation_url/test/negative2.json
  assets/queries/openAPI/invalid_schema_external_documentation_url/test/negative3.yaml
  assets/queries/openAPI/invalid_schema_external_documentation_url/test/negative4yaml
  assets/queries/openAPI/invalid_schema_external_documentation_url/test/positive1.json
  assets/queries/openAPI/invalid_schema_external_documentation_url/test/positive2.json
  assets/queries/openAPI/invalid_schema_external_documentation_url/test/positive3.yaml
  assets/queries/openAPI/invalid_schema_external_documentation_url/test/positive4.yaml
  assets/queries/openAPI/invalid_schema_external_documentation_url/test/positive_expected_result.json
Labels: openapi, query

#2934 Fixed Bug with ExtractLineFragment #2933
  assets/queries/cloudFormation/api_gateway_stage_without_api_gateway_usage_plan_associated/test/positive_expected_result.json
  assets/queries/cloudFormation/ecs_service_admin_role_is_present/test/positive_expected_result.json
  assets/queries/cloudFormation/sagemaker_enabling_internet_access/test/positive_expected_result.json
  assets/queries/terraform/aws/default_vpc_exists/query.rego
  pkg/detector/helper.go
Labels: bug

#2924 Added "Success Response Code Defined for Patch Operation" query for OpenAPI
  assets/queries/openAPI/success_response_code_defined_patch_operation/metadata.json
  assets/queries/openAPI/success_response_code_defined_patch_operation/query.rego
  assets/queries/openAPI/success_response_code_defined_patch_operation/test/negative1.json
  assets/queries/openAPI/success_response_code_defined_patch_operation/test/negative2.yaml
  assets/queries/openAPI/success_response_code_defined_patch_operation/test/positive1.json
  assets/queries/openAPI/success_response_code_defined_patch_operation/test/positive2.json
  assets/queries/openAPI/success_response_code_defined_patch_operation/test/positive3.yaml
  assets/queries/openAPI/success_response_code_defined_patch_operation/test/positive4.yaml
  assets/queries/openAPI/success_response_code_defined_patch_operation/test/positive_expected_result.json
Labels: openapi, query

#2922 Added "Invalid Content Type For Multiple Files Upload" query for OpenAPI Closes#2919
  assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/metadata.json
  assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/query.rego
  assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/negative1.json
  assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/negative2.json
  assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/negative3.yaml
  assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/negative4.yaml
  assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/positive1.json
  assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/positive2.json
  assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/positive3.yaml
  assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/positive4.yaml
  assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/positive_expected_result.json
Labels: openapi, query

#2917 Added "Success Response Code Defined for Delete Operation" query for OpenAPI (#2915)
  assets/queries/openAPI/success_response_code_defined_delete_operation/metadata.json
  assets/queries/openAPI/success_response_code_defined_delete_operation/query.rego
  assets/queries/openAPI/success_response_code_defined_delete_operation/test/negative1.json
  assets/queries/openAPI/success_response_code_defined_delete_operation/test/negative2.yaml
  assets/queries/openAPI/success_response_code_defined_delete_operation/test/positive1.json
  assets/queries/openAPI/success_response_code_defined_delete_operation/test/positive2.json
  assets/queries/openAPI/success_response_code_defined_delete_operation/test/positive3.yaml
  assets/queries/openAPI/success_response_code_defined_delete_operation/test/positive4.yaml
  assets/queries/openAPI/success_response_code_defined_delete_operation/test/positive_expected_result.json
Labels: openapi, query

#2910 Added Parameter Objects Headers With Dup Name query for OpenAPI #2909
  assets/queries/openAPI/parameter_objects_headers_dup_name/metadata.json
  assets/queries/openAPI/parameter_objects_headers_dup_name/query.rego
  assets/queries/openAPI/parameter_objects_headers_dup_name/test/negative1.json
  assets/queries/openAPI/parameter_objects_headers_dup_name/test/negative2.yaml
  assets/queries/openAPI/parameter_objects_headers_dup_name/test/negative3.json
  assets/queries/openAPI/parameter_objects_headers_dup_name/test/negative4.yaml
  assets/queries/openAPI/parameter_objects_headers_dup_name/test/positive1.json
  assets/queries/openAPI/parameter_objects_headers_dup_name/test/positive2.yaml
  assets/queries/openAPI/parameter_objects_headers_dup_name/test/positive3.json
  assets/queries/openAPI/parameter_objects_headers_dup_name/test/positive4.yaml
  assets/queries/openAPI/parameter_objects_headers_dup_name/test/positive_expected_result.json
Labels: openapi, query

#2914 Added Implicit Flow in OAuth2 query for OpenAPI #2913
  assets/queries/openAPI/implicit_flow_oauth2/metadata.json
  assets/queries/openAPI/implicit_flow_oauth2/query.rego
  assets/queries/openAPI/implicit_flow_oauth2/test/negative1.json
  assets/queries/openAPI/implicit_flow_oauth2/test/negative2.yaml
  assets/queries/openAPI/implicit_flow_oauth2/test/positive1.json
  assets/queries/openAPI/implicit_flow_oauth2/test/positive2.json
  assets/queries/openAPI/implicit_flow_oauth2/test/positive3.json
  assets/queries/openAPI/implicit_flow_oauth2/test/positive4.yaml
  assets/queries/openAPI/implicit_flow_oauth2/test/positive5.yaml
  assets/queries/openAPI/implicit_flow_oauth2/test/positive6.yaml
  assets/queries/openAPI/implicit_flow_oauth2/test/positive_expected_result.json
Labels: openapi, query

#2926 Added "Success Response Code Defined for Put Operation" query for OpenAPI (#2925)
  assets/queries/openAPI/success_response_code_defined_put_operation/metadata.json
  assets/queries/openAPI/success_response_code_defined_put_operation/query.rego
  assets/queries/openAPI/success_response_code_defined_put_operation/test/negative1.json
  assets/queries/openAPI/success_response_code_defined_put_operation/test/negative2.yaml
  assets/queries/openAPI/success_response_code_defined_put_operation/test/positive1.json
  assets/queries/openAPI/success_response_code_defined_put_operation/test/positive2.json
  assets/queries/openAPI/success_response_code_defined_put_operation/test/positive3.yaml
  assets/queries/openAPI/success_response_code_defined_put_operation/test/positive4.yaml
  assets/queries/openAPI/success_response_code_defined_put_operation/test/positive_expected_result.json
Labels: openapi, query

#2928 Added Success Response Code Defined for Post Operation query for OpenAPI (#2927)
  assets/queries/openAPI/success_response_code_defined_post_operation/metadata.json
  assets/queries/openAPI/success_response_code_defined_post_operation/query.rego
  assets/queries/openAPI/success_response_code_defined_post_operation/test/negative1.json
  assets/queries/openAPI/success_response_code_defined_post_operation/test/negative2.yaml
  assets/queries/openAPI/success_response_code_defined_post_operation/test/positive1.json
  assets/queries/openAPI/success_response_code_defined_post_operation/test/positive2.json
  assets/queries/openAPI/success_response_code_defined_post_operation/test/positive3.yaml
  assets/queries/openAPI/success_response_code_defined_post_operation/test/positive4.yaml
  assets/queries/openAPI/success_response_code_defined_post_operation/test/positive_expected_result.json
Labels: openapi, query

#2939 Fixing bug in queries metrics
  .github/scripts/get-test-metrics.sh
Labels: bug

#2940 Update docs with openapi image
  README.md
  docs/img/logo-helm.png
  docs/img/logo-openapi.png
  docs/index.md
Labels: documentation

#2875 Added "Link Object OperationId Does Not Target Operation Object" query for OpenAPI Closes #2874
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/metadata.json
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/query.rego
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/test/negative1.json
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/test/negative2.json
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/test/negative3.json
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/test/negative4.yaml
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/test/negative5.yaml
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/test/negative6.yaml
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/test/positive1.json
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/test/positive2.json
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/test/positive3.json
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/test/positive4.yaml
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/test/positive5.yaml
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/test/positive6.yaml
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/test/positive_expected_result.json
Labels: openapi, query

#2931 Add "Server URL Not Absolute" query for OpenAPI #2930
  assets/queries/openAPI/server_url_not_absolute/metadata.json
  assets/queries/openAPI/server_url_not_absolute/query.rego
  assets/queries/openAPI/server_url_not_absolute/test/negative1.json
  assets/queries/openAPI/server_url_not_absolute/test/negative2.json
  assets/queries/openAPI/server_url_not_absolute/test/negative3.yaml
  assets/queries/openAPI/server_url_not_absolute/test/negative4.yaml
  assets/queries/openAPI/server_url_not_absolute/test/positive1.json
  assets/queries/openAPI/server_url_not_absolute/test/positive2.json
  assets/queries/openAPI/server_url_not_absolute/test/positive3.yaml
  assets/queries/openAPI/server_url_not_absolute/test/positive4.yaml
  assets/queries/openAPI/server_url_not_absolute/test/positive_expected_result.json
Labels: openapi, query

#2941 Add New Line to command 'generate-id'
  internal/console/generate_id.go
Labels: bug

#2943 Removed windows+arm64 from goreleaser #2942
  .goreleaser.yml
Labels: CI

#2945 fix: update-docs-index workflow
  .github/workflows/update-docs-index.yaml
Labels: CI

#2948 Moved template to be in assets folder
  assets/template/query/metadata.json
  assets/template/query/query.rego
  assets/template/query/test/negative.tf
  assets/template/query/test/positive.tf
  assets/template/query/test/positive_expected_result.json
Labels: query

#2954 Troubleshooting coverage workflow
  .github/workflows/go-ci-coverage.yaml
Labels: CI

#2953 fix: docker release workflow
  .github/workflows/release-dkr-image.yml
Labels: CI

#2951 fix: fixing usage documentation
  docs/usage/commands.md
Labels: documentation

#2955 fix: troubleshooting coverage workflow
  .github/workflows/go-ci-coverage.yaml
Labels: CI

#2956 fix: troubleshooting coverage workflow
  .github/workflows/go-ci-coverage.yaml
Labels: CI

#2977 fix(report): generate report for all supported formats, if no format is defined
  internal/console/helpers/helpers.go
  internal/console/helpers/helpers_test.go
  internal/console/scan.go
Labels: bug

#2974 test(e2e): new E2E tests scenarios (#2980)
  e2e/README.md
  e2e/cli_test.go
  e2e/fixtures/E2E_CLI_008
  e2e/fixtures/E2E_CLI_010
  e2e/fixtures/E2E_CLI_011_PAYLOAD
  e2e/fixtures/E2E_CLI_013
  e2e/fixtures/samples/terraform-single.tf
  e2e/utils.go
Labels: enhancement, go, tests

#2726 feat(engine): semantic exit code based on results (#2400) (#1721)
  .github/workflows/go-ci-integration.yml
  cmd/console/main.go
  docs/results.md
  docs/usage/commands.md
  e2e/cli_test.go
  e2e/fixtures/E2E_CLI_002
  e2e/fixtures/E2E_CLI_003
  e2e/fixtures/E2E_CLI_004
  internal/console/helpers/exit_handler.go
  internal/console/helpers/exit_handler_test.go
  internal/console/kics.go
  internal/console/scan.go
  internal/constants/constants.go
  mkdocs.yml
  pkg/parser/parser.go
Labels: enhancement, feature, go

#2961 feat(analytics) print CPU and Memory usage in logs (#2379)
  docs/benchmark.md
  docs/configuration-file.md
  docs/performance.md
  docs/usage/commands.md
  e2e/fixtures/E2E_CLI_001
  e2e/fixtures/E2E_CLI_002
  e2e/fixtures/E2E_CLI_003
  e2e/fixtures/E2E_CLI_004
  e2e/fixtures/E2E_CLI_016_INVALID_FLAG
  e2e/fixtures/E2E_CLI_016_INVALID_SCAN_FLAG
  e2e/fixtures/E2E_CLI_016_INVALID_SHOTHAND
  go.mod
  go.sum
  internal/console/helpers/helpers.go
  internal/console/kics.go
  internal/console/scan.go
  internal/metrics/cpu_metric.go
  internal/metrics/mem_metric.go
  internal/metrics/metrics.go
  mkdocs.yml
  pkg/engine/inspector.go
  pkg/kics/service.go
Labels: feature, go

#2969 feat(query): "Server Object Variable Not Used" for OpenAPI (#2968)
  assets/queries/openAPI/server_object_variable_not_used/metadata.json
  assets/queries/openAPI/server_object_variable_not_used/query.rego
  assets/queries/openAPI/server_object_variable_not_used/test/negative1.json
  assets/queries/openAPI/server_object_variable_not_used/test/negative2.json
  assets/queries/openAPI/server_object_variable_not_used/test/negative3.yaml
  assets/queries/openAPI/server_object_variable_not_used/test/negative4.yaml
  assets/queries/openAPI/server_object_variable_not_used/test/positive1.json
  assets/queries/openAPI/server_object_variable_not_used/test/positive2.json
  assets/queries/openAPI/server_object_variable_not_used/test/positive3.yaml
  assets/queries/openAPI/server_object_variable_not_used/test/positive4.yaml
  assets/queries/openAPI/server_object_variable_not_used/test/positive_expected_result.json
  assets/queries/openAPI/server_url_not_absolute/query.rego
Labels: openapi, query

#2971 feat(query): "OperationId Not Unique" for OpenAPI (#2970)
  assets/queries/openAPI/operation_id_not_unique/metadata.json
  assets/queries/openAPI/operation_id_not_unique/query.rego
  assets/queries/openAPI/operation_id_not_unique/test/negative1.json
  assets/queries/openAPI/operation_id_not_unique/test/negative2.yaml
  assets/queries/openAPI/operation_id_not_unique/test/positive1.json
  assets/queries/openAPI/operation_id_not_unique/test/positive2.yaml
  assets/queries/openAPI/operation_id_not_unique/test/positive_expected_result.json
Labels: openapi, query

#2976 feat(query) "Schema Items Undefined" for OpenAPI (#2975)
  assets/queries/openAPI/schema_items_undefined/metadata.json
  assets/queries/openAPI/schema_items_undefined/query.rego
  assets/queries/openAPI/schema_items_undefined/test/negative1.json
  assets/queries/openAPI/schema_items_undefined/test/negative2.json
  assets/queries/openAPI/schema_items_undefined/test/negative3.yaml
  assets/queries/openAPI/schema_items_undefined/test/negative4.yaml
  assets/queries/openAPI/schema_items_undefined/test/positive1.json
  assets/queries/openAPI/schema_items_undefined/test/positive2.json
  assets/queries/openAPI/schema_items_undefined/test/positive3.yaml
  assets/queries/openAPI/schema_items_undefined/test/positive4.yaml
  assets/queries/openAPI/schema_items_undefined/test/positive_expected_result.json
Labels: openapi, query

#2982 feat(query): "Schema With Both ReadOnly And WriteOnly" for OpenAPI (#2981)
  assets/queries/openAPI/schema_with_both_read_only_and_write_only/metadata.json
  assets/queries/openAPI/schema_with_both_read_only_and_write_only/query.rego
  assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/negative1.json
  assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/negative2.json
  assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/negative3.yaml
  assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/negative4.yaml
  assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/positive1.json
  assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/positive2.json
  assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/positive3.yaml
  assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/positive4.yaml
  assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/positive_expected_result.json
Labels: openapi, query

#2985 feat(query): "Security Operation Field Undefined" for OpenAPI (#2984)
  assets/queries/openAPI/security_operation_field_undefined/metadata.json
  assets/queries/openAPI/security_operation_field_undefined/query.rego
  assets/queries/openAPI/security_operation_field_undefined/test/negative1.json
  assets/queries/openAPI/security_operation_field_undefined/test/negative2.yaml
  assets/queries/openAPI/security_operation_field_undefined/test/positive1.json
  assets/queries/openAPI/security_operation_field_undefined/test/positive2.json
  assets/queries/openAPI/security_operation_field_undefined/test/positive3.yaml
  assets/queries/openAPI/security_operation_field_undefined/test/positive4.yaml
  assets/queries/openAPI/security_operation_field_undefined/test/positive_expected_result.json
Labels: openapi, query

#2990 feat(query): "Schema Discriminator Property Not String" for OpenAPI (#2989)
  assets/queries/openAPI/schema_discriminator_property_not_string/metadata.json
  assets/queries/openAPI/schema_discriminator_property_not_string/query.rego
  assets/queries/openAPI/schema_discriminator_property_not_string/test/negative1.json
  assets/queries/openAPI/schema_discriminator_property_not_string/test/negative2.json
  assets/queries/openAPI/schema_discriminator_property_not_string/test/negative3.yaml
  assets/queries/openAPI/schema_discriminator_property_not_string/test/negative4.yaml
  assets/queries/openAPI/schema_discriminator_property_not_string/test/positive1.json
  assets/queries/openAPI/schema_discriminator_property_not_string/test/positive2.json
  assets/queries/openAPI/schema_discriminator_property_not_string/test/positive3.yaml
  assets/queries/openAPI/schema_discriminator_property_not_string/test/positive4.yaml
  assets/queries/openAPI/schema_discriminator_property_not_string/test/positive_expected_result.json
Labels: openapi, query

#3017 feat(engine): multiple paths on `--path` flag
  docs/configuration-file.md
  docs/usage/commands.md
  e2e/cli_test.go
  e2e/fixtures/E2E_CLI_002
  e2e/fixtures/E2E_CLI_003
  e2e/fixtures/E2E_CLI_004
  e2e/fixtures/E2E_CLI_010
  e2e/fixtures/E2E_CLI_016_INVALID_SCAN_FLAG
  e2e/fixtures/E2E_CLI_018
  internal/console/kics_test.go
  internal/console/scan.go
  pkg/engine/inspector.go
  pkg/engine/inspector_test.go
  pkg/engine/provider/filesystem.go
  pkg/engine/provider/filesystem_test.go
  pkg/engine/provider/provider.go
  pkg/engine/similarity_id.go
  pkg/engine/similarity_id_test.go
  pkg/engine/vulnerability_builder.go
  pkg/kics/service.go
  pkg/kics/service_test.go
  test/queries_content_test.go
  test/queries_test.go
  test/similarity_id_test.go
Labels: feature, go

#2988 feat(ci): saving docker images digests and publishing dockerhub description
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/scripts/get-digest.sh
  .github/workflows/release-dkr-image-for-tag-latest.yml
  .github/workflows/release-dkr-image-for-tag.yml
  .github/workflows/release-dkr-image.yml
  .github/workflows/release-nightly.yml
  .github/workflows/update-docs-index.yaml
  .github/workflows/update-docs-queries.yaml
  .github/workflows/update-install-script.yaml
  README.md
  docs/docker/digests.csv
  docs/docker/digests.md
  docs/docker/nightly.csv
  docs/docker/nightly.md
  docs/dockerhub.md
  docs/releases.md
  docs/roadmap.md
Labels: CI

#2987 feat(query): "Security Field Undefined" for OpenAPI (#2986)
  assets/queries/openAPI/security_field_undefined/metadata.json
  assets/queries/openAPI/security_field_undefined/query.rego
  assets/queries/openAPI/security_field_undefined/test/negative1.json
  assets/queries/openAPI/security_field_undefined/test/negative2.yaml
  assets/queries/openAPI/security_field_undefined/test/positive1.json
  assets/queries/openAPI/security_field_undefined/test/positive2.json
  assets/queries/openAPI/security_field_undefined/test/positive3.yaml
  assets/queries/openAPI/security_field_undefined/test/positive4.yaml
  assets/queries/openAPI/security_field_undefined/test/positive_expected_result.json
Labels: openapi, query

#3034 fix(ci): fixing docker release workflow
  .github/scripts/get-digest.sh
  .github/workflows/release-dkr-image.yml
  .github/workflows/release-nightly.yml
Labels: CI

#3030 feat(cli): KICS does not execute scan as default anymore
  .github/workflows/go-ci-integration.yml
  docs/creating-queries.md
  docs/getting-started.md
  e2e/cli_test.go
  internal/console/kics.go
  internal/console/kics_test.go
Labels: enhancement, feature

#3037 fix(log): should not print, if printer is not ready
  internal/console/kics.go
  internal/console/printer/printer.go
  internal/console/printer/printer_test.go
Labels: bug

#3032 feat(engine): enhanced query selection and improved performance
  assets/queries/cloudFormation/dynamodb_with_aws_owned_cmk/query.rego
  assets/queries/cloudFormation/dynamodb_with_aws_owned_cmk/test/negative1.yaml
  assets/queries/cloudFormation/dynamodb_with_aws_owned_cmk/test/negative2.json
  assets/queries/cloudFormation/dynamodb_with_aws_owned_cmk/test/positive1.yaml
  assets/queries/cloudFormation/dynamodb_with_aws_owned_cmk/test/positive2.yaml
  assets/queries/cloudFormation/dynamodb_with_aws_owned_cmk/test/positive3.yaml
  assets/queries/cloudFormation/dynamodb_with_aws_owned_cmk/test/positive4.yaml
  assets/queries/cloudFormation/dynamodb_with_aws_owned_cmk/test/positive5.json
  assets/queries/cloudFormation/dynamodb_with_aws_owned_cmk/test/positive6.json
  assets/queries/cloudFormation/dynamodb_with_aws_owned_cmk/test/positive7.json
  assets/queries/cloudFormation/dynamodb_with_aws_owned_cmk/test/positive8.json
  assets/queries/cloudFormation/iam_policies_with_full_privileges/test/negative1.yaml
  assets/queries/cloudFormation/iam_policies_with_full_privileges/test/negative2.json
  assets/queries/cloudFormation/iam_policy_grants_assumerole_permission_across_all_services/test/negative1.yaml
  assets/queries/cloudFormation/iam_policy_grants_assumerole_permission_across_all_services/test/negative2.json
  assets/queries/cloudFormation/support_has_no_role_associated/test/negative1.yaml
  assets/queries/cloudFormation/support_has_no_role_associated/test/negative2.json
  internal/console/scan.go
  pkg/analyzer/analyzer.go
  pkg/analyzer/analyzer_test.go
  test/fixtures/analyzer_test/Dockerfile
  test/fixtures/analyzer_test/cloudformation.yaml
  test/fixtures/analyzer_test/helm/.helmignore
  test/fixtures/analyzer_test/helm/Chart.yaml
  test/fixtures/analyzer_test/helm/templates/NOTES.txt
  test/fixtures/analyzer_test/helm/templates/_helpers.tpl
  test/fixtures/analyzer_test/helm/templates/service.yaml
  test/fixtures/analyzer_test/helm/values.yaml
  test/fixtures/analyzer_test/k8s.yaml
  test/fixtures/analyzer_test/openAPI.json
  test/fixtures/analyzer_test/openAPI_test/openAPI.yaml
  test/fixtures/analyzer_test/terraform.tf
Labels: enhancement, feature, go

#3043 fix(log): changed terraform vars not found log level
  pkg/parser/terraform/variables.go
Labels: bug

#3038 docs(integrations): Jenkinsfile documentation and examples
  docs/configuration-file.md
  docs/img/jenkins-creating-pipeline.png
  docs/img/jenkins-paste-pipeline.png
  docs/img/jenkins-pipeline-artifacts.png
  docs/img/jenkins-pipeline-success.png
  docs/integrations.md
  docs/integrations_gitlabci.md
  docs/integrations_jenkins.md
  examples/azure-pipelines/azure-pipelines.yaml
  examples/bitbucket/bitbucket-pipelines.yaml
  examples/github/kics-docker-runner-sarif.yaml
  examples/jenkins/agent-docker-html-report-declarative.jenkinsfile
  examples/jenkins/agent-linux-simple-declarative.jenkinsfile
  mkdocs.yml
Labels: documentation

#2994 feat(query): "Property 'allowReserved' Improperly Defined" for OpenAPI (#2993)
  assets/queries/openAPI/property_allow_reserved_improperly_defined/metadata.json
  assets/queries/openAPI/property_allow_reserved_improperly_defined/query.rego
  assets/queries/openAPI/property_allow_reserved_improperly_defined/test/negative1.json
  assets/queries/openAPI/property_allow_reserved_improperly_defined/test/negative2.yaml
  assets/queries/openAPI/property_allow_reserved_improperly_defined/test/negative3.json
  assets/queries/openAPI/property_allow_reserved_improperly_defined/test/negative4.yaml
  assets/queries/openAPI/property_allow_reserved_improperly_defined/test/positive1.json
  assets/queries/openAPI/property_allow_reserved_improperly_defined/test/positive2.yaml
  assets/queries/openAPI/property_allow_reserved_improperly_defined/test/positive3.json
  assets/queries/openAPI/property_allow_reserved_improperly_defined/test/positive4.yaml
  assets/queries/openAPI/property_allow_reserved_improperly_defined/test/positive_expected_result.json
Labels: openapi, query

#2996 feat(query): "Property 'allowEmptyValue' Improperly Defined" for OpenAPI (#2995)
  assets/queries/openAPI/property_allow_empty_value_improperly_defined/metadata.json
  assets/queries/openAPI/property_allow_empty_value_improperly_defined/query.rego
  assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/negative1.json
  assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/negative2.yaml
  assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/negative3.json
  assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/negative4.yaml
  assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/positive1.json
  assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/positive2.yaml
  assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/positive3.json
  assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/positive4.yaml
  assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/positive_expected_result.json
Labels: openapi, query

#3046 docs(jenkins): fixing image url in integration guide
  docs/integrations_jenkins.md
Labels: documentation

#3027 feat(query): "Link Object With Both 'operationId' And 'operationRef'" for OpenAPI (#3026)
  assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/query.rego
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/metadata.json
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/query.rego
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/negative1.json
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/negative2.json
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/negative3.json
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/negative4.yaml
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/negative5.yaml
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/negative6.yaml
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive1.json
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive2.json
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive3.json
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive4.yaml
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive5.yaml
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive6.yaml
  assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive_expected_result.json
Labels: openapi, query

#3014 feat(query): "Path Without Operation" for OpenAPI (#3013)
  assets/queries/openAPI/path_without_operation/metadata.json
  assets/queries/openAPI/path_without_operation/query.rego
  assets/queries/openAPI/path_without_operation/test/negative1.json
  assets/queries/openAPI/path_without_operation/test/negative2.yaml
  assets/queries/openAPI/path_without_operation/test/positive1.json
  assets/queries/openAPI/path_without_operation/test/positive2.yaml
  assets/queries/openAPI/path_without_operation/test/positive_expected_result.json
Labels: openapi, query

#3010 feat(query): "Header Response Named as 'Content-Type'" for OpenAPI (#3009)
  assets/queries/openAPI/header_response_named_as_content_type/metadata.json
  assets/queries/openAPI/header_response_named_as_content_type/query.rego
  assets/queries/openAPI/header_response_named_as_content_type/test/negative1.json
  assets/queries/openAPI/header_response_named_as_content_type/test/negative2.yaml
  assets/queries/openAPI/header_response_named_as_content_type/test/positive1.json
  assets/queries/openAPI/header_response_named_as_content_type/test/positive2.yaml
  assets/queries/openAPI/header_response_named_as_content_type/test/positive_expected_result.json
Labels: openapi, query
