Repository Checkmarx/kics, pull requests merged in 2021-11, with the labels that each got.

#4448 fix(race): fix kics Go data races (#4399 )
  .github/workflows/go-test-race.yml
  internal/console/helpers/helpers.go
  internal/storage/memory.go
  internal/tracker/ci.go
  pkg/engine/inspector_test.go
  pkg/progress/circle/circle_progress.go
  pkg/progress/circle/circle_progress_test.go
  pkg/scan/scan.go
Labels: bug, go

#4435 fix(query): fixed 59cb3da7-f206-4ae6-b827-7abf0a9cab9d and 2ade1579-4b2c-4590-bebb-f99bf597f612
  assets/libraries/azureresourcemanager.rego
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_rdp/query.rego
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_rdp/test/negative2.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_rdp/test/negative3.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_rdp/test/negative5.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_rdp/test/negative6.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_rdp/test/positive1.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/query.rego
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/negative1.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/negative2.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/negative3.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/negative4.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/negative5.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/negative6.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/positive1.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/positive2.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/positive3.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/positive4.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/positive5.json
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/positive6.json
Labels: bug, query, arm

#4447 feat(query): updated "Public Storage Account" for Terraform
  assets/queries/terraform/azure/public_storage_account/metadata.json
  assets/queries/terraform/azure/public_storage_account/query.rego
  assets/queries/terraform/azure/public_storage_account/test/negative1.tf
  assets/queries/terraform/azure/public_storage_account/test/negative2.tf
  assets/queries/terraform/azure/public_storage_account/test/negative3.tf
  assets/queries/terraform/azure/public_storage_account/test/positive1.tf
  assets/queries/terraform/azure/public_storage_account/test/positive2.tf
  assets/queries/terraform/azure/public_storage_account/test/positive_expected_result.json
Labels: query, terraform, azure

#4437 feat(e2e): added custom JSON Schema Validation for BoM Results
  .github/workflows/go-e2e.yaml
  e2e/cli_test.go
  e2e/fixtures/schemas/result.json
  e2e/fixtures/schemas/resultBoM.json
  e2e/testcases/e2e-cli-050_scan_bill-of-materials.go
Labels: tests

#4457 fix(cli): report-formats panics with uppercase input closes #4455
  internal/console/helpers/helpers.go
  internal/console/scan.go
Labels: go

#4462 refactor(go-test-race): increase timeout to 1 hour
  .github/workflows/go-test-race.yml
Labels: CI

#4465 fix(source): fixed KICS panic when reading invalid metadata (#4413)
  pkg/engine/source/filesystem.go
  pkg/engine/source/filesystem_test.go
Labels: bug

#4461 fix: increase client timeout to 20s
  pkg/descriptions/client.go
Labels: go

#4456 fix(bom): appropriate resource categories
  assets/queries/terraform/aws_bom/elasticache/query.rego
  assets/queries/terraform/aws_bom/msk/query.rego
  assets/queries/terraform/aws_bom/sns/query.rego
Labels: query

#4444 feat(passwords and secrets mechanism): a88baa34-e2ad-44ea-ad6f-8cac87bc7c71 trigger all the rules defined inside the regex_rules.json
  docs/secrets.md
  pkg/engine/secrets/inspector.go
  pkg/engine/secrets/inspector_test.go
  pkg/scan/scan.go
  pkg/scanner/scanner_test.go
  test/secrets_test.go
Labels: go

#4449 feat(query): added "Function App FTPS Enforce Disabled" for Terraform
  assets/queries/terraform/azure/function_app_ftps_enforce_disabled/metadata.json
  assets/queries/terraform/azure/function_app_ftps_enforce_disabled/query.rego
  assets/queries/terraform/azure/function_app_ftps_enforce_disabled/test/negative1.tf
  assets/queries/terraform/azure/function_app_ftps_enforce_disabled/test/negative2.tf
  assets/queries/terraform/azure/function_app_ftps_enforce_disabled/test/positive1.tf
  assets/queries/terraform/azure/function_app_ftps_enforce_disabled/test/positive2.tf
  assets/queries/terraform/azure/function_app_ftps_enforce_disabled/test/positive_expected_result.json
Labels: query, terraform, azure

#4450 feat(query): added "App Service Not Using Latest TLS Encryption Version" for Terraform
  assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/metadata.json
  assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/query.rego
  assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/test/negative1.tf
  assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/test/negative2.tf
  assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/test/positive1.tf
  assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/test/positive2.tf
  assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/test/positive_expected_result.json
Labels: query, terraform, azure

#4464 fix(detector): fix panic with interpolated brackets in detector (#4415)
  pkg/detector/helper.go
  pkg/detector/helper_test.go
Labels: bug, go

#4452 feat(query): added "Function App Managed Identity Disabled" for Terraform
  assets/queries/terraform/azure/function_app_managed_identity_disabled/metadata.json
  assets/queries/terraform/azure/function_app_managed_identity_disabled/query.rego
  assets/queries/terraform/azure/function_app_managed_identity_disabled/test/negative.tf
  assets/queries/terraform/azure/function_app_managed_identity_disabled/test/positive1.tf
  assets/queries/terraform/azure/function_app_managed_identity_disabled/test/positive_expected_result.json
Labels: query, terraform, azure

#4451 feat(query): added "App Service FTPS Enforce Disabled" for Terraform
  assets/queries/terraform/azure/app_service_ftps_enforce_disabled/metadata.json
  assets/queries/terraform/azure/app_service_ftps_enforce_disabled/query.rego
  assets/queries/terraform/azure/app_service_ftps_enforce_disabled/test/negative1.tf
  assets/queries/terraform/azure/app_service_ftps_enforce_disabled/test/negative2.tf
  assets/queries/terraform/azure/app_service_ftps_enforce_disabled/test/positive1.tf
  assets/queries/terraform/azure/app_service_ftps_enforce_disabled/test/positive_expected_result.json
Labels: query, terraform, azure

#4480 feat(terraform): Added Ignore lines by comments to terraform
  pkg/engine/inspector.go
  pkg/engine/inspector_test.go
  pkg/engine/source/filesystem_test.go
  pkg/kics/sink.go
  pkg/model/model.go
  pkg/parser/docker/parser.go
  pkg/parser/docker/parser_test.go
  pkg/parser/json/parser.go
  pkg/parser/json/parser_test.go
  pkg/parser/parser.go
  pkg/parser/terraform/comment/comment.go
  pkg/parser/terraform/comment/comment_test.go
  pkg/parser/terraform/terraform.go
  pkg/parser/terraform/terraform_test.go
  pkg/parser/yaml/parser.go
  pkg/parser/yaml/parser_test.go
  test/fixtures/all_auth_users_get_read_access/metadata.json
  test/fixtures/type-test01/template01/metadata.json
Labels: feature, terraform, go

#4471 feat(query): added "MSSQL Server Public Network Access Enabled" for Terraform
  assets/queries/terraform/azure/mssql_server_public_network_access_disabled/metadata.json
  assets/queries/terraform/azure/mssql_server_public_network_access_disabled/query.rego
  assets/queries/terraform/azure/mssql_server_public_network_access_disabled/test/negative1.tf
  assets/queries/terraform/azure/mssql_server_public_network_access_disabled/test/positive1.tf
  assets/queries/terraform/azure/mssql_server_public_network_access_disabled/test/positive2.tf
  assets/queries/terraform/azure/mssql_server_public_network_access_disabled/test/positive_expected_result.json
  assets/queries/terraform/azure/mysql_server_public_access_enabled/metadata.json
Labels: query, terraform, azure

#4473 feat(query): added "Function App HTTP2 Disabled" for Terraform
  assets/queries/terraform/azure/function_app_http2_disabled/metadata.json
  assets/queries/terraform/azure/function_app_http2_disabled/query.rego
  assets/queries/terraform/azure/function_app_http2_disabled/test/negative.tf
  assets/queries/terraform/azure/function_app_http2_disabled/test/positive1.tf
  assets/queries/terraform/azure/function_app_http2_disabled/test/positive2.tf
  assets/queries/terraform/azure/function_app_http2_disabled/test/positive3.tf
  assets/queries/terraform/azure/function_app_http2_disabled/test/positive_expected_result.json
Labels: query, terraform, azure

#4474 feat(query): added "App Service HTTP2 Disabled" for Terraform
  assets/queries/terraform/azure/app_service_http2_disabled/metadata.json
  assets/queries/terraform/azure/app_service_http2_disabled/query.rego
  assets/queries/terraform/azure/app_service_http2_disabled/test/negative.tf
  assets/queries/terraform/azure/app_service_http2_disabled/test/positive1.tf
  assets/queries/terraform/azure/app_service_http2_disabled/test/positive2.tf
  assets/queries/terraform/azure/app_service_http2_disabled/test/positive3.tf
  assets/queries/terraform/azure/app_service_http2_disabled/test/positive_expected_result.json
Labels: query, terraform, azure

#4483 fix(report): fixed bug with invalid startLine on sarif report
  pkg/report/model/sarif.go
  pkg/report/model/sarif_test.go
Labels: bug, go

#4409 feat(engine): Added data source policy to terraform
  assets/libraries/terraform.rego
  assets/queries/terraform/aws/cloudwatch_logs_destination_with_vulnerable_policy/query.rego
  assets/queries/terraform/aws/glue_with_vulnerable_policy/query.rego
  pkg/parser/terraform/converter/default.go
  pkg/parser/terraform/converter/default_test.go
  pkg/parser/terraform/data_source.go
  pkg/parser/terraform/data_source_test.go
  pkg/parser/terraform/terraform.go
  pkg/parser/terraform/terraform_test.go
  pkg/parser/terraform/variables.go
  pkg/parser/terraform/variables_test.go
  test/fixtures/test_terraform_data_source/data_source_1.tf
  test/fixtures/test_terraform_data_source/data_source_2.tf
Labels: feature, go

#4488 Add MegaLinter in the list of integrations
  docs/integrations.md
Labels: documentation, integrations

#4486 feat(yaml): Added Ignore lines by comments to yaml #4420
  pkg/model/comment_yaml.go
  pkg/model/comment_yaml_test.go
  pkg/model/model_yaml.go
Labels: feature, go

#4466 refactor(query): Updated query Chown Flag Exists description (#3768)
  assets/queries/dockerfile/chown_flag_exists/metadata.json
Labels: enhancement, query, docker

#4491 feat(parser): Enabled parsers ignore comment by line
  docs/running-kics.md
  pkg/kics/resolver_sink.go
  pkg/model/comment_yaml.go
  pkg/model/comment_yaml_test.go
  pkg/model/comments.go
  pkg/model/comments_test.go
  pkg/model/model.go
  pkg/parser/docker/comments.go
  pkg/parser/docker/comments_test.go
  pkg/parser/docker/parser.go
  pkg/parser/docker/parser_test.go
  pkg/parser/terraform/comment/comment.go
  pkg/parser/terraform/comment/comment_test.go
  pkg/parser/terraform/terraform.go
  pkg/parser/terraform/terraform_test.go
  pkg/parser/yaml/parser.go
  pkg/parser/yaml/parser_test.go
Labels: feature, go

#4478 feat(passwords and secrets): validation of query ids in custom secrets regexes
  pkg/engine/secrets/inspector.go
Labels: go

#4446 feat(query): added "Function App Client Certificates Unrequired" for Terraform
  assets/queries/terraform/azure/function_app_client_certificates_unrequired/metadata.json
  assets/queries/terraform/azure/function_app_client_certificates_unrequired/query.rego
  assets/queries/terraform/azure/function_app_client_certificates_unrequired/test/negative.tf
  assets/queries/terraform/azure/function_app_client_certificates_unrequired/test/positive1.tf
  assets/queries/terraform/azure/function_app_client_certificates_unrequired/test/positive2.tf
  assets/queries/terraform/azure/function_app_client_certificates_unrequired/test/positive_expected_result.json
Labels: query, terraform, azure

#4445 feat(query): added "Function App Authentication Disabled" for Terraform
  assets/queries/terraform/azure/function_app_authentication_disabled/metadata.json
  assets/queries/terraform/azure/function_app_authentication_disabled/query.rego
  assets/queries/terraform/azure/function_app_authentication_disabled/test/negative.tf
  assets/queries/terraform/azure/function_app_authentication_disabled/test/positive1.tf
  assets/queries/terraform/azure/function_app_authentication_disabled/test/positive2.tf
  assets/queries/terraform/azure/function_app_authentication_disabled/test/positive_expected_result.json
  assets/queries/terraform/azure/unrestricted_sql_server_access/metadata.json
  assets/queries/terraform/azure/unrestricted_sql_server_access/query.rego
  assets/queries/terraform/azure/unrestricted_sql_server_access/test/negative.tf
  assets/queries/terraform/azure/unrestricted_sql_server_access/test/positive.tf
  assets/queries/terraform/azure/unrestricted_sql_server_access/test/positive_expected_result.json
Labels: query, terraform, azure

#4470 feat(query): added "App Service Managed Identity Disabled" for Terraform
  assets/queries/terraform/azure/app_service_managed_identity_disabled/metadata.json
  assets/queries/terraform/azure/app_service_managed_identity_disabled/query.rego
  assets/queries/terraform/azure/app_service_managed_identity_disabled/test/negative1.tf
  assets/queries/terraform/azure/app_service_managed_identity_disabled/test/positive1.tf
  assets/queries/terraform/azure/app_service_managed_identity_disabled/test/positive_expected_result.json
Labels: query, terraform, azure

#4472 feat(query): added "Function App Not Using Latest TLS Encryption Version" for Terraform
  assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/query.rego
  assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/test/negative3.tf
  assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/test/positive_expected_result.json
  assets/queries/terraform/azure/function_app_not_using_latest_tls_encryption_version/metadata.json
  assets/queries/terraform/azure/function_app_not_using_latest_tls_encryption_version/query.rego
  assets/queries/terraform/azure/function_app_not_using_latest_tls_encryption_version/test/negative1.tf
  assets/queries/terraform/azure/function_app_not_using_latest_tls_encryption_version/test/negative2.tf
  assets/queries/terraform/azure/function_app_not_using_latest_tls_encryption_version/test/negative3.tf
  assets/queries/terraform/azure/function_app_not_using_latest_tls_encryption_version/test/positive1.tf
  assets/queries/terraform/azure/function_app_not_using_latest_tls_encryption_version/test/positive_expected_result.json
Labels: query, terraform, azure

#4492 tests(source): increased unit tests coverago to 80%
  pkg/engine/source/filesystem_test.go
Labels: tests

#4495 fix(docs): removed duplicate lines from docs
  docs/certifications-cis.md
Labels: documentation

#4497 fix(engine): Fixed comments commands on windows
  docs/running-kics.md
  pkg/model/comment_yaml.go
  pkg/parser/terraform/comment/comment.go
Labels: bug, go

#4500 Add blank line so mkdocs displays correctly the bulletpoints
  docs/integrations.md
Labels: community

#4487 feat(e2e): CIS Description server mock - E2E & CI
  .github/scripts/server-mock/.gitignore
  .github/scripts/server-mock/package-lock.json
  .github/scripts/server-mock/package.json
  .github/scripts/server-mock/src/descriptions.json
  .github/scripts/server-mock/src/index.js
  .github/workflows/go-e2e.yaml
  e2e/cli_test.go
  e2e/fixtures/schemas/result.json
  e2e/fixtures/schemas/resultCIS.json
  e2e/testcases/e2e-cli-052_scan_with_custom_cis_descriptions.go
  e2e/testcases/general.go
  e2e/utils/helper.go
Labels: tests

#4502 fix(query) Wrong detection of unused security group
  assets/queries/terraform/aws/security_groups_not_used/query.rego
  assets/queries/terraform/aws/security_groups_not_used/test/negative3.tf
  assets/queries/terraform/aws/security_groups_not_used/test/positive2.tf
  assets/queries/terraform/aws/security_groups_not_used/test/positive3.tf
  assets/queries/terraform/aws/security_groups_not_used/test/positive_expected_result.json
Labels: community

#4503 feat(docs & passwords and secrets): consideration of kics-scan ignore command and LinesIgnore
  docs/platforms.md
  pkg/engine/secrets/inspector.go
  pkg/engine/secrets/inspector_test.go
  pkg/scan/path_utils.go
  pkg/scan/post_scan.go
  pkg/scan/scan.go
Labels: documentation, go

#4529 update(docs): update to Checkmarx new logos
  README.md
  docs/about.md
  docs/img/logo-cx-horizontal_new.jpg
  docs/img/logo/kics_hat_color_new.png
  docs/img/logo/kics_hat_white_new.png
  mkdocs.yml
Labels: documentation

#4534 refactor(core): Changed tests to use a constants platforms
  e2e/utils/html.go
  internal/constants/constants.go
  test/queries_content_test.go
Labels: go

#4541 bump(containrd): bump containrd to version 1.5.8
  go.mod
  go.sum
Labels: dependencies

#4537 fix(password and secrets): fixed MS Teams regex hardcoded team_name (#4528)
  assets/queries/common/passwords_and_secrets/regex_rules.json
Labels: bug

#4518 feat(e2e): E2E Tests for kics comments commands
  e2e/fixtures/samples/scan-ignore/disable.tf
  e2e/fixtures/samples/scan-ignore/enable.tf
  e2e/fixtures/samples/scan-ignore/ignore-block.dockerfile
  e2e/fixtures/samples/scan-ignore/ignore-lines.yaml
  e2e/fixtures/samples/scan-ignore/ignore/sample.dockerfile
  e2e/fixtures/samples/scan-ignore/ignore/sample.tf
  e2e/fixtures/samples/scan-ignore/ignore/sample.yaml
  e2e/testcases/e2e-cli-053_kics_scan_ignore.go
Labels: tests

#4550 bump(deps): bump vulnerable dependencies
  go.mod
  go.sum
Labels: dependencies

#4517 feat(query): added "User with IAM Role" for Terraform
  assets/libraries/terraform.rego
  assets/queries/terraform/gcp/user_with_iam_role/metadata.json
  assets/queries/terraform/gcp/user_with_iam_role/query.rego
  assets/queries/terraform/gcp/user_with_iam_role/test/negative.tf
  assets/queries/terraform/gcp/user_with_iam_role/test/positive1.tf
  assets/queries/terraform/gcp/user_with_iam_role/test/positive2.tf
  assets/queries/terraform/gcp/user_with_iam_role/test/positive_expected_result.json
Labels: terraform

#4536 fix(parser): fixed YAML parser panic with wrong type for interface (#4521)
  pkg/parser/yaml/parser.go
Labels: bug

#4549 docs(terraform): Added docs for terraform modules feature
  docs/platforms.md
Labels: documentation

#4542 refactor(query): policies for Ansible
  assets/queries/ansible/aws/ecr_repository_is_publicly_accessible/query.rego
  assets/queries/ansible/aws/iam_policies_with_full_privileges/query.rego
  assets/queries/ansible/aws/iam_policies_with_full_privileges/test/positive_expected_result.json
  assets/queries/ansible/aws/iam_policy_grants_assumerole_permission_across_all_services/query.rego
  assets/queries/ansible/aws/iam_policy_grants_assumerole_permission_across_all_services/test/positive.yaml
  assets/queries/ansible/aws/iam_policy_grants_assumerole_permission_across_all_services/test/positive_expected_result.json
  assets/queries/ansible/aws/iam_policy_grants_full_permissions/query.rego
  assets/queries/ansible/aws/iam_policy_grants_full_permissions/test/positive_expected_result.json
  assets/queries/ansible/aws/iam_role_allows_all_principals_to_assume/query.rego
  assets/queries/ansible/aws/iam_role_allows_all_principals_to_assume/test/positive.yaml
  assets/queries/ansible/aws/iam_role_allows_all_principals_to_assume/test/positive_expected_result.json
  assets/queries/ansible/aws/kms_key_with_vulnerable_policy/query.rego
  assets/queries/ansible/aws/s3_bucket_access_to_any_principal/query.rego
  assets/queries/ansible/aws/s3_bucket_access_to_any_principal/test/positive_expected_result.json
  assets/queries/ansible/aws/s3_bucket_allows_delete_action_from_all_principals/query.rego
  assets/queries/ansible/aws/s3_bucket_allows_delete_action_from_all_principals/test/positive_expected_result.json
  assets/queries/ansible/aws/s3_bucket_allows_get_action_from_all_principals/query.rego
  assets/queries/ansible/aws/s3_bucket_allows_get_action_from_all_principals/test/positive_expected_result.json
  assets/queries/ansible/aws/s3_bucket_allows_list_action_from_all_principals/query.rego
  assets/queries/ansible/aws/s3_bucket_allows_list_action_from_all_principals/test/positive_expected_result.json
  assets/queries/ansible/aws/s3_bucket_allows_put_action_from_all_principals/query.rego
  assets/queries/ansible/aws/s3_bucket_allows_put_action_from_all_principals/test/positive_expected_result.json
  assets/queries/ansible/aws/s3_bucket_allows_writeacp_action_from_all_principals/query.rego
  assets/queries/ansible/aws/s3_bucket_allows_writeacp_action_from_all_principals/test/positive_expected_result.json
  assets/queries/ansible/aws/s3_bucket_with_all_permissions/query.rego
  assets/queries/ansible/aws/sqs_policy_allows_all_actions/query.rego
  assets/queries/ansible/aws/sqs_policy_allows_all_actions/test/positive_expected_result.json
  assets/queries/ansible/aws/sqs_policy_with_public_access/query.rego
  assets/queries/ansible/aws/sqs_policy_with_public_access/test/positive_expected_result.json
  assets/queries/ansible/aws/sqs_queue_exposed/query.rego
  assets/queries/ansible/aws/sqs_queue_exposed/test/positive_expected_result.json
Labels: query, ansible, aws

#4515 feat(query): added "GKE Using Default Service Account" for Ansible and Terraform
  assets/queries/ansible/gcp/gke_using_default_service_account/metadata.json
  assets/queries/ansible/gcp/gke_using_default_service_account/query.rego
  assets/queries/ansible/gcp/gke_using_default_service_account/test/negative1.yaml
  assets/queries/ansible/gcp/gke_using_default_service_account/test/positive1.yaml
  assets/queries/ansible/gcp/gke_using_default_service_account/test/positive2.yaml
  assets/queries/ansible/gcp/gke_using_default_service_account/test/positive_expected_result.json
  assets/queries/terraform/gcp/gke_using_default_service_account/metadata.json
  assets/queries/terraform/gcp/gke_using_default_service_account/query.rego
  assets/queries/terraform/gcp/gke_using_default_service_account/test/negative.tf
  assets/queries/terraform/gcp/gke_using_default_service_account/test/positive1.tf
  assets/queries/terraform/gcp/gke_using_default_service_account/test/positive2.tf
  assets/queries/terraform/gcp/gke_using_default_service_account/test/positive_expected_result.json
Labels: terraform, ansible

#4551 fix(scan): not reporting error when progress bar fails to close
  pkg/scan/scan.go
Labels: go

#4535 refactor(query): policies for Terraform
  assets/queries/terraform/aws/authentication_without_mfa/query.rego
  assets/queries/terraform/aws/cloudwatch_logs_destination_with_vulnerable_policy/query.rego
  assets/queries/terraform/aws/ecr_repository_is_publicly_accessible/query.rego
  assets/queries/terraform/aws/efs_with_vulnerable_policy/query.rego
  assets/queries/terraform/aws/elasticsearch_domain_with_vulnerable_policy/query.rego
  assets/queries/terraform/aws/glue_with_vulnerable_policy/query.rego
  assets/queries/terraform/aws/iam_policies_with_full_privileges/query.rego
  assets/queries/terraform/aws/iam_policy_grants_assumerole_permission_across_all_services/query.rego
  assets/queries/terraform/aws/iam_policy_grants_full_permissions/query.rego
  assets/queries/terraform/aws/iam_policy_grants_full_permissions/test/positive_expected_result.json
  assets/queries/terraform/aws/iam_role_allows_all_principals_to_assume/query.rego
  assets/queries/terraform/aws/iam_role_policy_passrole_allows_all/query.rego
  assets/queries/terraform/aws/iam_role_policy_passrole_allows_all/test/positive_expected_result.json
  assets/queries/terraform/aws/iam_role_with_full_privileges/query.rego
  assets/queries/terraform/aws/iam_user_policy_without_mfa/query.rego
  assets/queries/terraform/aws/kms_key_with_vulnerable_policy/query.rego
  assets/queries/terraform/aws/policy_without_principal/query.rego
  assets/queries/terraform/aws/policy_without_principal/test/positive_expected_result.json
  assets/queries/terraform/aws/rest_api_with_vulnerable_policy/query.rego
  assets/queries/terraform/aws/s3_bucket_access_to_any_principal/query.rego
  assets/queries/terraform/aws/s3_bucket_allows_all_actions_from_all_principals/query.rego
  assets/queries/terraform/aws/s3_bucket_allows_delete_action_from_all_principals/query.rego
  assets/queries/terraform/aws/s3_bucket_allows_get_action_from_all_principals/query.rego
  assets/queries/terraform/aws/s3_bucket_allows_list_action_from_all_principals/query.rego
  assets/queries/terraform/aws/s3_bucket_allows_put_action_from_all_principals/query.rego
  assets/queries/terraform/aws/s3_bucket_allows_writeacp_action_from_all_principals/query.rego
  assets/queries/terraform/aws/s3_bucket_allows_writeacp_action_from_all_principals/test/positive_expected_result.json
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/query.rego
  assets/queries/terraform/aws/s3_bucket_with_all_permissions/query.rego
  assets/queries/terraform/aws/secrets_manager_with_vulnerable_policy/query.rego
  assets/queries/terraform/aws/service_control_policies_disabled/query.rego
  assets/queries/terraform/aws/sns_topic_is_publicly_accessible_for_subscription/query.rego
  assets/queries/terraform/aws/sns_topic_publicity_has_allow_and_not_action_simultaneously/query.rego
  assets/queries/terraform/aws/sns_topic_publicity_has_allow_and_not_action_simultaneously/test/positive_expected_result.json
  assets/queries/terraform/aws/sqs_policy_allows_all_actions/query.rego
  assets/queries/terraform/aws/sqs_policy_allows_all_actions/test/positive_expected_result.json
  assets/queries/terraform/aws/sqs_policy_with_public_access/query.rego
  assets/queries/terraform/aws/sqs_queue_exposed/query.rego
Labels: query, terraform, aws

#4552 feat(report): Added expected value to PDF report
  pkg/report/pdf.go
Labels: feature, go

#4554 docs(logo): changed kics logo in README.md to colored logo
  README.md
Labels: documentation

#4555 feat(docs): Added pre-commit hooks
  docs/integrations.md
  mkdocs.yml
Labels: documentation

#4475 Create certifications.md
  docs/certifications.md
  mkdocs.yml
Labels: documentation

#4531 feat(query): Updated condition from 'Action' to 'Principal', remove unnecessar…
  assets/queries/terraform/aws/sqs_policy_with_public_access/query.rego
Labels: community

#4564 feat(ci): add workflow to upload github-actions image to dockerhub
  .github/workflows/release-docker-github-actions.yaml
Labels: CI

#4573 fix(query): fixed query Multiple RUN, ADD, COPY, Instructions Listed (#4567)
  assets/queries/dockerfile/multiple_run_add_copy_instructions_listed/query.rego
  assets/queries/dockerfile/multiple_run_add_copy_instructions_listed/test/negative4.dockerfile
Labels: query, docker, accuracy
