Repository Checkmarx/kics, pull requests merged in 2021-10, with the labels that each got.

#4325 ci(deps): bump golang to version 1.17 in pipelines
  .github/workflows/go-ci-coverage.yaml
  .github/workflows/go-ci.yml
  .github/workflows/go-e2e.yaml
  .github/workflows/release-apispec.yml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
Labels: CI, dependencies

#4328 fix(parser): fixed json parser with incorrect kics_line #4327
  pkg/parser/json/json_line.go
Labels: bug, go

#4332 build(deps): bump opa to version 0.33.0
  assets/libraries/common.rego
  assets/queries/ansible/aws/stack_without_template/query.rego
  assets/queries/cloudFormation/ec2_instance_has_no_iam_role/query.rego
  assets/queries/cloudFormation/ec2_instance_has_no_iam_role/test/positive2.json
  assets/queries/cloudFormation/ec2_instance_has_no_iam_role/test/positive_expected_result.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/metadata.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/query.rego
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative1.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative2.yaml
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative3.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative4.yaml
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative5.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative6.yaml
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive1.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive2.yaml
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive3.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive4.yaml
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive5.json
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive6.yaml
  assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive_expected_result.json
  go.mod
  go.sum
  test/queries_test.go
Labels: dependencies
