Repository Checkmarx/kics, pull requests merged in 2022-07, with the labels that each got.

#5542 feat(rego): add query to check iam policy to invoke lambda
  assets/queries/terraform/aws/lambda_iam_invokefunction_misconfigured/metadata.json
  assets/queries/terraform/aws/lambda_iam_invokefunction_misconfigured/query.rego
  assets/queries/terraform/aws/lambda_iam_invokefunction_misconfigured/test/negative1.tf
  assets/queries/terraform/aws/lambda_iam_invokefunction_misconfigured/test/negative2.tf
  assets/queries/terraform/aws/lambda_iam_invokefunction_misconfigured/test/positive1.tf
  assets/queries/terraform/aws/lambda_iam_invokefunction_misconfigured/test/positive2.tf
  assets/queries/terraform/aws/lambda_iam_invokefunction_misconfigured/test/positive3.tf
  assets/queries/terraform/aws/lambda_iam_invokefunction_misconfigured/test/positive4.tf
  assets/queries/terraform/aws/lambda_iam_invokefunction_misconfigured/test/positive5.tf
  assets/queries/terraform/aws/lambda_iam_invokefunction_misconfigured/test/positive6.tf
  assets/queries/terraform/aws/lambda_iam_invokefunction_misconfigured/test/positive_expected_result.json
Labels: community

#5574 fix(keyExpectedValue): convert to a recommendation rather than a current status
  assets/queries/ansible/aws/ec2_instance_has_public_ip/query.rego
  assets/queries/ansible/aws/redshift_publicly_accessible/query.rego
  assets/queries/ansible/aws/stack_retention_disabled/query.rego
  assets/queries/ansible/azure/redis_cache_allows_non_ssl_connections/query.rego
  assets/queries/ansible/gcp/gke_legacy_authorization_enabled/query.rego
  assets/queries/ansible/gcp/ip_forwarding_enabled/query.rego
  assets/queries/ansible/gcp/network_policy_disabled/query.rego
  assets/queries/cloudFormation/aws/batch_job_definition_with_privileged_container_properties/query.rego
  assets/queries/cloudFormation/aws/mq_broker_is_publicly_accessible/query.rego
  assets/queries/cloudFormation/aws/redshift_publicly_accessible/query.rego
  assets/queries/k8s/privilege_escalation_allowed/query.rego
  assets/queries/k8s/psp_allows_privilege_escalation/query.rego
  assets/queries/k8s/psp_allows_sharing_host_ipc/query.rego
  assets/queries/k8s/psp_allows_sharing_host_pid/query.rego
  assets/queries/k8s/psp_containers_share_host_network_namespace/query.rego
  assets/queries/k8s/psp_set_to_privileged/query.rego
  assets/queries/k8s/service_account_token_automount_not_disabled/query.rego
  assets/queries/k8s/shared_host_ipc_namespace/query.rego
  assets/queries/k8s/shared_host_network_namespace/query.rego
  assets/queries/k8s/shared_host_pid_namespace/query.rego
  assets/queries/terraform/aws/ec2_instance_has_public_ip/query.rego
  assets/queries/terraform/aws/redshift_not_encrypted/query.rego
  assets/queries/terraform/aws/redshift_publicly_accessible/query.rego
  assets/queries/terraform/azure/dashboard_is_enabled/query.rego
  assets/queries/terraform/azure/redis_cache_allows_non_ssl_connections/query.rego
  assets/queries/terraform/gcp/gke_legacy_authorization_enabled/query.rego
  assets/queries/terraform/gcp/google_project_auto_create_network_disabled/query.rego
  assets/queries/terraform/gcp/ip_forwarding_enabled/query.rego
  assets/queries/terraform/gcp/network_policy_disabled/query.rego
  assets/queries/terraform/gcp/vm_serial_ports_are_enabled_for_vm_instances/query.rego
  assets/queries/terraform/github/github_organization_webhook_with_ssl_disabled/query.rego
  assets/queries/terraform/kubernetes/psp_allows_containers_to_share_the_host_network_namespace/query.rego
  test/fixtures/tc-sim01/query.rego
  test/fixtures/tc-sim03/query.rego
Labels: community

#5576 fix(keyExpectedValue): convert to a recommendation rather than a current status
  assets/queries/ansible/aws/cmk_is_unusable/query.rego
  assets/queries/ansible/aws/kms_key_with_vulnerable_policy/query.rego
  assets/queries/ansible/gcp/serial_ports_enabled_for_vm_instances/query.rego
  assets/queries/cloudFormation/aws/cmk_is_unusable/query.rego
  assets/queries/cloudFormation/aws/iam_groups_inline_policies/query.rego
  assets/queries/cloudFormation/aws/iam_policies_attached_to_user/query.rego
  assets/queries/cloudFormation/aws/s3_bucket_sse_disabled/query.rego
  assets/queries/cloudFormation/aws/sqs_queue_policy_allows_not_action/query.rego
  assets/queries/googleDeploymentManager/compute_instance_is_publicly_accessible/query.rego
  assets/queries/k8s/cluster_allows_unsafe_sysctls/query.rego
  assets/queries/k8s/hpa_targeted_deployments_with_configured_replica_count/query.rego
  assets/queries/k8s/secrets_as_environment_variables/query.rego
  assets/queries/openAPI/general/non_array_schema_with_items/query.rego
  assets/queries/terraform/aws/kinesis_sse_not_configured/query.rego
  assets/queries/terraform/aws/mq_broker_is_publicly_accessible/query.rego
  assets/queries/terraform/aws/user_data_shell_script_is_encoded/query.rego
  assets/queries/terraform/aws/vpc_default_security_group_accepts_all_traffic/query.rego
  assets/queries/terraform/azure/network_interfaces_dont_use_public_ip/query.rego
  assets/queries/terraform/gcp/ip_forwarding_enabled/query.rego
  assets/queries/terraform/kubernetes/cluster_allows_unsafe_sysctls/query.rego
  assets/queries/terraform/kubernetes/container_host_ipc_is_true/query.rego
  assets/queries/terraform/kubernetes/container_host_pid_is_true/query.rego
  assets/queries/terraform/kubernetes/container_with_added_capabilities/query.rego
  assets/queries/terraform/kubernetes/psp_allows_sharing_host_ipc/query.rego
  assets/queries/terraform/kubernetes/secrets_as_environment_variables/query.rego
  assets/queries/terraform/kubernetes/shared_host_network_namespace/query.rego
Labels: community

#5589 fix(keyExpectedValue): ansible-aws queries convert to a recommendation rather than a current status
  assets/queries/ansible/aws/api_gateway_endpoint_config_is_not_private/query.rego
  assets/queries/ansible/aws/api_gateway_without_configured_authorizer/query.rego
  assets/queries/ansible/aws/api_gateway_without_ssl_certificate/query.rego
  assets/queries/ansible/aws/auto_scaling_group_with_no_associated_elb/query.rego
  assets/queries/ansible/aws/batch_job_definition_with_privileged_container_properties/query.rego
  assets/queries/ansible/aws/ca_certificate_identifier_is_outdated/query.rego
  assets/queries/ansible/aws/certificate_rsa_key_bytes_lower_than_256/query.rego
  assets/queries/ansible/aws/cloudfront_without_minimum_protocol_tls_1.2/query.rego
  assets/queries/ansible/aws/cloudtrail_log_file_validation_disabled/query.rego
  assets/queries/ansible/aws/cloudtrail_log_files_not_encrypted_with_cmk/query.rego
  assets/queries/ansible/aws/cloudtrail_not_integrated_with_cloudwatch/query.rego
  assets/queries/ansible/aws/cloudtrail_sns_topic_name_undefined/query.rego
  assets/queries/ansible/aws/cloudwatch_without_retention_period_specified/query.rego
  assets/queries/ansible/aws/db_security_group_open_to_large_scope/query.rego
  assets/queries/ansible/aws/db_security_group_with_public_scope/query.rego
  assets/queries/ansible/aws/ecs_service_without_running_tasks/query.rego
  assets/queries/ansible/aws/ecs_task_definition_network_mode_not_recommended/query.rego
  assets/queries/ansible/aws/ecs_task_definition_with_plaintext_password/query.rego
  assets/queries/ansible/aws/iam_password_without_lowercase_letter/query.rego
  assets/queries/ansible/aws/iam_password_without_minimum_length/query.rego
  assets/queries/ansible/aws/iam_password_without_uppercase_letter/query.rego
  assets/queries/ansible/aws/iam_policies_with_full_privileges/query.rego
  assets/queries/ansible/aws/iam_policy_grants_full_permissions/query.rego
  assets/queries/ansible/aws/kinesis_not_encrypted_with_kms/query.rego
  assets/queries/ansible/aws/lambda_functions_without_x-ray_tracing/query.rego
  assets/queries/ansible/aws/lambda_permission_misconfigured/query.rego
  assets/queries/ansible/aws/lambda_permission_principal_is_wildcard/query.rego
  assets/queries/ansible/aws/launch_configuration_is_not_encrypted/query.rego
  assets/queries/ansible/aws/s3_bucket_access_to_any_principal/query.rego
  assets/queries/ansible/aws/s3_bucket_allows_delete_action_from_all_principals/query.rego
  assets/queries/ansible/aws/s3_bucket_allows_get_action_from_all_principals/query.rego
  assets/queries/ansible/aws/s3_bucket_allows_list_action_from_all_principals/query.rego
  assets/queries/ansible/aws/s3_bucket_allows_put_action_from_all_principals/query.rego
  assets/queries/ansible/aws/s3_bucket_allows_writeacp_action_from_all_principals/query.rego
  assets/queries/ansible/aws/s3_bucket_with_all_permissions/query.rego
  assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/query.rego
  assets/queries/ansible/aws/security_group_ingress_not_restricted/query.rego
  assets/queries/ansible/aws/ses_policy_with_allowed_iam_actions/query.rego
  assets/queries/ansible/aws/sns_topic_is_publicly_accessible/query.rego
  assets/queries/ansible/aws/sql_analysis_services_port_2383_is_publicly_accessible/query.rego
  assets/queries/ansible/aws/unknown_port_exposed_to_internet/query.rego
  assets/queries/ansible/aws/viewer_protocol_policy_allows_http/query.rego
  assets/queries/ansible/aws/vulnerable_default_ssl_certificate/query.rego
Labels: community

#5592 fix(keyExpectedValue): AzureResourceManager queries convert to a recommendation rather than a current status
  assets/queries/azureResourceManager/account_admins_not_notified_by_email/query.rego
  assets/queries/azureResourceManager/aks_cluster_network_policy_not_configured/query.rego
  assets/queries/azureResourceManager/aks_cluster_rbac_disabled/query.rego
  assets/queries/azureResourceManager/aks_dashboard_enabled/query.rego
  assets/queries/azureResourceManager/aks_logging_azure_monitoring_disabled/query.rego
  assets/queries/azureResourceManager/aks_with_authorized_ip_ranges_disabled/query.rego
  assets/queries/azureResourceManager/app_service_authentication_not_set/query.rego
  assets/queries/azureResourceManager/azure_instance_using_basic_authentication/query.rego
  assets/queries/azureResourceManager/azure_managed_disk_without_encryption/query.rego
  assets/queries/azureResourceManager/email_notifications_set_off/query.rego
  assets/queries/azureResourceManager/key_vault_not_recoverable/query.rego
  assets/queries/azureResourceManager/log_profile_incorrect_category/query.rego
  assets/queries/azureResourceManager/mysql_server_ssl_enforcement_disabled/query.rego
  assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_rdp/query.rego
  assets/queries/azureResourceManager/phone_number_not_set_security_contacts/query.rego
  assets/queries/azureResourceManager/postgres_sql_database_server_connection_throttling_disabled/query.rego
  assets/queries/azureResourceManager/postgres_sql_server_log_checkpoint_disabled/query.rego
  assets/queries/azureResourceManager/postgres_sql_server_log_connections_disabled/query.rego
  assets/queries/azureResourceManager/postgres_sql_server_ssl_disabled/query.rego
  assets/queries/azureResourceManager/role_definitions_allow_custom_subscription_role_creation/query.rego
  assets/queries/azureResourceManager/secret_without_expiration_date/query.rego
  assets/queries/azureResourceManager/sql_alert_policy_without_emails/query.rego
  assets/queries/azureResourceManager/sql_server_database_with_low_retention_days/query.rego
  assets/queries/azureResourceManager/sql_server_database_without_auditing/query.rego
  assets/queries/azureResourceManager/standard_price_not_selected/query.rego
  assets/queries/azureResourceManager/storage_account_allows_network_default_access/query.rego
  assets/queries/azureResourceManager/storage_account_allows_unsecure_transfer/query.rego
  assets/queries/azureResourceManager/storage_blob_service_container_with_public_access/query.rego
  assets/queries/azureResourceManager/storage_logging_for_read_write_delete_requests_disabled/query.rego
  assets/queries/azureResourceManager/trusted_microsoft_services_not_enabled/query.rego
  assets/queries/azureResourceManager/unrecommended_log_profile_retention_policy/query.rego
  assets/queries/azureResourceManager/unrecommended_network_watcher_flow_log_retention_policy/query.rego
  assets/queries/azureResourceManager/web_app_not_using_tls_last_version/query.rego
  assets/queries/azureResourceManager/website_azure_active_directory_disabled/query.rego
  assets/queries/azureResourceManager/website_not_forcing_https/query.rego
  assets/queries/azureResourceManager/website_with_client_certificate_auth_disabled/query.rego
  assets/queries/azureResourceManager/website_with_http20enabled_disabled/query.rego
Labels: community

#5561 fix(cloud provider flag): support alicloud in the cloud provider flag
  docs/commands.md
  docs/dockerhub.md
  e2e/fixtures/assets/scan_help
  internal/constants/constants.go
  pkg/engine/source/filesystem.go
  pkg/engine/source/filesystem_test.go
Labels: bug, go

#5591 fix(keyExpectedValue): ansible-gcp queries convert to a recommendation rather than a current status
  assets/queries/ansible/gcp/client_certificate_disabled/query.rego
  assets/queries/ansible/gcp/cloud_dns_without_dnnsec/query.rego
  assets/queries/ansible/gcp/cloud_sql_instance_with_contained_database_authentication_on/query.rego
  assets/queries/ansible/gcp/cloud_sql_instance_with_cross_db_ownership_chaining_on/query.rego
  assets/queries/ansible/gcp/cloud_storage_anonymous_or_publicly_accessible/query.rego
  assets/queries/ansible/gcp/cloud_storage_bucket_logging_not_enabled/query.rego
  assets/queries/ansible/gcp/cloud_storage_bucket_versioning_disabled/query.rego
  assets/queries/ansible/gcp/cluster_labels_disabled/query.rego
  assets/queries/ansible/gcp/cluster_master_authentication_disabled/query.rego
  assets/queries/ansible/gcp/disk_encryption_disabled/query.rego
  assets/queries/ansible/gcp/gke_basic_authentication_enabled/query.rego
  assets/queries/ansible/gcp/gke_master_authorized_networks_disabled/query.rego
  assets/queries/ansible/gcp/google_compute_ssl_policy_weak_cipher_in_use/query.rego
  assets/queries/ansible/gcp/google_compute_subnetwork_with_private_google_access_disabled/query.rego
  assets/queries/ansible/gcp/google_container_node_pool_auto_repair_disabled/query.rego
  assets/queries/ansible/gcp/high_google_kms_crypto_key_rotation_period/query.rego
  assets/queries/ansible/gcp/high_kms_rotation_period/query.rego
  assets/queries/ansible/gcp/ip_aliasing_disabled/query.rego
  assets/queries/ansible/gcp/mysql_instance_with_local_infile_on/query.rego
  assets/queries/ansible/gcp/network_policy_disabled/query.rego
  assets/queries/ansible/gcp/node_auto_upgrade_disabled/query.rego
  assets/queries/ansible/gcp/oslogin_is_disabled_for_vm_instance/query.rego
  assets/queries/ansible/gcp/postgresql_log_checkpoints_flag_not_set_to_on/query.rego
  assets/queries/ansible/gcp/postgresql_log_connections_disabled/query.rego
  assets/queries/ansible/gcp/postgresql_logging_of_temporary_files_disabled/query.rego
  assets/queries/ansible/gcp/postgresql_misconfigured_log_messages_flag/query.rego
  assets/queries/ansible/gcp/postgresql_misconfigured_logging_duration_flag/query.rego
  assets/queries/ansible/gcp/private_cluster_disabled/query.rego
  assets/queries/ansible/gcp/project_wide_ssh_keys_are_enabled_in_vm_instances/query.rego
  assets/queries/ansible/gcp/rdp_access_is_not_restricted/query.rego
  assets/queries/ansible/gcp/shielded_vm_disabled/query.rego
  assets/queries/ansible/gcp/sql_db_instance_backup_disabled/query.rego
  assets/queries/ansible/gcp/sql_db_instance_is_publicly_accessible/query.rego
  assets/queries/ansible/gcp/sql_db_instance_with_ssl_disabled/query.rego
  assets/queries/ansible/gcp/ssh_access_is_not_restricted/query.rego
  assets/queries/ansible/gcp/stackdriver_logging_disabled/query.rego
  assets/queries/ansible/gcp/stackdriver_monitoring_disabled/query.rego
  assets/queries/ansible/gcp/using_default_service_account/query.rego
  assets/queries/ansible/gcp/vm_with_full_cloud_access/query.rego
Labels: community

#5593 fix(query): add check for ALB use in Terraform AWS Security Query
  assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/query.rego
  assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/negative3.tf
  assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/negative4.tf
  assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/positive5.tf
  assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/positive6.tf
  assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/positive_expected_result.json
Labels: query, terraform, aws

#5600 feat(kics_ar): add remediation for terraform alicloud security queries
  assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/query.rego
  assets/queries/terraform/alicloud/actiontrail_trail_oss_bucket_is_publicly_accessible/query.rego
  assets/queries/terraform/alicloud/actiontrail_trail_oss_bucket_is_publicly_accessible/test/positive_expected_result.json
  assets/queries/terraform/alicloud/alb_listening_on_http/query.rego
  assets/queries/terraform/alicloud/cs_kubernetes_node_pool_auto_repair_disabled/query.rego
  assets/queries/terraform/alicloud/disk_encryption_disabled/query.rego
  assets/queries/terraform/alicloud/high_kms_key_rotation_period/query.rego
  assets/queries/terraform/alicloud/launch_template_is_not_encrypted/query.rego
  assets/queries/terraform/alicloud/log_retention_is_not_greater_than_90_days/query.rego
  assets/queries/terraform/alicloud/nas_file_system_not_encrypted/query.rego
  assets/queries/terraform/alicloud/nas_file_system_without_kms/query.rego
  assets/queries/terraform/alicloud/oss_bucket_lifecycle_disabled/query.rego
  assets/queries/terraform/alicloud/oss_bucket_logging_disabled/query.rego
  assets/queries/terraform/alicloud/oss_bucket_public_access_enabled/query.rego
  assets/queries/terraform/alicloud/oss_bucket_transfer_acceleration_disabled/query.rego
  assets/queries/terraform/alicloud/oss_bucket_versioning_disabled/query.rego
  assets/queries/terraform/alicloud/ram_account_password_policy_max_login_attempts_unrecommended/query.rego
  assets/queries/terraform/alicloud/ram_account_password_policy_max_password_age_unrecommended/query.rego
  assets/queries/terraform/alicloud/ram_account_password_policy_not_required_numbers/query.rego
  assets/queries/terraform/alicloud/ram_account_password_policy_without_reuse_prevention/query.rego
  assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_lowercase_character/query.rego
  assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_uppercase_character/query.rego
  assets/queries/terraform/alicloud/ram_security_preference_not_enforce_mfa/query.rego
  assets/queries/terraform/alicloud/rds_instance_events_not_logged/query.rego
  assets/queries/terraform/alicloud/rds_instance_log_connections_disabled/query.rego
  assets/queries/terraform/alicloud/rds_instance_log_connections_disabled/test/positive3.tf
  assets/queries/terraform/alicloud/rds_instance_log_connections_disabled/test/positive_expected_result.json
  assets/queries/terraform/alicloud/rds_instance_log_disconenctions_disabled/query.rego
  assets/queries/terraform/alicloud/rds_instance_log_disconenctions_disabled/test/positive3.tf
  assets/queries/terraform/alicloud/rds_instance_log_disconenctions_disabled/test/positive_expected_result.json
  assets/queries/terraform/alicloud/rds_instance_log_duration_disabled/query.rego
  assets/queries/terraform/alicloud/rds_instance_log_duration_disabled/test/positive3.tf
  assets/queries/terraform/alicloud/rds_instance_log_duration_disabled/test/positive_expected_result.json
  assets/queries/terraform/alicloud/rds_instance_retention_not_recommended/query.rego
  assets/queries/terraform/alicloud/rds_instance_ssl_action_disabled/query.rego
  assets/queries/terraform/alicloud/rds_instance_tde_status_disable/query.rego
  assets/queries/terraform/alicloud/ros_stack_retention_disabled/query.rego
Labels: query, terraform, alicloud

#5602 feat(kics_ar): add kics_auto_remediation for terraform gcp securtiy queries
  .github/workflows/go-ci.yml
  assets/queries/terraform/gcp/client_certificate_disabled/query.rego
  assets/queries/terraform/gcp/client_certificate_disabled/test/positive_expected_result.json
  assets/queries/terraform/gcp/cloud_dns_without_dnssec/query.rego
  assets/queries/terraform/gcp/cloud_storage_bucket_versioning_disabled/query.rego
  assets/queries/terraform/gcp/dnssec_using_rsasha1/query.rego
  assets/queries/terraform/gcp/gke_legacy_authorization_enabled/query.rego
  assets/queries/terraform/gcp/google_compute_ssl_policy_weak_cipher_in_use/query.rego
  assets/queries/terraform/gcp/google_compute_subnetwork_with_private_google_access_disabled/query.rego
  assets/queries/terraform/gcp/google_container_node_pool_auto_repair_disabled/query.rego
  assets/queries/terraform/gcp/google_project_auto_create_network_disabled/query.rego
  assets/queries/terraform/gcp/google_storage_bucket_level_access_disabled/query.rego
  assets/queries/terraform/gcp/high_google_kms_crypto_key_rotation_period/query.rego
  assets/queries/terraform/gcp/high_kms_rotation_period/query.rego
  assets/queries/terraform/gcp/ip_forwarding_enabled/query.rego
  assets/queries/terraform/gcp/ip_forwarding_enabled/test/positive_expected_result.json
  assets/queries/terraform/gcp/network_policy_disabled/query.rego
  assets/queries/terraform/gcp/network_policy_disabled/test/positive_expected_result.json
  assets/queries/terraform/gcp/node_auto_upgrade_disabled/query.rego
  assets/queries/terraform/gcp/node_auto_upgrade_disabled/test/positive.tf
  assets/queries/terraform/gcp/os_login_disabled/query.rego
  assets/queries/terraform/gcp/os_login_disabled/test/positive_expected_result.json
  assets/queries/terraform/gcp/os_login_is_disabled_for_vm_instance/query.rego
  assets/queries/terraform/gcp/pod_security_policy_disabled/query.rego
  assets/queries/terraform/gcp/pod_security_policy_disabled/test/positive_expected_result.json
  assets/queries/terraform/gcp/sql_db_instance_backup_disabled/query.rego
  assets/queries/terraform/gcp/sql_db_instance_backup_disabled/test/positive.tf
  assets/queries/terraform/gcp/sql_db_instance_backup_disabled/test/positive_expected_result.json
  assets/queries/terraform/gcp/sql_db_instance_with_ssl_disabled/query.rego
  pkg/remediation/remediation.go
Labels: query, terraform, gcp

#5606 feat(kics_ar): add kics_auto_remediation for terraform kubernetes security queries
  assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/query.rego
  assets/queries/terraform/kubernetes/container_host_ipc_is_true/query.rego
  assets/queries/terraform/kubernetes/container_host_pid_is_true/query.rego
  assets/queries/terraform/kubernetes/container_is_privileged/query.rego
  assets/queries/terraform/kubernetes/container_is_privileged/test/positive_expected_result.json
  assets/queries/terraform/kubernetes/default_service_account_in_use/query.rego
  assets/queries/terraform/kubernetes/net_raw_capabilities_disabled_for_psp/query.rego
  assets/queries/terraform/kubernetes/privilege_escalation_allowed/query.rego
  assets/queries/terraform/kubernetes/privilege_escalation_allowed/test/positive_expected_result.json
  assets/queries/terraform/kubernetes/psp_allows_privilege_escalation/query.rego
  assets/queries/terraform/kubernetes/psp_allows_sharing_host_ipc/query.rego
  assets/queries/terraform/kubernetes/psp_set_to_privileged/query.rego
  assets/queries/terraform/kubernetes/root_container_not_mounted_as_read_only/query.rego
  assets/queries/terraform/kubernetes/root_container_not_mounted_as_read_only/test/positive_expected_result.json
  assets/queries/terraform/kubernetes/service_account_token_automount_not_disabled/query.rego
  assets/queries/terraform/kubernetes/shared_host_network_namespace/query.rego
  assets/queries/terraform/kubernetes/volume_mount_with_os_directory_write_permissions/query.rego
  assets/queries/terraform/kubernetes/volume_mount_with_os_directory_write_permissions/test/positive_expected_result.json
  pkg/remediation/scan.go
Labels: query, kubernetes, terraform

#5639 fix(bom): change AWS BOM resource_accessibility output values
  assets/libraries/cloudformation.rego
  assets/libraries/terraform.rego
  assets/queries/cloudFormation/aws_bom/efs/query.rego
  assets/queries/cloudFormation/aws_bom/s3_bucket/query.rego
  assets/queries/terraform/aws_bom/s3_bucket/query.rego
Labels: aws, BoM

#5504 feat(report): hide secrets in report results
  assets/queries/common/passwords_and_secrets/regex_rules.json
  pkg/engine/secrets/inspector.go
Labels: feature request, go, release/1.6

#5506 feat(scan): consider .gitignore to automatically exclude paths by default
  assets/queries/ansible/aws/aws_password_policy_with_unchangeable_passwords/metadata.json
  assets/queries/ansible/aws/aws_password_policy_with_unchangeable_passwords/query.rego
  assets/queries/ansible/aws/aws_password_policy_with_unchangeable_passwords/test/negative.yaml
  assets/queries/ansible/aws/aws_password_policy_with_unchangeable_passwords/test/positive.yaml
  assets/queries/ansible/aws/aws_password_policy_with_unchangeable_passwords/test/positive_expected_result.json
  docs/commands.md
  docs/dockerhub.md
  e2e/fixtures/assets/scan_help
  go.mod
  go.sum
  internal/console/assets/scan-flags.json
  internal/console/flags/scan_flags.go
  internal/console/scan.go
  pkg/analyzer/analyzer.go
  pkg/analyzer/analyzer_test.go
  pkg/scan/client.go
  pkg/scan/utils.go
  test/fixtures/gitignore/gitignore
  test/fixtures/gitignore/positive.dockerfile
  test/fixtures/gitignore/positive1.yaml
  test/fixtures/gitignore/secrets.tf
Labels: feature request, go, release/1.6

#5648 feat(pulumi): add support to Pulumi yaml parsing
  .github/scripts/metrics/get_metrics.py
  .github/scripts/queries-validator/metadata-schema.json
  README.md
  assets/libraries/pulumi.rego
  docs/commands.md
  docs/dockerhub.md
  docs/img/logo-crossplane.png
  docs/img/logo-knative.png
  docs/img/logo-pulumi.png
  docs/platforms.md
  e2e/fixtures/E2E_CLI_010
  e2e/fixtures/E2E_CLI_013
  e2e/fixtures/assets/scan_help
  e2e/fixtures/schemas/result.json
  e2e/fixtures/schemas/resultBoM.json
  internal/constants/constants.go
  pkg/analyzer/analyzer.go
  pkg/analyzer/analyzer_test.go
  pkg/engine/source/filesystem.go
  pkg/engine/source/filesystem_test.go
  pkg/parser/yaml/parser.go
  pkg/parser/yaml/parser_test.go
  res/demoPulumi.yaml
  test/fixtures/analyzer_test/pulumi.yaml
Labels: go
