Repository Checkmarx/kics, pull requests merged in 2022-05, with the labels that each got.

#5282 Typo fix
  assets/queries/dockerfile/missing_flag_from_dnf_install/query.rego
Labels: community

#5261 feature(report): Code Climate report
  docs/commands.md
  docs/configuration-file.md
  docs/dockerhub.md
  docs/img/kics_gitlab_code_quality_report.png
  docs/integrations_gitlabci.md
  docs/results.md
  e2e/cli_test.go
  e2e/fixtures/assets/scan_help
  e2e/fixtures/schemas/result-codeclimate.json
  e2e/testcases/e2e-cli-031_scan_report-formats.go
  e2e/testcases/e2e-cli-033_scan_output-path_validate_payload.go
  internal/console/helpers/helpers.go
  pkg/report/code_climate.go
  pkg/report/code_climate_test.go
  pkg/report/model/code_climate.go
  pkg/report/model/code_climate_test.go
Labels: feature request, integrations

#5181 update(query): Unpinned Package Version in Apk Add
  assets/queries/dockerfile/unpinned_package_version_in_apk_add/query.rego
  assets/queries/dockerfile/unpinned_package_version_in_apk_add/test/negative2.dockerfile
Labels: query, docker

#5296 update(query): Network ACL With Unrestricted Access To RDP for Terraform AWS
  assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/negative2.tf
Labels: query, terraform, aws

#5266 feat(query): add new k8s rule to detect port-forwarding into containers (RBAC)
  assets/queries/k8s/rbac_roles_with_portforwarding_permissions/metadata.json
  assets/queries/k8s/rbac_roles_with_portforwarding_permissions/query.rego
  assets/queries/k8s/rbac_roles_with_portforwarding_permissions/test/negative.yaml
  assets/queries/k8s/rbac_roles_with_portforwarding_permissions/test/positive.yaml
  assets/queries/k8s/rbac_roles_with_portforwarding_permissions/test/positive_expected_result.json
Labels: community

#5267 feat(query): add new k8s rule to detect account impersonation (RBAC)
  assets/queries/k8s/rbac_roles_with_impersonate_permission/metadata.json
  assets/queries/k8s/rbac_roles_with_impersonate_permission/query.rego
  assets/queries/k8s/rbac_roles_with_impersonate_permission/test/negative.yaml
  assets/queries/k8s/rbac_roles_with_impersonate_permission/test/positive.yaml
  assets/queries/k8s/rbac_roles_with_impersonate_permission/test/positive_expected_result.json
Labels: community

#5268 feat(query): add new k8s rule to detect bind or escalate permissions (RBAC)
  assets/queries/k8s/rbac_roles_allow_privilege_escalation/metadata.json
  assets/queries/k8s/rbac_roles_allow_privilege_escalation/query.rego
  assets/queries/k8s/rbac_roles_allow_privilege_escalation/test/negative.yaml
  assets/queries/k8s/rbac_roles_allow_privilege_escalation/test/positive.yaml
  assets/queries/k8s/rbac_roles_allow_privilege_escalation/test/positive_expected_result.json
Labels: community

#5286 feat(query): add new k8s rule to detect exec permissions (RBAC)
  assets/queries/k8s/rbac_roles_with_exec_permission/metadata.json
  assets/queries/k8s/rbac_roles_with_exec_permission/query.rego
  assets/queries/k8s/rbac_roles_with_exec_permission/test/negative.yaml
  assets/queries/k8s/rbac_roles_with_exec_permission/test/positive.yaml
  assets/queries/k8s/rbac_roles_with_exec_permission/test/positive_expected_result.json
Labels: community

#5293 update installation options and notes
  docs/getting-started.md
Labels: community

#5310 update(query): Missing Flag From Dnf Install for Dockerfile
  assets/queries/dockerfile/missing_flag_from_dnf_install/query.rego
  assets/queries/dockerfile/missing_flag_from_dnf_install/test/negative3.dockerfile
Labels: query, docker

#5308 update(docs): Removed results formats list from results section
  docs/results.md
Labels: documentation

#5303 update(query): StatefulSet Without Service Name for Kubernetes
  assets/queries/k8s/statefulset_without_service_name/metadata.json
  assets/queries/k8s/statefulset_without_service_name/query.rego
  assets/queries/k8s/statefulset_without_service_name/test/negative.yaml
  assets/queries/terraform/kubernetes/statefulset_without_service_name/metadata.json
  assets/queries/terraform/kubernetes/statefulset_without_service_name/query.rego
Labels: query, kubernetes

#5314 update(query): Storage Account Not Using Latest TLS Encryption Version for Terraform Azure
  assets/queries/terraform/azure/storage_account_not_using_latest_tls_encryption_version/query.rego
  assets/queries/terraform/azure/storage_account_not_using_latest_tls_encryption_version/test/positive.tf
  assets/queries/terraform/azure/storage_account_not_using_latest_tls_encryption_version/test/positive_expected_result.json
Labels: query, terraform, azure

#5264 fix(query): adjusted severity rating and added searchLine in rbac_wildcard_in_rule k8s rule
  assets/queries/k8s/rbac_wildcard_in_rule/metadata.json
  assets/queries/k8s/rbac_wildcard_in_rule/query.rego
  assets/queries/k8s/rbac_wildcard_in_rule/test/positive_expected_result.json
Labels: community

#5334 fix(password and secrets): improve performance
  .github/scripts/report/e2e-html.go
  internal/console/flags/flags_utils.go
  pkg/descriptions/client.go
  pkg/engine/secrets/inspector.go
  pkg/report/commons.go
  pkg/terraformer/terraformer.go
  test/helpers.go
Labels: go

#5321 fix(cpu): fixed number of cpus available info
  internal/console/helpers/helpers.go
  internal/console/pre_scan.go
Labels: bug

#5322 fix(samples): k8s queries
  README.md
  assets/queries/k8s/bind_address_not_properly_set/test/negative1.yaml
  assets/queries/k8s/bind_address_not_properly_set/test/negative2.yaml
  assets/queries/k8s/bind_address_not_properly_set/test/positive1.yaml
  assets/queries/k8s/bind_address_not_properly_set/test/positive2.yaml
  assets/queries/k8s/bind_address_not_properly_set/test/positive_expected_result.json
  assets/queries/k8s/root_ca_file_not_defined/test/negative1.yaml
  assets/queries/k8s/root_ca_file_not_defined/test/negative2.yaml
  assets/queries/k8s/root_ca_file_not_defined/test/positive1.yaml
  assets/queries/k8s/root_ca_file_not_defined/test/positive_expected_result.json
  assets/queries/k8s/service_account_private_key_file_not_defined/test/negative1.yaml
  assets/queries/k8s/service_account_private_key_file_not_defined/test/negative2.yaml
  assets/queries/k8s/service_account_private_key_file_not_defined/test/positive1.yaml
  assets/queries/k8s/service_account_private_key_file_not_defined/test/positive_expected_result.json
  assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/negative1.yaml
  assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/negative2.yaml
  assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/positive1.yaml
  assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/positive2.yaml
  assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/positive_expected_result.json
  assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/negative1.yaml
  assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/negative2.yaml
  assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/positive1.yaml
  assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/positive2.yaml
  assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/positive_expected_result.json
  docs/getting-started.md
  docs/release_checklist.md
Labels: query, kubernetes

#5348 build(go): bump golang version to 1.18
  .github/workflows/go-ci-coverage.yaml
  .github/workflows/go-ci.yml
  .github/workflows/go-e2e.yaml
  .github/workflows/go-test-race.yml
  .github/workflows/release-apispec.yml
  .github/workflows/release-commits.yaml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
  .github/workflows/statistics.yaml
  Dockerfile.ubi8
  go.mod
  go.sum
  pkg/builder/writer/rego.go
  pkg/builder/writer/rego_test.go
  pkg/detector/helper.go
  pkg/engine/secrets/inspector.go
  pkg/parser/terraform/converter/default.go
  pkg/parser/terraform/variables.go
  pkg/parser/yaml/parser.go
  pkg/progress/circle/circle_progress.go
  pkg/progress/circle/circle_progress_test.go
  pkg/report/model/gitlab_sast.go
Labels: dependencies

#5360 update(query): Client Certificate Authentication Not Setup Properly
  assets/queries/k8s/client_certificate_authentication_not_setup_properly/metadata.json
  assets/queries/k8s/client_certificate_authentication_not_setup_properly/query.rego
  assets/queries/k8s/client_certificate_authentication_not_setup_properly/test/negative6.yaml
  assets/queries/k8s/client_certificate_authentication_not_setup_properly/test/negative7.yaml
  assets/queries/k8s/client_certificate_authentication_not_setup_properly/test/positive_expected_result.json
Labels: query, kubernetes

#5349 fix(query): Changed severity of Memcached Disabled query
  assets/queries/ansible/aws/memcached_disabled/metadata.json
  assets/queries/ansible/aws/memcached_disabled/query.rego
  assets/queries/ansible/aws/memcached_disabled/test/positive_expected_result.json
  assets/queries/cloudFormation/aws/memcached_disabled/metadata.json
  assets/queries/cloudFormation/aws/memcached_disabled/query.rego
  assets/queries/cloudFormation/aws/memcached_disabled/test/positive_expected_result.json
  assets/queries/terraform/aws/memcached_disabled/metadata.json
  assets/queries/terraform/aws/memcached_disabled/query.rego
  assets/queries/terraform/aws/memcached_disabled/test/positive_expected_result.json
Labels: query

#5343 fix(detector): Fix bug on GetBracketValues function
  pkg/detector/helper.go
Labels: bug

#5347 fix(vulnerability builder): fixed and improved DefaultVulnerabilityBuilder
  pkg/engine/vulnerability_builder.go
Labels: go

#5368 feat(query): Ensure Administrative Boundaries Between Resources for Kubernetes
  assets/queries/k8s/ensure_administrative_boundaries_between_resources/metadata.json
  assets/queries/k8s/ensure_administrative_boundaries_between_resources/query.rego
  assets/queries/k8s/ensure_administrative_boundaries_between_resources/test/negative.yaml
  assets/queries/k8s/ensure_administrative_boundaries_between_resources/test/positive.yaml
  assets/queries/k8s/ensure_administrative_boundaries_between_resources/test/positive_expected_result.json
Labels: query, kubernetes

#5371 fix(cpu): fix number cpus macos
  internal/console/helpers/helpers.go
  internal/console/pre_scan.go
Labels: bug

#5395 fix(InitializeMetrics): fixed access to CIFlag
  internal/console/pre_scan.go
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
Labels: bug, go

#5357 feat(result): added resourceType and resourceName to Google Deployment Management queries result
  assets/queries/googleDeploymentManager/bigquery_database_is_public/query.rego
  assets/queries/googleDeploymentManager/bucket_without_versioning/query.rego
  assets/queries/googleDeploymentManager/client_certificate_disabled/query.rego
  assets/queries/googleDeploymentManager/cloud_dns_without_dnnsec/query.rego
  assets/queries/googleDeploymentManager/cloud_storage_anonymous_or_publicly_accessible/query.rego
  assets/queries/googleDeploymentManager/cloud_storage_bucket_is_publicly_accessible/query.rego
  assets/queries/googleDeploymentManager/cloud_storage_bucket_versioning_disabled/query.rego
  assets/queries/googleDeploymentManager/cluster_labels_disabled/query.rego
  assets/queries/googleDeploymentManager/cluster_master_authentication_disabled/query.rego
  assets/queries/googleDeploymentManager/compute_instance_is_publicly_accessible/query.rego
  assets/queries/googleDeploymentManager/cos_node_image_not_used/query.rego
  assets/queries/googleDeploymentManager/disk_encryption_disabled/query.rego
  assets/queries/googleDeploymentManager/dnssec_using_rsasha1/query.rego
  assets/queries/googleDeploymentManager/gke_legacy_authorization_enabled/query.rego
  assets/queries/googleDeploymentManager/gke_master_authorized_networks_disabled/query.rego
  assets/queries/googleDeploymentManager/google_storage_bucket_level_access_disabled/query.rego
  assets/queries/googleDeploymentManager/ip_aliasing_disabled/query.rego
  assets/queries/googleDeploymentManager/ip_forwarding_enabled/query.rego
  assets/queries/googleDeploymentManager/mysql_instance_with_local_infile_on/query.rego
  assets/queries/googleDeploymentManager/network_policy_disabled/query.rego
  assets/queries/googleDeploymentManager/node_auto_upgrade_disabled/query.rego
  assets/queries/googleDeploymentManager/not_proper_email_account_in_use/query.rego
  assets/queries/googleDeploymentManager/os_login_is_disabled_for_vm_instance/query.rego
  assets/queries/googleDeploymentManager/private_cluster_disabled/query.rego
  assets/queries/googleDeploymentManager/project_wide_ssh_keys_are_enabled_in_vm_instances/query.rego
  assets/queries/googleDeploymentManager/rdp_access_is_not_restricted/query.rego
  assets/queries/googleDeploymentManager/shielded_vm_disabled/query.rego
  assets/queries/googleDeploymentManager/sql_db_instance_backup_disable/query.rego
  assets/queries/googleDeploymentManager/sql_db_instance_with_ssl_disabled/query.rego
  assets/queries/googleDeploymentManager/ssh_access_is_not_restricted/query.rego
  assets/queries/googleDeploymentManager/stackdriver_logging_disabled/query.rego
  assets/queries/googleDeploymentManager/stackdriver_monitoring_disabled/query.rego
  test/queries_content_test.go
Labels: query, gdm

#5400 fix(helm): fixed helm filepath bug introduced by resolver
  pkg/detector/helm/helm_detect.go
  pkg/detector/helm/helm_detect_test.go
  pkg/engine/vulnerability_builder.go
Labels: bug
