Repository Checkmarx/kics, pull requests merged in 2022-06, with the labels that each got.

#5424 fix(query): fixed incorrect Dockerfile metadata
  assets/queries/dockerfile/multiple_run_add_copy_instructions_listed/metadata.json
Labels: community

#5358 feat(query): added "App Service Without Latest PHP Version" query for Terraform Azure
  assets/queries/terraform/aws/cloudfront_without_waf/test/negative.tf
  assets/queries/terraform/aws/cloudfront_without_waf/test/positive.tf
  assets/queries/terraform/azure/app_service_without_latest_php_version/metadata.json
  assets/queries/terraform/azure/app_service_without_latest_php_version/query.rego
  assets/queries/terraform/azure/app_service_without_latest_php_version/test/negative1.tf
  assets/queries/terraform/azure/app_service_without_latest_php_version/test/negative2.tf
  assets/queries/terraform/azure/app_service_without_latest_php_version/test/negative3.tf
  assets/queries/terraform/azure/app_service_without_latest_php_version/test/positive1.tf
  assets/queries/terraform/azure/app_service_without_latest_php_version/test/positive2.tf
  assets/queries/terraform/azure/app_service_without_latest_php_version/test/positive3.tf
  assets/queries/terraform/azure/app_service_without_latest_php_version/test/positive_expected_result.json
  assets/queries/terraform/general/generic_git_module_without_revision/test/negative1.tf
  assets/queries/terraform/general/generic_git_module_without_revision/test/positive1.tf
  assets/queries/terraform/general/name_is_not_snake_case/test/negative1.tf
  assets/queries/terraform/general/name_is_not_snake_case/test/positive1.tf
  assets/queries/terraform/general/name_is_not_snake_case/test/positive2.tf
Labels: query, terraform, arm

#5434 update(docs): added -t flag on docker run command
  docs/BADGE.md
  docs/configuration-file.md
  docs/dockerhub.md
  docs/getting-started.md
  docs/platforms.md
  docs/running-kics.md
Labels: documentation

#5418 update(report): improved report message
  e2e/fixtures/schemas/result-asff.json
  e2e/fixtures/schemas/result-cyclonedx.json
  e2e/fixtures/schemas/result-junit.json
  pkg/report/model/asff.go
  pkg/report/model/asff_test.go
  pkg/report/model/cyclonedx.go
  pkg/report/model/cyclonedx_test.go
  pkg/report/model/junit.go
  pkg/report/model/junit_test.go
Labels: go

#5407 fix(analyzer): fixed Dockerfile analyzer approach
  go.mod
  go.sum
  pkg/analyzer/analyzer.go
  pkg/engine/provider/filesystem.go
  pkg/parser/docker/parser.go
  pkg/parser/docker/parser_test.go
  pkg/parser/parser.go
  pkg/utils/get_extension.go
  pkg/utils/get_extension_test.go
  test/fixtures/dockerfile/Dockerfile-example
Labels: bug, go

#5419 fix(inspector): fix timeout secrets inspector
  e2e/fixtures/samples/configs/config-dev.json
  e2e/fixtures/samples/configs/config-dev.yaml
  e2e/fixtures/samples/configs/config.json
  e2e/fixtures/samples/configs/config.yaml
  e2e/testcases/e2e-cli-029_scan_config.go
  e2e/testcases/e2e-cli-056_scan_timeout.go
  e2e/utils/helper.go
  pkg/engine/secrets/inspector.go
Labels: bug, go

#5408 feat(filesystem): double star support to exclude folders
  go.mod
  go.sum
  pkg/engine/provider/filesystem.go
  pkg/engine/provider/filesystem_test.go
Labels: go

#5415 fix(query): s3 bucket policy accepts http requests
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/query.rego
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/negative5.tf
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/negative6.tf
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/positive4.tf
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/positive5.tf
  assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/positive_expected_result.json
Labels: community

#5433 fix(queries): fixed function check_schemes of OpenAPI lib
  assets/libraries/openapi.rego
  assets/queries/openAPI/2.0/undefined_security_scope_global_security/query.rego
  assets/queries/openAPI/2.0/undefined_security_scope_security_operations/query.rego
  assets/queries/openAPI/2.0/undefined_security_scope_security_operations/test/positive_expected_result.json
  assets/queries/openAPI/3.0/undefined_security_scope_global_security/query.rego
  assets/queries/openAPI/3.0/undefined_security_scope_global_security/test/positive_expected_result.json
  assets/queries/openAPI/3.0/undefined_security_scope_security_operations/query.rego
  assets/queries/openAPI/3.0/undefined_security_scope_security_operations/test/positive_expected_result.json
Labels: bug, query, openapi

#5422 update(tfplan parser): support child modules
  assets/queries/terraform/azure/default_azure_storage_account_network_access_is_too_permissive/query.rego
  assets/queries/terraform/general/name_is_not_snake_case/query.rego
  pkg/parser/json/tfplan.go
Labels: go

#5429 fix(filesystem): added mutex to lock read and write on map
  pkg/engine/provider/filesystem.go
Labels: bug, go

#5460 fix(queries): align descriptionText to similar queries across different platforms #2
  assets/queries/ansible/aws/api_gateway_without_ssl_certificate/metadata.json
  assets/queries/ansible/aws/automatic_minor_upgrades_disabled/metadata.json
  assets/queries/ansible/aws/cloudtrail_multi_region_disabled/metadata.json
  assets/queries/ansible/aws/db_instance_publicly_accessible/metadata.json
  assets/queries/ansible/aws/elb_using_insecure_protocols/metadata.json
  assets/queries/ansible/aws/redshift_not_encrypted/metadata.json
  assets/queries/ansible/aws/redshift_publicly_accessible/metadata.json
  assets/queries/ansible/aws/s3_bucket_with_all_permissions/metadata.json
  assets/queries/ansible/gcp/cloud_storage_bucket_versioning_disabled/metadata.json
  assets/queries/ansible/gcp/node_auto_upgrade_disabled/metadata.json
  assets/queries/cloudFormation/aws/api_gateway_with_invalid_compression/metadata.json
  assets/queries/cloudFormation/aws/automatic_minor_upgrades_disabled/metadata.json
  assets/queries/cloudFormation/aws/cloudfront_logging_disabled/metadata.json
  assets/queries/cloudFormation/aws/cloudtrail_multi_region_disabled/metadata.json
  assets/queries/cloudFormation/aws/elb_using_weak_ciphers/metadata.json
  assets/queries/cloudFormation/aws/rds_storage_not_encrypted/metadata.json
  assets/queries/cloudFormation/aws/redshift_not_encrypted/metadata.json
  assets/queries/googleDeploymentManager/cloud_storage_bucket_versioning_disabled/metadata.json
  assets/queries/k8s/service_account_name_undefined_or_empty/metadata.json
  assets/queries/terraform/aws/api_gateway_with_invalid_compression/metadata.json
  assets/queries/terraform/aws/api_gateway_without_ssl_certificate/metadata.json
  assets/queries/terraform/aws/automatic_minor_upgrades_disabled/metadata.json
  assets/queries/terraform/aws/cloudfront_logging_disabled/metadata.json
  assets/queries/terraform/aws/cloudtrail_multi_region_disabled/metadata.json
  assets/queries/terraform/aws/db_instance_publicly_accessible/metadata.json
  assets/queries/terraform/aws/rds_storage_not_encrypted/metadata.json
  assets/queries/terraform/aws/redshift_not_encrypted/metadata.json
  assets/queries/terraform/aws/redshift_publicly_accessible/metadata.json
  assets/queries/terraform/aws/s3_bucket_with_all_permissions/metadata.json
  assets/queries/terraform/gcp/cloud_storage_bucket_versioning_disabled/metadata.json
  assets/queries/terraform/gcp/dnssec_using_rsasha1/metadata.json
  assets/queries/terraform/gcp/node_auto_upgrade_disabled/metadata.json
Labels: community

#5320 fix(query): uncomment cloud formation's test sample
  assets/queries/cloudFormation/aws/iam_access_analyzer_not_enabled/test/file.json
  assets/queries/cloudFormation/aws/iam_access_analyzer_not_enabled/test/negative1.yaml
Labels: community

#5479 feat(workflows): added branching process for major versions
  .github/workflows/go-ci-integration.yml
  .github/workflows/go-ci.yml
  .github/workflows/go-e2e.yaml
  .github/workflows/kics-gh-action.yaml
  .github/workflows/sonarcloud.yml
  .github/workflows/sync_major_release.yaml
Labels: github_actions

#5497 update(workflow): cancel previous runs in sync_major_release workflow
  .github/workflows/sync_major_release.yaml
Labels: github_actions

#5483 update(query): improved "Resource Not Using Tags" description
  assets/queries/terraform/aws/resource_not_using_tags/metadata.json
  assets/queries/terraform/aws/resource_not_using_tags/query.rego
  e2e/fixtures/E2E_CLI_033_RESULT.json
Labels: query, terraform, aws

#5503 fix(secrets inspector): added mutex to lock addVulnerability
  .github/workflows/go-ci.yml
  .github/workflows/go-test-race.yml
  assets/queries/k8s/object_is_using_a_deprecated_api_version/query.rego
  assets/queries/k8s/tiller_is_deployed/query.rego
  assets/queries/k8s/tiller_service_is_not_deleted/query.rego
  pkg/engine/secrets/inspector.go
Labels: go

#5511 fix(resolver): exclude resolve path call for the same path reference
  pkg/resolver/file/file.go
Labels: go

#5529 Add wafv2 to query incl. negative test
  assets/queries/terraform/aws/api_gateway_without_waf/query.rego
  assets/queries/terraform/aws/api_gateway_without_waf/test/negative2.tf
Labels: community

#5533 fix(scan behavior): ignore broken synlink
  pkg/engine/provider/filesystem.go
Labels: community
