Repository Checkmarx/kics, pull requests merged in 2022-02, with the labels that each got.

#4726 feat(query): added "SSH Access Is Not Restricted" for Google Deployment Manager
  assets/libraries/common.rego
  assets/queries/ansible/gcp/ssh_access_is_not_restricted/query.rego
  assets/queries/googleDeploymentManager/ssh_access_is_not_restricted/metadata.json
  assets/queries/googleDeploymentManager/ssh_access_is_not_restricted/query.rego
  assets/queries/googleDeploymentManager/ssh_access_is_not_restricted/test/negative1.yaml
  assets/queries/googleDeploymentManager/ssh_access_is_not_restricted/test/positive1.yaml
  assets/queries/googleDeploymentManager/ssh_access_is_not_restricted/test/positive2.yaml
  assets/queries/googleDeploymentManager/ssh_access_is_not_restricted/test/positive_expected_result.json
  assets/queries/terraform/gcp/ssh_access_is_not_restricted/query.rego
Labels: query, gdm

#4750 feat(query): added "Cluster Labels Disabled" for Google Deployment Manager
  assets/queries/googleDeploymentManager/cluster_labels_disabled/metadata.json
  assets/queries/googleDeploymentManager/cluster_labels_disabled/query.rego
  assets/queries/googleDeploymentManager/cluster_labels_disabled/test/negative1.yaml
  assets/queries/googleDeploymentManager/cluster_labels_disabled/test/positive1.yaml
  assets/queries/googleDeploymentManager/cluster_labels_disabled/test/positive_expected_result.json
Labels: query, gdm

#4751 feat(query): added "Stackdriver Logging Disabled" for Google Deployment Manager
  assets/queries/googleDeploymentManager/stackdriver_logging_disabled/metadata.json
  assets/queries/googleDeploymentManager/stackdriver_logging_disabled/query.rego
  assets/queries/googleDeploymentManager/stackdriver_logging_disabled/test/negative1.yaml
  assets/queries/googleDeploymentManager/stackdriver_logging_disabled/test/positive1.yaml
  assets/queries/googleDeploymentManager/stackdriver_logging_disabled/test/positive2.yaml
  assets/queries/googleDeploymentManager/stackdriver_logging_disabled/test/positive_expected_result.json
Labels: query, gdm

#4752 feat(query): added "Client Certificate Disabled" for Google Deployment Manager
  assets/queries/googleDeploymentManager/client_certificate_disabled/metadata.json
  assets/queries/googleDeploymentManager/client_certificate_disabled/query.rego
  assets/queries/googleDeploymentManager/client_certificate_disabled/test/negative1.yaml
  assets/queries/googleDeploymentManager/client_certificate_disabled/test/positive1.yaml
  assets/queries/googleDeploymentManager/client_certificate_disabled/test/positive2.yaml
  assets/queries/googleDeploymentManager/client_certificate_disabled/test/positive3.yaml
  assets/queries/googleDeploymentManager/client_certificate_disabled/test/positive_expected_result.json
Labels: query, gdm

#4767 fix(parser): added YAML alias as string
  pkg/model/model_yaml.go
  pkg/parser/yaml/parser_test.go
Labels: bug, go

#4768 fix(parser): added type handler to Terraform convertBody function
  pkg/parser/terraform/converter/default.go
Labels: bug, go

#4770 feat(analyzer): added support to Cloud Development Kit for Terraform (CDKTF)
  assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/negative3.json
  assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/positive5.json
  assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/positive_expected_result.json
  docs/platforms.md
  pkg/analyzer/analyzer.go
Labels: feature request, go

#4761 fix(report): fixed CycloneDX report for compressed files
  pkg/model/summary.go
  pkg/model/summary_test.go
  pkg/report/cyclonedx.go
  pkg/report/model/cyclonedx.go
  pkg/report/model/cyclonedx_test.go
  pkg/scan/post_scan.go
  pkg/scan/scan.go
Labels: bug, go

#4725 feat(query): added "OSLogin Is Disabled In VM Instance" for Google Deployment Manager
  assets/queries/ansible/gcp/oslogin_is_disabled_for_vm_instance/metadata.json
  assets/queries/googleDeploymentManager/os_login_is_disabled_for_vm_instance/metadata.json
  assets/queries/googleDeploymentManager/os_login_is_disabled_for_vm_instance/query.rego
  assets/queries/googleDeploymentManager/os_login_is_disabled_for_vm_instance/test/negative1.yaml
  assets/queries/googleDeploymentManager/os_login_is_disabled_for_vm_instance/test/negative2.yaml
  assets/queries/googleDeploymentManager/os_login_is_disabled_for_vm_instance/test/positive1.yaml
  assets/queries/googleDeploymentManager/os_login_is_disabled_for_vm_instance/test/positive_expected_result.json
Labels: query, gdm

#4758 feat(query): added "MySQL Instance With Local Infile On" for Google Deployment Manager
  assets/queries/googleDeploymentManager/mysql_instance_with_local_infile_on/metadata.json
  assets/queries/googleDeploymentManager/mysql_instance_with_local_infile_on/query.rego
  assets/queries/googleDeploymentManager/mysql_instance_with_local_infile_on/test/negative1.yaml
  assets/queries/googleDeploymentManager/mysql_instance_with_local_infile_on/test/negative2.yaml
  assets/queries/googleDeploymentManager/mysql_instance_with_local_infile_on/test/positive1.yaml
  assets/queries/googleDeploymentManager/mysql_instance_with_local_infile_on/test/positive_expected_result.json
Labels: query, gdm

#4756 fix(report): fixed null ASFF report
  pkg/report/model/asff.go
Labels: go

#4757 docs(kics.io): Removed binaries and changed all cmds to Docker cmds
  docs/configuration-file.md
  docs/getting-started.md
  docs/index.md
  docs/integrations_jenkins.md
  docs/releases.md
  docs/running-kics.md
Labels: documentation

#4749 feat(query): added "COS Node Image Not Used" for Google Deployment Manager
  assets/queries/ansible/gcp/cos_node_image_not_used/metadata.json
  assets/queries/ansible/gcp/cos_node_image_not_used/query.rego
  assets/queries/ansible/gcp/cos_node_image_not_used/test/negative2.yaml
  assets/queries/googleDeploymentManager/cos_node_image_not_used/metadata.json
  assets/queries/googleDeploymentManager/cos_node_image_not_used/query.rego
  assets/queries/googleDeploymentManager/cos_node_image_not_used/test/negative1.yaml
  assets/queries/googleDeploymentManager/cos_node_image_not_used/test/negative2.yaml
  assets/queries/googleDeploymentManager/cos_node_image_not_used/test/negative3.yaml
  assets/queries/googleDeploymentManager/cos_node_image_not_used/test/positive1.yaml
  assets/queries/googleDeploymentManager/cos_node_image_not_used/test/positive_expected_result.json
  assets/queries/terraform/gcp/cos_node_image_not_used/metadata.json
  assets/queries/terraform/gcp/cos_node_image_not_used/query.rego
  assets/queries/terraform/gcp/cos_node_image_not_used/test/negative.tf
Labels: query, gdm

#4784 feat(docs): updated ASFF documentation
  docs/results.md
Labels: documentation

#4795 fix(doc): Removed Travis CI binary example
  docs/integrations_travisci.md
Labels: documentation, integrations

#4792 fix(golang): Generic error message go-getter
  pkg/engine/provider/extract.go
Labels: go

#4791 feat(docs): added Bamboo integration
  docs/integrations.md
  docs/integrations_bamboo.md
  mkdocs.yml
Labels: documentation, integrations

#4796 fix(report): Improved junit report
  e2e/fixtures/schemas/result-junit.json
  pkg/report/model/junit.go
  pkg/report/model/junit_test.go
Labels: go

#4813 feat(cli): multiple paths for queries
  docs/commands.md
  docs/dockerhub.md
  e2e/fixtures/assets/scan_help
  e2e/fixtures/schemas/result-asff.json
  internal/console/assets/scan-flags.json
  internal/console/scan.go
  pkg/engine/inspector_test.go
  pkg/engine/source/filesystem.go
  pkg/engine/source/filesystem_test.go
  pkg/scan/client.go
  pkg/scan/utils.go
  pkg/scanner/scanner_test.go
Labels: go

#4819 feat(docs): added SAM and CDK logos to supported platforms
  README.md
  docs/img/logo-cdk.png
  docs/img/logo-sam.png
Labels: documentation

#4821 feat(ci): added release commits action
  .github/scripts/release-commits/get_commits.py
  .github/scripts/release-commits/requirements.txt
  .github/workflows/release-commits.yaml
Labels: CI

#4834 fix(query): changed severity, description text and URL in "Liveness Probe Is Not Defined" query
  assets/queries/k8s/liveness_probe_is_not_defined/metadata.json
  assets/queries/k8s/liveness_probe_is_not_defined/test/positive_expected_result.json
Labels: query, kubernetes

#4790 feat(doc): AWS CodeBuild integration
  docs/img/codebuild-report-section.png
  docs/img/codebuild-report.png
  docs/img/codebuild-test-cases.png
  docs/integrations.md
  docs/integrations_aws_codebuild.md
  mkdocs.yml
Labels: documentation, integrations

#4836 doc(integrations): Removed GitlabCI binary example
  docs/integrations_gitlabci.md
  examples/gitlab/KICS.v1.gitlabci.yaml
  examples/jenkins/agent-linux-simple-declarative.jenkinsfile
Labels: documentation, integrations

#4805 fix(analyzer): Fixed scan on GDM sample
  pkg/analyzer/analyzer.go
Labels: bug, go

#4804 feat(terraformer): added terraformer integration with GCP
  Dockerfile
  Dockerfile.apispec
  Dockerfile.apispec.debian
  Dockerfile.debian
  Dockerfile.ubi7
  docs/integrations_terraformer.md
  pkg/terraformer/gcp/gcp_cloud_provider.go
  pkg/terraformer/gcp/gcp_cloud_provider_test.go
  pkg/terraformer/terraformer.go
  pkg/terraformer/terraformer_test.go
Labels: feature, CI, go

#4838 feat(report): added Checkmarx logo to pdf report
  docs/img/logo/checkmarx-logo.png
  pkg/report/pdf.go
Labels: go

#4844 feat(report): added Checkmarx logo to HTML report
  pkg/report/template/html/report.tmpl
Labels: go

#4843 fix(query): fixed "Service Control Policies Disabled" query
  assets/queries/terraform/aws/service_control_policies_disabled/metadata.json
  assets/queries/terraform/aws/service_control_policies_disabled/query.rego
  assets/queries/terraform/aws/service_control_policies_disabled/test/negative.tf
  assets/queries/terraform/aws/service_control_policies_disabled/test/positive.tf
  assets/queries/terraform/aws/service_control_policies_disabled/test/positive_expected_result.json
Labels: query

#4840 feat(tests): added unit tests for multiple query path
  e2e/fixtures/samples/queries/valid/multiple_query/s3_bucket_without_enabled_mfa_delete/metadata.json
  e2e/fixtures/samples/queries/valid/multiple_query/s3_bucket_without_enabled_mfa_delete/query.rego
  e2e/testcases/e2e-cli-054_scan_multiple-queries-path.go
  pkg/engine/inspector_test.go
  pkg/engine/source/filesystem_test.go
  pkg/scan/utils.go
  pkg/scan/utils_test.go
  pkg/scanner/scanner_test.go
Labels: go

#4858 Update "Trusted Microsoft Services Not Enabled".
  assets/queries/azureResourceManager/trusted_microsoft_services_not_enabled/metadata.json
Labels: documentation, azure

#4857 fix(analyzer): fixed and improved regexes in analyzer
  pkg/analyzer/analyzer.go
Labels: bug, go
