Repository Checkmarx/kics, pull requests merged in 2023-03, with the labels that each got.

#6153 refactor(tf-gcp-auth): Remove obsolete GKE Auth queries for TF
  assets/queries/terraform/gcp/cluster_master_authentication_disabled/metadata.json
  assets/queries/terraform/gcp/cluster_master_authentication_disabled/query.rego
  assets/queries/terraform/gcp/cluster_master_authentication_disabled/test/negative.tf
  assets/queries/terraform/gcp/cluster_master_authentication_disabled/test/positive.tf
  assets/queries/terraform/gcp/cluster_master_authentication_disabled/test/positive_expected_result.json
  assets/queries/terraform/gcp/gke_basic_authentication_enabled/metadata.json
  assets/queries/terraform/gcp/gke_basic_authentication_enabled/query.rego
  assets/queries/terraform/gcp/gke_basic_authentication_enabled/test/negative.tf
  assets/queries/terraform/gcp/gke_basic_authentication_enabled/test/positive.tf
  assets/queries/terraform/gcp/gke_basic_authentication_enabled/test/positive_expected_result.json
  docs/queries/terraform-queries.md
Labels: community

#6145 azure-instance-using-default-auth-tf-and-ansible-support TF&Ansible support
  assets/queries/ansible/azure/azure_instance_using_basic_authentication/metadata.json
  assets/queries/ansible/azure/azure_instance_using_basic_authentication/query.rego
  assets/queries/ansible/azure/azure_instance_using_basic_authentication/test/negative.yaml
  assets/queries/ansible/azure/azure_instance_using_basic_authentication/test/positive.yaml
  assets/queries/ansible/azure/azure_instance_using_basic_authentication/test/positive_expected_result.json
  assets/queries/terraform/azure/azure_instance_using_basic_authentication/metadata.json
  assets/queries/terraform/azure/azure_instance_using_basic_authentication/query.rego
  assets/queries/terraform/azure/azure_instance_using_basic_authentication/test/negative1.tf
  assets/queries/terraform/azure/azure_instance_using_basic_authentication/test/negative2.tf
  assets/queries/terraform/azure/azure_instance_using_basic_authentication/test/positive1.tf
  assets/queries/terraform/azure/azure_instance_using_basic_authentication/test/positive2.tf
  assets/queries/terraform/azure/azure_instance_using_basic_authentication/test/positive_expected_result.json
Labels: community

#6222 feat(analyzer): add expected lines of code in analyzer
  pkg/analyzer/analyzer.go
  pkg/analyzer/analyzer_test.go
  pkg/model/model.go
  pkg/scan/utils_test.go
  pkg/utils/line_counter.go
  pkg/utils/line_counter_test.go
Labels: go, tests

#6231 bump(go): update to go 1.20
  .github/workflows/go-ci-coverage.yaml
  .github/workflows/go-ci.yml
  .github/workflows/go-e2e.yaml
  .github/workflows/go-test-race.yml
  .github/workflows/release-apispec.yml
  .github/workflows/release-commits.yaml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
  .github/workflows/statistics.yaml
  docker/Dockerfile.ubi8
  go.mod
  pkg/descriptions/client.go
  pkg/printer/options_test.go
  pkg/report/html.go
Labels: dependencies, go

#6252 fix(query): add exception for Github id-token Default Values rule
  assets/queries/common/passwords_and_secrets/regex_rules.json
  assets/queries/common/passwords_and_secrets/test/negative52.yaml
Labels: bug, query

#6255 fix(query): Effect 'Allow' conditions added
  assets/queries/cloudFormation/aws/s3_bucket_without_ssl_in_write_actions/query.rego
  assets/queries/cloudFormation/aws/s3_bucket_without_ssl_in_write_actions/test/negative7.yaml
  assets/queries/cloudFormation/aws/s3_bucket_without_ssl_in_write_actions/test/positive2.yaml
  assets/queries/cloudFormation/aws/s3_bucket_without_ssl_in_write_actions/test/positive3.yaml
  assets/queries/cloudFormation/aws/s3_bucket_without_ssl_in_write_actions/test/positive6.json
  assets/queries/cloudFormation/aws/s3_bucket_without_ssl_in_write_actions/test/positive_expected_result.json
Labels: query, tests

#6261 fix(query): added issue.solution var to differentiate issue types
  assets/queries/openAPI/3.0/additional_properties_too_permissive/query.rego
Labels: bug, query
