Repository Checkmarx/kics, pull requests merged in 2023-06, with the labels that each got.

#6410 feat(query): Elasticsearch Log Disabled
  assets/queries/pulumi/aws/elasticsearch_logs_disabled/metadata.json
  assets/queries/pulumi/aws/elasticsearch_logs_disabled/query.rego
  assets/queries/pulumi/aws/elasticsearch_logs_disabled/test/negative1.yaml
  assets/queries/pulumi/aws/elasticsearch_logs_disabled/test/positive1.yaml
  assets/queries/pulumi/aws/elasticsearch_logs_disabled/test/positive2.yaml
  assets/queries/pulumi/aws/elasticsearch_logs_disabled/test/positive3.yaml
  assets/queries/pulumi/aws/elasticsearch_logs_disabled/test/positive_expected_result.json
Labels: feature, query, pulumi

#6412 feat(query): Elasticsearch with HTTPS disabled for CloudFormation
  assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/metadata.json
  assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/query.rego
  assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/negative1.yaml
  assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/negative2.json
  assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/negative3.yaml
  assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/positive1.yaml
  assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/positive2.yaml
  assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/positive3.json
  assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/positive4.json
  assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/positive5.json
  assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/positive_expected_result.json
Labels: feature, query, cloudformation

#6352 feat(query): Publicly Accessible Amazon DMS
  assets/queries/cloudFormation/aws/amazon_dms_replication_instance_is_publicly_accessible/metadata.json
  assets/queries/cloudFormation/aws/amazon_dms_replication_instance_is_publicly_accessible/query.rego
  assets/queries/cloudFormation/aws/amazon_dms_replication_instance_is_publicly_accessible/test/negative1.yaml
  assets/queries/cloudFormation/aws/amazon_dms_replication_instance_is_publicly_accessible/test/positive1.yaml
  assets/queries/cloudFormation/aws/amazon_dms_replication_instance_is_publicly_accessible/test/positive2.yaml
  assets/queries/cloudFormation/aws/amazon_dms_replication_instance_is_publicly_accessible/test/positive_expected_result.json
  assets/queries/pulumi/aws/amazon_dms_replication_instance_is_publicly_accessible/metadata.json
  assets/queries/pulumi/aws/amazon_dms_replication_instance_is_publicly_accessible/query.rego
  assets/queries/pulumi/aws/amazon_dms_replication_instance_is_publicly_accessible/test/negative1.yaml
  assets/queries/pulumi/aws/amazon_dms_replication_instance_is_publicly_accessible/test/positive1.yaml
  assets/queries/pulumi/aws/amazon_dms_replication_instance_is_publicly_accessible/test/positive2.yaml
  assets/queries/pulumi/aws/amazon_dms_replication_instance_is_publicly_accessible/test/positive_expected_result.json
  assets/queries/terraform/aws/amazon_dms_replication_instance_is_publicly_accessible/metadata.json
  assets/queries/terraform/aws/amazon_dms_replication_instance_is_publicly_accessible/query.rego
  assets/queries/terraform/aws/amazon_dms_replication_instance_is_publicly_accessible/test/negative1.tf
  assets/queries/terraform/aws/amazon_dms_replication_instance_is_publicly_accessible/test/negative2.tf
  assets/queries/terraform/aws/amazon_dms_replication_instance_is_publicly_accessible/test/positive1.tf
  assets/queries/terraform/aws/amazon_dms_replication_instance_is_publicly_accessible/test/positive_expected_result.json
Labels: feature, query

#6426 chore(-): update gitlab sast schema to 15.0.6
  docs/results.md
  e2e/fixtures/schemas/result-gl-sast.json
  pkg/report/model/gitlab_sast.go
  pkg/report/model/gitlab_sast_test.go
Labels: community

#6439 remove unused allowRule
  assets/queries/common/passwords_and_secrets/regex_rules.json
Labels: community

#6405 Feature(Engine) Resolve internal/external section references
  assets/queries/cloudFormation/aws/alb_listening_on_http/query.rego
  assets/queries/openAPI/2.0/constraining_enum_property/test/positive_expected_result.json
  assets/queries/openAPI/2.0/json_reference_does_not_exists_parameter/query.rego
  assets/queries/openAPI/2.0/parameter_object_incorrect_ref/query.rego
  assets/queries/openAPI/2.0/response_object_incorrect_ref/query.rego
  assets/queries/openAPI/2.0/schema_object_incorrect_ref/query.rego
  assets/queries/openAPI/2.0/schema_with_additional_properties_set_as_boolean/test/positive_expected_result.json
  assets/queries/openAPI/3.0/callback_object_incorrect_ref/query.rego
  assets/queries/openAPI/3.0/example_json_reference_outside_components_examples/query.rego
  assets/queries/openAPI/3.0/header_object_with_incorrect_ref/query.rego
  assets/queries/openAPI/3.0/json_reference_does_not_exists_callback/query.rego
  assets/queries/openAPI/3.0/json_reference_does_not_exists_example/query.rego
  assets/queries/openAPI/3.0/json_reference_does_not_exists_header/query.rego
  assets/queries/openAPI/3.0/json_reference_does_not_exists_link/query.rego
  assets/queries/openAPI/3.0/json_reference_does_not_exists_parameter/query.rego
  assets/queries/openAPI/3.0/json_reference_does_not_exists_request_body/query.rego
  assets/queries/openAPI/3.0/json_reference_does_not_exists_response/query.rego
  assets/queries/openAPI/3.0/json_reference_does_not_exists_schema/query.rego
  assets/queries/openAPI/3.0/link_object_incorrect_ref/query.rego
  assets/queries/openAPI/3.0/parameter_object_incorrect_ref/query.rego
  assets/queries/openAPI/3.0/parameter_object_schema_content/query.rego
  assets/queries/openAPI/3.0/request_body_incorrect_ref/query.rego
  assets/queries/openAPI/3.0/request_body_object_with_incorrect_media_type/query.rego
  assets/queries/openAPI/3.0/response_object_incorrect_ref/query.rego
  assets/queries/openAPI/3.0/schema_object_incorrect_ref/query.rego
  assets/queries/openAPI/3.0/unknown_property/query.rego
  assets/queries/openAPI/general/header_response_name_is_invalid/test/positive_expected_result.json
  assets/queries/openAPI/general/invalid_format/test/positive_expected_result.json
  assets/queries/openAPI/general/json_object_schema_without_properties/query.rego
  assets/queries/openAPI/general/json_object_schema_without_type/query.rego
  assets/queries/openAPI/general/json_ref_alongside_properties/query.rego
  assets/queries/openAPI/general/maximum_length_undefined/test/positive_expected_result.json
  assets/queries/openAPI/general/no_global_and_operation_security_defined/query.rego
  assets/queries/openAPI/general/non_array_schema_with_items/test/positive_expected_result.json
  assets/queries/openAPI/general/numeric_schema_without_format/test/positive_expected_result.json
  assets/queries/openAPI/general/numeric_schema_without_maximum/test/positive_expected_result.json
  assets/queries/openAPI/general/numeric_schema_without_minimum/test/positive_expected_result.json
  assets/queries/openAPI/general/pattern_undefined/test/positive_expected_result.json
  assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/positive_expected_result.json
  assets/queries/openAPI/general/required_property_default_value/test/positive_expected_result.json
  assets/queries/openAPI/general/schema_enum_invalid/test/positive_expected_result.json
  assets/queries/openAPI/general/schema_object_with_circular_ref/query.rego
  assets/queries/openAPI/general/string_schema_with_broad_pattern/test/positive_expected_result.json
  assets/queries/openAPI/general/type_has_invalid_keyword/test/positive_expected_result.json
  e2e/fixtures/E2E_CLI_031_RESULT.html
  e2e/fixtures/E2E_CLI_032_RESULT.json
  e2e/fixtures/E2E_CLI_036_RESULT.json
  e2e/fixtures/E2E_CLI_036_RESULT_2.json
  e2e/fixtures/E2E_CLI_040_RESULT.html
  e2e/testcases/e2e-cli-055_scan_resolve_openapi_files.go
  pkg/detector/default_detect.go
  pkg/detector/helper.go
  pkg/engine/inspector.go
  pkg/engine/vulnerability_builder.go
  pkg/resolver/file/file.go
  pkg/resolver/file/file_test.go
  test/main_test.go
Labels: community

#6452 fix(analyzer): Removed void Symlinks
  pkg/analyzer/analyzer.go
  pkg/analyzer/analyzer_test.go
  test/fixtures/analyzer_test/dead_symlink
Labels: bug, community

#6469 fix(sink): Added regex to subs "\r" (line break)
  pkg/kics/sink.go
  pkg/kics/sink_test.go
Labels: bug
