Repository Checkmarx/kics, pull requests merged in 2023-11, with the labels that each got.

#6757 fix(query): false positive detections in "api_key_exposed" function
  assets/libraries/openapi.rego
  assets/queries/openAPI/general/api_key_exposed_in_global_security/test/negative5.yaml
  assets/queries/openAPI/general/api_key_exposed_in_operation_security/test/negative5.yaml
Labels: query, community

#6773 feat(engine): improve detection of Ansible files
  pkg/analyzer/analyzer.go
  pkg/analyzer/analyzer_test.go
Labels: feature, ansible

#6769 feat(engine): experimental queries as feature flag
  .github/workflows/go-ci.yml
  Dockerfile
  assets/utils/experimental-queries.json
  docker/Dockerfile.apispec
  docker/Dockerfile.apispec.debian
  docker/Dockerfile.debian
  docs/commands.md
  docs/dockerhub.md
  e2e/fixtures/E2E_CLI_069_RESULT.json
  e2e/fixtures/E2E_CLI_070_RESULT.json
  e2e/fixtures/assets/scan_help
  e2e/testcases/e2e-cli-069_ignore_experimental_query.go
  e2e/testcases/e2e-cli-070_not_ignore_experimental_query.go
  internal/console/assets/scan-flags.json
  internal/console/helpers/helpers.go
  internal/console/scan.go
  internal/tracker/ci_test.go
  pkg/detector/default_detect_test.go
  pkg/engine/inspector_test.go
  pkg/engine/source/filesystem.go
  pkg/engine/source/filesystem_test.go
  pkg/engine/source/source.go
  pkg/model/model.go
  pkg/remediation/scan.go
  pkg/scan/client.go
  pkg/scan/scan.go
  pkg/scanner/scanner_test.go
  test/fixtures/experimental_test/queries/redis_disable_experimental/metadata.json
  test/fixtures/experimental_test/queries/redis_disable_experimental/query.rego
  test/fixtures/experimental_test/queries/redis_disabled/metadata.json
  test/fixtures/experimental_test/queries/redis_disabled/query.rego
  test/fixtures/experimental_test/sample/sample.tf
  test/fixtures/test_experimental_queries/experimental_queries_queries/experimental/test/metadata.json
  test/fixtures/test_experimental_queries/experimental_queries_queries/tested/tested_query/metadata.json
  test/queries_content_test.go
Labels: feature, query

#6553 fix(query): iam_access_analyzer_not_enabled
  assets/queries/cloudFormation/aws/iam_access_analyzer_not_enabled/query.rego
  assets/queries/cloudFormation/aws/iam_access_analyzer_not_enabled/test/negative2.json
  assets/queries/cloudFormation/aws/iam_access_analyzer_not_enabled/test/positive2.json
  assets/queries/cloudFormation/aws/iam_access_analyzer_not_enabled/test/positive_expected_result.json
Labels: query

#6788 feat(kics): create a kics-queries-repo branch for all queries each release
  .github/scripts/kics-queries-repo-branch-creation/config-template/config.yml
  .github/workflows/release-kics-queries-repo-branch.yaml
Labels: feature, query

#6792 fix(workflow): update release-kics-queries-repo-branch.yaml
  .github/workflows/release-kics-queries-repo-branch.yaml
Labels: query

#6794 fix(deps): update go version version in debian image
  docker/Dockerfile.debian
Labels: dockerfile

#6803 update(metadata): queries validator schema updated
  .github/scripts/queries-validator/metadata-schema.json
Labels: query

#6805 update(readme): add information regarding beta features
  README.md
  docs/index.md
Labels: query

#6314 feat(nifcloud): add nifcloud engine support
  .github/scripts/queries-validator/metadata-schema.json
  assets/queries/terraform/nifcloud/computing_instance_has_common_private/metadata.json
  assets/queries/terraform/nifcloud/computing_instance_has_common_private/query.rego
  assets/queries/terraform/nifcloud/computing_instance_has_common_private/test/negative.tf
  assets/queries/terraform/nifcloud/computing_instance_has_common_private/test/positive1.tf
  assets/queries/terraform/nifcloud/computing_instance_has_common_private/test/positive2.tf
  assets/queries/terraform/nifcloud/computing_instance_has_common_private/test/positive_expected_result.json
  e2e/fixtures/assets/scan_help
  internal/constants/constants.go
  pkg/engine/source/filesystem.go
  pkg/engine/source/filesystem_test.go
  test/main_test.go
Labels: feature request, terraform, community

#6798 feat(engine): improve experimental signal on the results and cli
  e2e/fixtures/E2E_CLI_032_RESULT.json
  e2e/fixtures/E2E_CLI_033_RESULT.json
  e2e/fixtures/E2E_CLI_036_RESULT.json
  e2e/fixtures/E2E_CLI_036_RESULT_2.json
  e2e/fixtures/E2E_CLI_068_RESULT.json
  e2e/fixtures/E2E_CLI_069_RESULT.json
  e2e/fixtures/E2E_CLI_070_RESULT.json
  pkg/engine/inspector.go
  pkg/engine/vulnerability_builder.go
  pkg/engine/vulnerability_utils.go
  pkg/model/model.go
  pkg/model/summary.go
  pkg/printer/printer.go
  pkg/printer/printer_test.go
  test/helpers.go
Labels: feature

#6789 feat(engine): resolve references between files as flag
  docs/commands.md
  docs/dockerhub.md
  e2e/fixtures/E2E_CLI_070_RESULT.json
  e2e/fixtures/E2E_CLI_071_RESULT.json
  e2e/fixtures/E2E_CLI_072_RESULT.json
  e2e/fixtures/E2E_CLI_073_RESULT.json
  e2e/fixtures/E2E_CLI_074_RESULT.json
  e2e/fixtures/assets/scan_help
  e2e/testcases/e2e-cli-071_no_flag_resolve_references.go
  e2e/testcases/e2e-cli-072_flag_resolve_references.go
  e2e/testcases/e2e-cli-073_json_no_flag_resolve_references.go
  e2e/testcases/e2e-cli-074_json_flag_resolve_references.go
  internal/console/assets/scan-flags.json
  internal/console/flags/scan_flags.go
  internal/console/remediate.go
  internal/console/scan.go
  pkg/analyzer/analyzer.go
  pkg/kics/resolver_sink.go
  pkg/kics/service.go
  pkg/kics/sink.go
  pkg/parser/ansible/ini/config/parser.go
  pkg/parser/ansible/ini/hosts/parser.go
  pkg/parser/buildah/parser.go
  pkg/parser/buildah/parser_test.go
  pkg/parser/docker/parser.go
  pkg/parser/docker/parser_test.go
  pkg/parser/grpc/parser.go
  pkg/parser/grpc/parser_test.go
  pkg/parser/json/parser.go
  pkg/parser/json/parser_test.go
  pkg/parser/parser.go
  pkg/parser/parser_test.go
  pkg/parser/terraform/terraform.go
  pkg/parser/terraform/terraform_test.go
  pkg/parser/yaml/parser.go
  pkg/parser/yaml/parser_test.go
  pkg/remediation/remediation.go
  pkg/remediation/remediation_test.go
  pkg/remediation/scan.go
  pkg/remediation/utils.go
  pkg/resolver/file/file.go
  pkg/resolver/file/file_test.go
  pkg/scan/client.go
  pkg/scan/post_scan.go
  pkg/scan/scan.go
  pkg/scanner/scanner.go
  test/fixtures/resolve_references/paths/users/user.yaml
  test/fixtures/resolve_references/schemas/MyResponse.yaml
  test/fixtures/resolve_references/swagger.yaml
  test/fixtures/resolve_references_json/definitions.json
  test/fixtures/resolve_references_json/scan-2files.json
  test/main_test.go
  test/queries_test.go
Labels: feature

#6801 fix(parser): tf function evaluation - uknown type
  e2e/fixtures/E2E_CLI_071_PAYLOAD.json
  e2e/fixtures/samples/tf-eval-func-unknown-type/main.tf
  e2e/fixtures/samples/tf-eval-func-unknown-type/variables.tf
  e2e/testcases/e2e-cli-071_tf_eval_func_unknown_type.go
  pkg/parser/terraform/converter/default.go
Labels: terraform, community

#6816 feat(engine): improve detection of Ansible host files
  e2e/fixtures/E2E_CLI_075_RESULT.json
  e2e/testcases/e2e-cli-075_ansible_host_detected.go
  pkg/analyzer/analyzer.go
  pkg/analyzer/analyzer_test.go
  test/fixtures/analyzer_test_ansible_host/ansiblehost.yaml
  test/fixtures/analyzer_test_ansible_host/ansiblehost2.yaml
  test/fixtures/analyzer_test_ansible_host/ansiblehost3.yaml
  test/fixtures/analyzer_test_ansible_host/e2e/positive1.ini
  test/fixtures/analyzer_test_ansible_host/e2e/positive2.yaml
Labels: feature, ansible
