Repository Checkmarx/kics, pull requests merged in 2023-07, with the labels that each got.

#6447 feature(logs): Add Ignored Lines
  e2e/fixtures/E2E_CLI_032_RESULT.json
  e2e/fixtures/E2E_CLI_033_RESULT.json
  e2e/fixtures/E2E_CLI_036_RESULT.json
  e2e/fixtures/E2E_CLI_036_RESULT_2.json
  e2e/fixtures/schemas/result.json
  e2e/testcases/e2e-cli-038_scan_log-path.go
  internal/tracker/ci.go
  internal/tracker/ci_test.go
  pkg/kics/resolver_sink.go
  pkg/kics/service.go
  pkg/kics/sink.go
  pkg/model/summary.go
  pkg/printer/printer.go
  pkg/resolver/file/file.go
  pkg/scan/post_scan.go
  pkg/scan/post_scan_test.go
  pkg/scan/preview_secrets_mask_test.go
Labels: bug, query

#6487 fix(query): Add SearchLine
  assets/queries/cloudFormation/aws/http_port_open/query.rego
  assets/queries/cloudFormation/aws/http_port_open/test/positive_expected_result.json
  assets/queries/cloudFormation/aws/unrestricted_security_group_ingress/query.rego
  assets/queries/cloudFormation/aws/unrestricted_security_group_ingress/test/positive_expected_result.json
Labels: bug, query

#6490 iam_access_analyzer_not_enabled Query Changed
  assets/queries/cloudFormation/aws/iam_access_analyzer_not_enabled/query.rego
Labels: bug, query

#6508 fix(query): ddd missing search value in response code missing query for open api
  assets/queries/openAPI/general/response_code_missing/query.rego
Labels: bug, query, openapi

#6501 fix(Tracker): Add Resolved File Lines' counter
  pkg/kics/sink.go
  pkg/resolver/file/file.go
Labels: bug

#6522 fix(secrets): improve oAuthSecret secret to detect more valid characters
  assets/queries/common/passwords_and_secrets/regex_rules.json
  assets/queries/common/passwords_and_secrets/test/positive47.tf
  assets/queries/common/passwords_and_secrets/test/positive_expected_result.json
Labels: bug, query

#6529 fix(regex): Add Quotation mark
  assets/queries/common/passwords_and_secrets/regex_rules.json
Labels: bug

#6494 fix(summary): Add SearchLine Key to qItem
  e2e/fixtures/E2E_CLI_032_RESULT.json
  e2e/fixtures/E2E_CLI_033_RESULT.json
  e2e/fixtures/E2E_CLI_036_RESULT.json
  e2e/fixtures/E2E_CLI_036_RESULT_2.json
  e2e/fixtures/schemas/result-csv.json
  e2e/fixtures/schemas/result.json
  e2e/fixtures/schemas/resultBoM.json
  pkg/model/summary.go
Labels: bug

#6477 fix(query): transit_encryption attribute changed
  .github/workflows/validate-tf-samples.yml
  assets/queries/terraform/aws/ecs_task_definition_volume_not_encrypted/metadata.json
  assets/queries/terraform/aws/ecs_task_definition_volume_not_encrypted/query.rego
  assets/queries/terraform/aws/ecs_task_definition_volume_not_encrypted/test/positive3.tf
  assets/queries/terraform/aws/ecs_task_definition_volume_not_encrypted/test/positive_expected_result.json
  assets/queries/terraform/aws/efs_volume_with_disabled_transit_encryption/metadata.json
  assets/queries/terraform/aws/efs_volume_with_disabled_transit_encryption/query.rego
  assets/queries/terraform/aws/efs_volume_with_disabled_transit_encryption/test/negative1.tf
  assets/queries/terraform/aws/efs_volume_with_disabled_transit_encryption/test/positive1.tf
  assets/queries/terraform/aws/efs_volume_with_disabled_transit_encryption/test/positive2.tf
  assets/queries/terraform/aws/efs_volume_with_disabled_transit_encryption/test/positive_expected_result.json
Labels: bug

#6538 fix(query): Add Allow Rule to Generic Private Key
  assets/queries/common/passwords_and_secrets/regex_rules.json
  assets/queries/common/passwords_and_secrets/test/negative56.yml
  assets/queries/common/passwords_and_secrets/test/positive49.yml
  assets/queries/common/passwords_and_secrets/test/positive_expected_result.json
Labels: bug

#6535 fix(inspector): Change regex special mask
  assets/queries/common/passwords_and_secrets/regex_rules.json
  pkg/engine/secrets/inspector.go
Labels: bug
