Repository Checkmarx/kics, pull requests merged in 2023-12, with the labels that each got.

#6807 fix(parser): reduce complexity of initializeJSONLine
  pkg/parser/json/json_line.go
Labels: enhancement, community

#6815 fix(converter): improve check dynamic known types
  pkg/parser/terraform/converter/default.go
  pkg/parser/terraform/converter/default_test.go
Labels: enhancement, community

#6809 feat(kics): add platform field to sarif format
  e2e/fixtures/schemas/result-sarif-required.json
  e2e/fixtures/schemas/result-sarif.json
  pkg/report/model/sarif.go
  pkg/report/model/sarif_test.go
Labels: feature request, community

#6830 fix(metrics): add buildah and cicd to queries count
  .github/scripts/metrics/get_metrics.py
Labels: query

#6670 feat(cli): add new flag --max-file-size to control the max file size
  docs/commands.md
  e2e/fixtures/E2E_CLI_076_RESULT.json
  e2e/fixtures/assets/scan_help
  e2e/testcases/e2e-cli-076_max_file_size.go
  internal/console/analyze.go
  internal/console/assets/scan-flags.json
  internal/console/flags/scan_flags.go
  internal/console/pre_scan.go
  internal/console/scan.go
  pkg/analyzer/analyzer.go
  pkg/analyzer/analyzer_test.go
  pkg/kics/service.go
  pkg/kics/sink.go
  pkg/scan/client.go
  pkg/scan/scan.go
  pkg/scan/utils.go
  pkg/scan/utils_test.go
  test/fixtures/max_file_size/sample.tf
  tools/go.sum
Labels: feature request, community
