Repository Checkmarx/kics, pull requests merged in 2024-03, with the labels that each got.

#6901 fix(openapi): functions must not produce multiple output for same inputs
  assets/queries/openAPI/general/type_has_invalid_keyword/query.rego
  assets/queries/openAPI/general/type_has_invalid_keyword/test/positive11.yaml
  assets/queries/openAPI/general/type_has_invalid_keyword/test/positive_expected_result.json
Labels: openapi

#6911 feat(kics): automatic kics-queries-repo tag change (KICS-1337)
  .github/scripts/kics-queries-repo-branch-creation/config-template/config.yml
  .github/workflows/release-kics-queries-repo-branch.yaml
Labels: feature, query

#6937 revert(terraformer): remove terraformer
  .github/workflows/go-ci.yml
  .grype.yaml
  Dockerfile
  docker/Dockerfile.apispec
  docker/Dockerfile.apispec.debian
  docker/Dockerfile.debian
  docker/Dockerfile.ubi8
  docs/integrations_terraformer.md
  docs/release_checklist.md
  pkg/engine/provider/extract.go
  pkg/scan/utils.go
  pkg/scan/utils_test.go
  pkg/terraformer/terraformer.go
  pkg/terraformer/terraformer_test.go
  pkg/terraformer/utils.go
  res/E2E_CLI_081_RESULT.json
  trivy-ignore.rego
Labels: dockerfile

#6938 fix(community): common/password_and_secrets new allow rule added to permit the ansible playbook update_password field
  assets/queries/common/passwords_and_secrets/regex_rules.json
  assets/queries/common/passwords_and_secrets/test/negative57.yml
Labels: ansible

#6932 update(query): s3 bucket sse bucket disabled queries deprecated
  assets/queries/ansible/aws/s3_bucket_sse_disabled/metadata.json
  assets/queries/ansible/aws/s3_bucket_sse_disabled/query.rego
  assets/queries/ansible/aws/s3_bucket_sse_disabled/test/negative.yaml
  assets/queries/ansible/aws/s3_bucket_sse_disabled/test/positive.yaml
  assets/queries/ansible/aws/s3_bucket_sse_disabled/test/positive_expected_result.json
  assets/queries/cloudFormation/aws/s3_bucket_sse_disabled/metadata.json
  assets/queries/cloudFormation/aws/s3_bucket_sse_disabled/query.rego
  assets/queries/cloudFormation/aws/s3_bucket_sse_disabled/test/negative.json
  assets/queries/cloudFormation/aws/s3_bucket_sse_disabled/test/negative.yaml
  assets/queries/cloudFormation/aws/s3_bucket_sse_disabled/test/positive1.json
  assets/queries/cloudFormation/aws/s3_bucket_sse_disabled/test/positive1.yaml
  assets/queries/cloudFormation/aws/s3_bucket_sse_disabled/test/positive2.json
  assets/queries/cloudFormation/aws/s3_bucket_sse_disabled/test/positive2.yaml
  assets/queries/cloudFormation/aws/s3_bucket_sse_disabled/test/positive_expected_result.json
  assets/queries/terraform/aws/s3_bucket_sse_disabled/metadata.json
  assets/queries/terraform/aws/s3_bucket_sse_disabled/query.rego
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/negative1.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/negative2.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/negative3.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/negative4.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/positive1.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/positive10.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/positive2.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/positive3.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/positive4.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/positive5.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/positive6.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/positive7.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/positive8.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/positive9.tf
  assets/queries/terraform/aws/s3_bucket_sse_disabled/test/positive_expected_result.json
Labels: query, cloudformation, terraform, ansible, aws

#6946 docs(community): add blog post by Firefly
  README.md
Labels: documentation

#6941 update(query): description update to better address the intention of the query
  assets/queries/common/passwords_and_secrets/metadata.json
  e2e/fixtures/E2E_CLI_032_RESULT.json
  e2e/fixtures/E2E_CLI_086_RESULT.json
  e2e/fixtures/E2E_CLI_087_RESULT.json
  e2e/fixtures/E2E_CLI_088_RESULT.json
Labels: query

#6676 fix(query): fix query detecting issues with schemas of type different to object
  assets/queries/openAPI/3.0/additional_properties_too_permissive/query.rego
  assets/queries/openAPI/3.0/additional_properties_too_permissive/test/negative3.json
Labels: query

#6681 fix(query): add 2xx as possible response code
  assets/queries/openAPI/general/success_response_code_undefined_delete_operation/query.rego
  assets/queries/openAPI/general/success_response_code_undefined_delete_operation/test/negative5.json
  assets/queries/openAPI/general/success_response_code_undefined_delete_operation/test/negative6.yaml
  assets/queries/openAPI/general/success_response_code_undefined_get_operation/query.rego
  assets/queries/openAPI/general/success_response_code_undefined_get_operation/test/negative5.json
  assets/queries/openAPI/general/success_response_code_undefined_get_operation/test/negative6.yaml
  assets/queries/openAPI/general/success_response_code_undefined_head_operation/query.rego
  assets/queries/openAPI/general/success_response_code_undefined_head_operation/test/negative5.json
  assets/queries/openAPI/general/success_response_code_undefined_head_operation/test/negative6.yaml
  assets/queries/openAPI/general/success_response_code_undefined_patch_operation/query.rego
  assets/queries/openAPI/general/success_response_code_undefined_patch_operation/test/negative5.json
  assets/queries/openAPI/general/success_response_code_undefined_patch_operation/test/negative6.yaml
  assets/queries/openAPI/general/success_response_code_undefined_post_operation/query.rego
  assets/queries/openAPI/general/success_response_code_undefined_post_operation/test/negative5.json
  assets/queries/openAPI/general/success_response_code_undefined_post_operation/test/negative6.yaml
  assets/queries/openAPI/general/success_response_code_undefined_put_operation/query.rego
  assets/queries/openAPI/general/success_response_code_undefined_put_operation/test/negative5.json
  assets/queries/openAPI/general/success_response_code_undefined_put_operation/test/negative6.yaml
Labels: query

#6893 feat(engine): add new severity metadata field support
  .github/scripts/server-mock/package-lock.json
  assets/queries/ansible/aws/alb_listening_on_http/metadata.json
  docs/commands.md
  docs/dockerhub.md
  e2e/fixtures/E2E_CLI_093_RESULT.json
  e2e/fixtures/E2E_CLI_093_RESULT_2.json
  e2e/fixtures/E2E_CLI_093_RESULT_3.json
  e2e/fixtures/E2E_CLI_093_RESULT_4.json
  e2e/fixtures/E2E_CLI_093_RESULT_5.json
  e2e/fixtures/assets/scan_help
  e2e/testcases/e2e-cli-093_new_severity_metadata_field.go
  go.sum
  internal/console/assets/scan-flags.json
  internal/console/flags/scan_flags.go
  internal/console/scan.go
  pkg/engine/inspector.go
  pkg/engine/inspector_test.go
  pkg/engine/vulnerability_builder.go
  pkg/engine/vulnerability_builder_test.go
  pkg/remediation/scan.go
  pkg/scan/client.go
  pkg/scan/scan.go
  pkg/scanner/scanner_test.go
  test/fixtures/test_new_severity/critical/metadata.json
  test/fixtures/test_new_severity/critical/query.rego
  test/fixtures/test_new_severity/high/metadata.json
  test/fixtures/test_new_severity/high/query.rego
  test/fixtures/test_new_severity/info/metadata.json
  test/fixtures/test_new_severity/info/query.rego
  test/fixtures/test_new_severity/low/metadata.json
  test/fixtures/test_new_severity/low/query.rego
  test/fixtures/test_new_severity/medium/metadata.json
  test/fixtures/test_new_severity/medium/query.rego
  test/fixtures/test_new_severity/test/negative.yaml
  test/fixtures/test_new_severity/test/positive1.yaml
  test/fixtures/test_new_severity/test/positive_expected_result.json
  test/queries_content_test.go
  test/queries_test.go
  test/similarity_id_test.go
Labels: feature

#6866 feat(critical): add critical severity to all report formats
  .github/scripts/queries-validator/metadata-schema.json
  assets/queries/terraform/alicloud/vpc_flow_logs_disabled/metadata.json
  e2e/fixtures/E2E_CLI_031_RESULT.html
  e2e/fixtures/E2E_CLI_040_RESULT.html
  e2e/fixtures/E2E_CLI_081_RESULT.json
  e2e/fixtures/E2E_CLI_089_RESULT.json
  e2e/fixtures/E2E_CLI_090_RESULT.html
  e2e/fixtures/E2E_CLI_091_RESULT.json
  e2e/fixtures/schemas/result-asff.json
  e2e/fixtures/schemas/result-codeclimate.json
  e2e/fixtures/schemas/result-csv.json
  e2e/fixtures/schemas/result-cyclonedx.json
  e2e/fixtures/schemas/result-gl-sast.json
  e2e/fixtures/schemas/result-junit.json
  e2e/fixtures/schemas/result-sonarqube.json
  e2e/testcases/e2e-cli-089_critical_severity.go
  e2e/testcases/e2e-cli-090_critical_severity_all_report_formats.go
  e2e/testcases/e2e-cli-093_new_severity_metadata_field.go
  e2e/utils/html.go
  go.sum
  pkg/kics/resolver_sink_test.go
  pkg/printer/printer_test.go
  pkg/report/asff_test.go
  pkg/report/code_climate_test.go
  pkg/report/csv_test.go
  pkg/report/cyclonedx_test.go
  pkg/report/gitlab_sast_test.go
  pkg/report/html_test.go
  pkg/report/json_test.go
  pkg/report/junit_test.go
  pkg/report/model/asff_test.go
  pkg/report/model/code_climate.go
  pkg/report/model/code_climate_test.go
  pkg/report/model/csv_test.go
  pkg/report/model/cyclonedx.go
  pkg/report/model/cyclonedx_test.go
  pkg/report/model/gitlab_sast_test.go
  pkg/report/model/junit_test.go
  pkg/report/model/sarif.go
  pkg/report/model/sonarqube.go
  pkg/report/model/sonarqube_test.go
  pkg/report/pdf.go
  pkg/report/pdf_test.go
  pkg/report/sarif_test.go
  pkg/report/sonarqube_test.go
  pkg/report/template/html/report.css
  pkg/report/template/html/report.tmpl
  test/fixtures/test_critical_custom_queries/amazon_mq_broker_encryption_disabled/query/metadata.json
  test/fixtures/test_critical_custom_queries/amazon_mq_broker_encryption_disabled/query/query.rego
  test/fixtures/test_critical_custom_queries/amazon_mq_broker_encryption_disabled/test/negative1.yaml
  test/fixtures/test_critical_custom_queries/amazon_mq_broker_encryption_disabled/test/positive1.yaml
  test/fixtures/test_critical_custom_queries/amazon_mq_broker_encryption_disabled/test/positive_expected_result.json
  test/fixtures/test_critical_custom_queries/run_block_injection/query/metadata.json
  test/fixtures/test_critical_custom_queries/run_block_injection/query/query.rego
  test/fixtures/test_critical_custom_queries/run_block_injection/test/negative.yaml
  test/fixtures/test_critical_custom_queries/run_block_injection/test/positive1.yaml
  test/fixtures/test_critical_custom_queries/run_block_injection/test/positive_expected_result.json
  test/helpers.go
Labels: feature

#6906 feat(warning): updated warnings for line detection failure
  pkg/detector/default_detect.go
  pkg/detector/helm/helm_detect.go
Labels: feature

#6952 fix(query): improve query to detect results with tuple
  assets/queries/common/passwords_and_secrets/regex_rules.json
  assets/queries/common/passwords_and_secrets/test/positive50.yaml
  assets/queries/common/passwords_and_secrets/test/positive_expected_result.json
Labels: query

#6890 fix(query): deprecate query Container Requests Not Equal To It's Limits
  assets/queries/k8s/container_requests_not_equal_to_its_limits/metadata.json
  assets/queries/k8s/container_requests_not_equal_to_its_limits/query.rego
  assets/queries/k8s/container_requests_not_equal_to_its_limits/test/negative.yaml
  assets/queries/k8s/container_requests_not_equal_to_its_limits/test/positive.yaml
  assets/queries/k8s/container_requests_not_equal_to_its_limits/test/positive_expected_result.json
  docs/queries/all-queries.md
  docs/queries/kubernetes-queries.md
  docs/queries/kubernetes-queries/aee3c7d2-a811-4201-90c7-11c028be9a46.md
Labels: query

#6889 fix(query): improve queries Container Memory Requests Not Equal To It's Limits and Container CPU Requests Not Equal To It's Limits
  assets/queries/k8s/container_cpu_requests_not_equal_to_its_limits/metadata.json
  assets/queries/k8s/container_cpu_requests_not_equal_to_its_limits/query.rego
  assets/queries/k8s/container_cpu_requests_not_equal_to_its_limits/test/negative1.yaml
  assets/queries/k8s/container_cpu_requests_not_equal_to_its_limits/test/positive_expected_result.json
  assets/queries/k8s/container_memory_requests_not_equal_to_its_limits/metadata.json
  assets/queries/k8s/container_memory_requests_not_equal_to_its_limits/query.rego
  assets/queries/k8s/container_memory_requests_not_equal_to_its_limits/test/negative1.yaml
  assets/queries/k8s/container_memory_requests_not_equal_to_its_limits/test/positive_expected_result.json
Labels: query

#6955 fix(query): improve query platform_flag_with_from
  assets/libraries/common.rego
  assets/queries/dockerfile/using_platform_with_from/metadata.json
  assets/queries/dockerfile/using_platform_with_from/query.rego
  assets/queries/dockerfile/using_platform_with_from/test/negative.dockerfile
  assets/queries/dockerfile/using_platform_with_from/test/positive.dockerfile
  assets/queries/dockerfile/using_platform_with_from/test/positive_expected_result.json
Labels: query

#6962 fix(docs): typo in Google Cloud Storage acronym
  docs/running-kics.md
Labels: community

#6968 build(deps): github.com/docker/docker v24.0.9+incompatible
  go.mod
  go.sum
Labels: docker

#6959 feat(kics): change all tests and appearances of new severity to old severity
  .github/scripts/queries-validator/metadata-schema.json
  docs/commands.md
  docs/dockerhub.md
  e2e/fixtures/E2E_CLI_093_RESULT.json
  e2e/fixtures/E2E_CLI_093_RESULT_2.json
  e2e/fixtures/E2E_CLI_093_RESULT_3.json
  e2e/fixtures/E2E_CLI_093_RESULT_4.json
  e2e/fixtures/E2E_CLI_093_RESULT_5.json
  e2e/fixtures/assets/scan_help
  e2e/testcases/e2e-cli-093_old_severity_metadata_field.go
  internal/console/assets/kics-console
  internal/console/assets/scan-flags.json
  internal/console/flags/scan_flags.go
  internal/console/scan.go
  pkg/engine/inspector.go
  pkg/engine/inspector_test.go
  pkg/engine/vulnerability_builder.go
  pkg/engine/vulnerability_builder_test.go
  pkg/remediation/scan.go
  pkg/scan/client.go
  pkg/scan/scan.go
  test/fixtures/test_old_severity/critical/metadata.json
  test/fixtures/test_old_severity/critical/query.rego
  test/fixtures/test_old_severity/high/metadata.json
  test/fixtures/test_old_severity/high/query.rego
  test/fixtures/test_old_severity/info/metadata.json
  test/fixtures/test_old_severity/info/query.rego
  test/fixtures/test_old_severity/low/metadata.json
  test/fixtures/test_old_severity/low/query.rego
  test/fixtures/test_old_severity/medium/metadata.json
  test/fixtures/test_old_severity/medium/query.rego
  test/fixtures/test_old_severity/test/negative.yaml
  test/fixtures/test_old_severity/test/positive1.yaml
  test/fixtures/test_old_severity/test/positive_expected_result.json
  test/queries_content_test.go
Labels: feature

#6974 fix(queries): removing deprecated queries
  assets/queries/k8s/container_cpu_requests_not_equal_to_its_limits/metadata.json
  assets/queries/k8s/container_cpu_requests_not_equal_to_its_limits/query.rego
  assets/queries/k8s/container_cpu_requests_not_equal_to_its_limits/test/negative.yaml
  assets/queries/k8s/container_cpu_requests_not_equal_to_its_limits/test/negative1.yaml
  assets/queries/k8s/container_cpu_requests_not_equal_to_its_limits/test/positive.yaml
  assets/queries/k8s/container_cpu_requests_not_equal_to_its_limits/test/positive2.yaml
  assets/queries/k8s/container_cpu_requests_not_equal_to_its_limits/test/positive_expected_result.json
  assets/queries/k8s/container_memory_requests_not_equal_to_its_limits/metadata.json
  assets/queries/k8s/container_memory_requests_not_equal_to_its_limits/query.rego
  assets/queries/k8s/container_memory_requests_not_equal_to_its_limits/test/negative.yaml
  assets/queries/k8s/container_memory_requests_not_equal_to_its_limits/test/negative1.yaml
  assets/queries/k8s/container_memory_requests_not_equal_to_its_limits/test/positive.yaml
  assets/queries/k8s/container_memory_requests_not_equal_to_its_limits/test/positive2.yaml
  assets/queries/k8s/container_memory_requests_not_equal_to_its_limits/test/positive_expected_result.json
Labels: query

#6639 fix(query): tokens at NPM Install Command Without Pinned Version
  assets/queries/dockerfile/npm_install_without_pinned_version/query.rego
  assets/queries/dockerfile/npm_install_without_pinned_version/test/negative1.dockerfile
  assets/queries/dockerfile/npm_install_without_pinned_version/test/positive1.dockerfile
  assets/queries/dockerfile/npm_install_without_pinned_version/test/positive_expected_result.json
Labels: query, community
