Repository Checkmarx/kics, pull requests merged in 2024-01, with the labels that each got.

#6838 feat(docs): add community section
  README.md
  docs/CONTRIBUTING.md
  docs/community.md
Labels: feature

#6843 docs(community): add Bedrock Streaming to users list
  README.md
Labels: documentation

#6840 feat(cli): lead with similarity id question
  e2e/fixtures/E2E_CLI_077_RESULT.json
  e2e/testcases/e2e-cli-077_fix_similarity_id.go
  pkg/parser/json/json_line.go
  pkg/parser/json/json_line_test.go
  test/fixtures/similarity_id/1_general_deployment.json
Labels: feature

#6841 feat(results): update cyclonedx reports to support v1.5
  docs/results.md
  pkg/report/model/cyclonedx.go
  pkg/report/model/cyclonedx_test.go
Labels: feature

#6851 feat(engine): improve similarity id
  e2e/fixtures/E2E_CLI_078_RESULT.json
  e2e/testcases/e2e-cli-078_similarity_id_minified_files.go
  pkg/engine/vulnerability_builder.go
  pkg/kics/resolver_sink.go
  pkg/kics/service.go
  pkg/kics/sink.go
  pkg/minified/minified.go
  pkg/minified/minified_test.go
  pkg/model/model.go
  pkg/parser/parser.go
  pkg/parser/parser_test.go
  pkg/remediation/scan.go
  test/fixtures/minified_files_similarity_id/swagger.json
  test/fixtures/minified_files_similarity_id/swagger_1.json
  test/fixtures/test_minified/giantminified.json
  test/main_test.go
Labels: feature

#6846 feat(engine): add a timeout to decode results
  pkg/engine/inspector.go
  pkg/engine/inspector_test.go
  pkg/remediation/scan.go
Labels: feature

#6852 docs(guides): remove ZWSPs & align column separators
  docs/configuration-file.md
  docs/performance.md
  docs/running-kics.md
Labels: documentation, community
