Repository Checkmarx/kics, pull requests merged in 2024-10, with the labels that each got.

#6867 fix(query): improve query name security_group_without_description
  assets/queries/terraform/aws/security_group_without_description/metadata.json
  assets/queries/terraform/aws/security_group_without_description/test/positive_expected_result.json
Labels: query, community

#7292 update(dockerfile): update Dockerfile USER and add OCI labels to all releases
  .github/workflows/go-ci-integration.yml
  .github/workflows/go-e2e.yaml
  .github/workflows/release-apispec.yml
  .github/workflows/release-dkr-image-for-tag.yml
  .github/workflows/release-dkr-image.yml
  .github/workflows/release-docker-github-actions.yaml
  .github/workflows/release-kics-cxone.yaml
  .github/workflows/release-kics-queries-repo-branch.yaml
  .github/workflows/release-nightly.yml
  .grype.yaml
  Dockerfile
  e2e/utils/helper.go
  go.mod
  go.sum
Labels: dockerfile

#7286 update(ghaction): update kics-gh-action.yaml
  .github/workflows/kics-gh-action.yaml
Labels: community
