Repository Checkmarx/kics, pull requests merged in 2025-05, with the labels that each got.

#7454 docs(queries): update universal JSON creation to docker command
  docs/creating-queries.md
Labels: documentation, query, docker, community

#7460 update(deps): update OPA package to version 1.4.2
  go.mod
  go.sum
  pkg/engine/inspector.go
  pkg/engine/inspector_test.go
  pkg/engine/source/source.go
  pkg/remediation/scan.go
Labels: query

#7455 fix(query): fn for s3_bucket_allows_delete_action_from_all_principals query
  assets/libraries/terraform.rego
  assets/queries/terraform/aws/s3_bucket_allows_delete_action_from_all_principals/query.rego
  assets/queries/terraform/aws/s3_bucket_allows_delete_action_from_all_principals/test/negative3.tf
  assets/queries/terraform/aws/s3_bucket_allows_delete_action_from_all_principals/test/positive4.tf
  assets/queries/terraform/aws/s3_bucket_allows_delete_action_from_all_principals/test/positive5.tf
  assets/queries/terraform/aws/s3_bucket_allows_delete_action_from_all_principals/test/positive6.tf
  assets/queries/terraform/aws/s3_bucket_allows_delete_action_from_all_principals/test/positive_expected_result.json
Labels: query, terraform, accuracy

#7445 fix(lint): update lint version
  .github/scripts/report/e2e-html.go
  .github/workflows/check-apache-license.yaml
  .github/workflows/go-ci.yml
  .github/workflows/validate-issues.yaml
  .github/workflows/validate-prs.yaml
  .golangci.yml
  cmd/builder/main.go
  e2e/testcases/e2e-cli-069_ignore_experimental_query.go
  e2e/utils/csv.go
  e2e/utils/helper.go
  e2e/utils/html.go
  e2e/utils/json.go
  internal/console/analyze.go
  internal/console/helpers/exit_handler.go
  internal/console/helpers/helpers.go
  internal/console/list_platforms.go
  internal/console/scan.go
  internal/console/version.go
  internal/constants/constants.go
  pkg/builder/parser/tag/tag_parser.go
  pkg/detector/default_detect.go
  pkg/detector/docker/docker_detect.go
  pkg/detector/helm/helm_detect.go
  pkg/engine/inspector.go
  pkg/engine/provider/extract.go
  pkg/engine/provider/filesystem.go
  pkg/engine/secrets/inspector.go
  pkg/engine/source/filesystem.go
  pkg/kuberneter/auth.go
  pkg/kuberneter/kuberneter.go
  pkg/kuberneter/utils.go
  pkg/model/comment_yaml.go
  pkg/model/model_yaml.go
  pkg/parser/bicep/parser.go
  pkg/parser/buildah/parser.go
  pkg/parser/terraform/terraform.go
  pkg/parser/utils/certificate_utils.go
  pkg/printer/options.go
  pkg/printer/printer.go
  pkg/remediation/scan.go
  pkg/remediation/utils.go
  pkg/report/commons.go
  pkg/report/gitlab_sast.go
  pkg/report/html.go
  pkg/report/model/cyclonedx.go
  pkg/report/model/sarif.go
  pkg/resolver/file/file.go
  pkg/resolver/file/file_test.go
  pkg/resolver/helm/helm.go
  pkg/scan/preview_secrets_mask.go
  pkg/scan/preview_secrets_mask_test.go
  pkg/scan/scan.go
  pkg/utils/get_extension.go
Labels: CI

#7456 fix(query): fix fn for S3_Bucket_Allows_Public_Policy query
  assets/queries/terraform/aws/s3_bucket_with_public_policy/metadata.json
  assets/queries/terraform/aws/s3_bucket_with_public_policy/query.rego
  assets/queries/terraform/aws/s3_bucket_with_public_policy/test/negative1.tf
  assets/queries/terraform/aws/s3_bucket_with_public_policy/test/negative2.tf
  assets/queries/terraform/aws/s3_bucket_with_public_policy/test/positive1.tf
  assets/queries/terraform/aws/s3_bucket_with_public_policy/test/positive2.tf
  assets/queries/terraform/aws/s3_bucket_with_public_policy/test/positive3.tf
  assets/queries/terraform/aws/s3_bucket_with_public_policy/test/positive_expected_result.json
Labels: query, aws, accuracy
